#category: dictionary, movie name as key and a list containing one or more category
﻿category = {'Toy Story':['Animation','Children\'s','Comedy'], 
'Jumanji':['Adventure','Children\'s','Fantasy'], 
'Grumpier Old Men':['Comedy','Romance'], 
'Waiting to Exhale':['Comedy','Drama'], 
'Father of the Bride Part II':['Comedy'], 
'Heat':['Action','Crime','Thriller'], 
'Sabrina':['Comedy','Romance'], 
'Tom and Huck':['Adventure','Children\'s'], 
'Sudden Death':['Action'], 
'GoldenEye':['Action','Adventure','Thriller'], 
'American President':['Comedy','Drama','Romance'], 
'Dracula':['Comedy','Horror'], 
'Balto':['Animation','Children\'s'], 
'Nixon':['Drama'], 
'Cutthroat Island':['Action','Adventure','Romance'], 
'Casino':['Drama','Thriller'], 
'Sense and Sensibility':['Drama','Romance'], 
'Four Rooms':['Thriller'], 
'Ace Ventura':['Comedy'], 
'Money Train':['Action'], 
'Get Shorty':['Action','Comedy','Drama'], 
'Copycat':['Crime','Drama','Thriller'], 
'Assassins':['Thriller'], 
'Powder':['Drama','Sci-Fi'], 
'Leaving Las Vegas':['Drama','Romance'], 
'Othello':['Drama'], 
'Now and Then':['Drama'], 
'Persuasion':['Romance'], 
'City of Lost Children':['Adventure','Sci-Fi'], 
'Shanghai Triad':['Drama'], 
'Dangerous Minds':['Drama'], 
'Twelve Monkeys':['Drama','Sci-Fi'], 
'Wings of Courage':['Adventure','Romance'], 
'Babe':['Children\'s','Comedy','Drama'], 
'Carrington':['Drama','Romance'], 
'Dead Man Walking':['Drama'], 
'Across the Sea of Time':['Documentary'], 
'It Takes Two':['Comedy'], 
'Clueless':['Comedy','Romance'], 
'Cry Beloved Country':['Drama'], 
'Richard III':['Drama','War'], 
'Dead Presidents':['Action','Crime','Drama'], 
'Restoration':['Drama'], 
'Mortal Kombat':['Action','Adventure'], 
'To Die For':['Comedy','Drama'], 
'How to Make an American Quilt':['Drama','Romance'], 
'Seven':['Crime','Thriller'], 
'Pocahontas':['Animation','Children\'s','Musical','Romance'], 
'When Night Is Falling':['Drama','Romance'], 
'Usual Suspects':['Crime','Thriller'], 
'Guardian Angel':['Action','Drama','Thriller'], 
'Mighty Aphrodite':['Comedy'], 
'Lamerica':['Drama'], 
'Big Green':['Children\'s','Comedy'], 
'Georgia':['Drama'], 
'Kids of the Round Table':['Adventure','Children\'s','Fantasy'], 
'Home for the Holidays':['Drama'], 
'Postino Il':['Drama','Romance'], 
'Confessional':['Drama','Mystery'], 
'Indian in the Cupboard':['Adventure','Children\'s','Fantasy'], 
'Eye for an Eye':['Drama','Thriller'], 
'Mr. Holland\'s Opus':['Drama'], 
'Don\'t Be a Menace to South Central While Drinking Your Juice in the Hood':['Comedy'], 
'Two if by Sea':['Comedy','Romance'], 
'Bio-Dome':['Comedy'], 
'Lawnmower Man 2':['Sci-Fi','Thriller'], 
'Two Bits':['Drama'], 
'French Twist':['Comedy','Romance'], 
'Friday':['Comedy'], 
'From Dusk Till Dawn':['Action','Comedy','Crime','Horror'], 
'Fair Game':['Action'], 
'Kicking and Screaming':['Comedy','Drama'], 
'Bed of Roses':['Drama','Romance'], 
'Big Bully':['Comedy','Drama'], 
'Screamers':['Sci-Fi','Thriller'], 
'Nico Icon':['Documentary'], 
'Crossing Guard':['Drama'], 
'Juror':['Drama','Thriller'], 
'White Balloon':['Drama'], 
'Things to Do in Denver when You\'re Dead':['Crime','Drama','Romance'], 
'Antonia\'s Line':['Drama'], 
'Once Upon a Time... When We Were Colored':['Drama'], 
'Last Summer in the Hamptons':['Comedy','Drama'], 
'Angels and Insects':['Drama','Romance'], 
'White Squall':['Adventure','Drama'], 
'Dunston Checks In':['Children\'s','Comedy'], 
'Black Sheep':['Comedy'], 
'Nick of Time':['Action','Thriller'], 
'Journey of August King':['Drama'], 
'Mary Reilly':['Drama','Thriller'], 
'Vampire in Brooklyn':['Comedy','Romance'], 
'Beautiful Girls':['Drama'], 
'Broken Arrow':['Action','Thriller'], 
'In the Bleak Midwinter':['Comedy'], 
'Hate':['Drama'], 
'Shopping':['Action','Thriller'], 
'Heidi Fleiss':['Documentary'], 
'City Hall':['Drama','Thriller'], 
'Bottle Rocket':['Comedy'], 
'Mr. Wrong':['Comedy'], 
'Unforgettable':['Thriller'], 
'Happy Gilmore':['Comedy'], 
'Bridges of Madison County':['Drama','Romance'], 
'Nobody Loves Me':['Comedy','Drama'], 
'Muppet Treasure Island':['Adventure','Children\'s','Comedy','Musical'], 
'Catwalk':['Documentary'], 
'Headless Body in Topless Bar':['Comedy'], 
'Braveheart':['Action','Drama','War'], 
'Taxi Driver':['Drama','Thriller'], 
'Rumble in the Bronx':['Action','Adventure','Crime'], 
'Before and After':['Drama','Mystery'], 
'Margaret\'s Museum':['Drama'], 
'Happiness Is in the Field':['Comedy'], 
'Anne Frank Remembered':['Documentary'], 
'Young Poisoner\'s Handbook':['Crime'], 
'If Lucy Fell':['Comedy','Romance'], 
'Steal Big Steal Little':['Comedy'], 
'Race the Sun':['Drama'], 
'Boys of St. Vincent':['Drama'], 
'Boomerang':['Comedy','Romance'], 
'Chungking Express':['Drama','Mystery','Romance'], 
'Star Maker':['Drama'], 
'Flirting With Disaster':['Comedy'], 
'NeverEnding Story III':['Adventure','Children\'s','Fantasy'], 
'Silence of the Palace':['Drama'], 
'Jupiter\'s Wife':['Documentary'], 
'Pie in the Sky':['Comedy','Romance'], 
'Angela':['Drama'], 
'Frankie Starlight':['Drama','Romance'], 
'Jade':['Thriller'], 
'Nueba Yol':['Comedy','Drama'], 
'Sonic Outlaws':['Documentary'], 
'Down Periscope':['Comedy'], 
'From the Journals of Jean Seberg':['Documentary'], 
'Man of the Year':['Documentary'], 
'Neon Bible':['Drama'], 
'Target':['Action','Drama'], 
'Up Close and Personal':['Drama','Romance'], 
'Birdcage':['Comedy'], 
'Shadows':['Drama'], 
'Gospa':['Drama'], 
'Brothers McMullen':['Comedy'], 
'Bad Boys':['Action'], 
'Amazing Panda Adventure':['Adventure','Children\'s'], 
'Basketball Diaries':['Drama'], 
'Awfully Big Adventure An':['Drama'], 
'Amateur':['Crime','Drama','Thriller'], 
'Apollo 13':['Drama'], 
'Rob Roy':['Drama','Romance','War'], 
'Addiction':['Horror'], 
'Batman Forever':['Action','Adventure','Comedy','Crime'], 
'Belle de jour':['Drama'], 
'Beyond Rangoon':['Drama','War'], 
'Blue in the Face':['Comedy'], 
'Canadian Bacon':['Comedy','War'], 
'Casper':['Adventure','Children\'s'], 
'Clockers':['Drama'], 
'Congo':['Action','Adventure','Mystery','Sci-Fi'], 
'Crimson Tide':['Drama','Thriller','War'], 
'Crumb':['Documentary'], 
'Desperado':['Action','Romance','Thriller'], 
'Devil in a Blue Dress':['Crime','Film-Noir','Mystery','Thriller'], 
'Die Hard':['Action','Thriller'], 
'Doom Generation':['Comedy','Drama'], 
'Feast of July':['Drama'], 
'First Knight':['Action','Adventure','Drama','Romance'], 
'Free Willy 2':['Adventure','Children\s','Drama'], 
'Hackers':['Action','Crime','Thriller'], 
'Jeffrey':['Comedy'], 
'Johnny Mnemonic':['Action','Sci-Fi','Thriller'], 
'Judge Dredd':['Action','Adventure','Sci-Fi'], 
'Jury Duty':['Comedy'], 
'Kids':['Drama'], 
'Living in Oblivion':['Comedy'], 
'Lord of Illusions':['Horror'], 
'Love & Human Remains':['Comedy'], 
'Mad Love':['Drama','Romance'], 
'Mallrats':['Comedy'], 
'Mighty Morphin Power Rangers':['Action','Children\s'], 
'Moonlight and Valentino':['Drama','Romance'], 
'Mute Witness':['Thriller'], 
'Nadja':['Drama'], 
'Net':['Sci-Fi','Thriller'], 
'Nine Months':['Comedy'], 
'Party Girl':['Comedy'], 
'Prophecy':['Horror'], 
'Reckless':['Comedy'], 
'Safe':['Thriller'], 
'Scarlet Letter':['Drama'], 
'Show':['Documentary'], 
'Showgirls':['Drama'], 
'Smoke':['Drama'], 
'Something to Talk About':['Comedy','Drama','Romance'], 
'Species':['Horror','Sci-Fi'], 
'Stars Fell on Henrietta':['Drama'], 
'Strange Days':['Action','Crime','Sci-Fi'], 
'Umbrellas of Cherbourg':['Drama','Musical'], 
'Tie That Binds':['Thriller'], 
'Three Wishes':['Drama'], 
'Total Eclipse':['Drama','Romance'], 
'To Wong Foo Thanks for Everything! Julie Newmar':['Comedy'], 
'Under Siege 2':['Action'], 
'Unstrung Heroes':['Comedy','Drama'], 
'Unzipped':['Documentary'], 
'Walk in the Clouds A':['Drama','Romance'], 
'Waterworld':['Action','Adventure'], 
'White Man\'s Burden':['Drama'], 
'Wild Bill':['Western'], 
'Browning Version':['Drama'], 
'Bushwhacked':['Comedy'], 
'Burnt By the Sun':['Drama'], 
'Before the Rain':['Drama'], 
'Before Sunrise':['Drama','Romance'], 
'Billy Madison':['Comedy'], 
'Babysitter':['Drama','Thriller'], 
'Boys on the Side':['Comedy','Drama'], 
'Cure':['Drama'], 
'Castle Freak':['Horror'], 
'Circle of Friends':['Drama','Romance'], 
'Clerks':['Comedy'], 
'Don Juan DeMarco':['Comedy','Drama','Romance'], 
'Disclosure':['Drama','Thriller'], 
'Dream Man':['Thriller'], 
'Drop Zone':['Action'], 
'Destiny Turns on the Radio':['Comedy'], 
'Death and the Maiden':['Drama','Thriller'], 
'Dolores Claiborne':['Drama','Thriller'], 
'Dumb & Dumber':['Comedy'], 
'Eat Drink Man Woman':['Comedy','Drama'], 
'Exotica':['Drama'], 
'Exit to Eden':['Comedy'], 
'Ed Wood':['Comedy','Drama'], 
'French Kiss':['Comedy','Romance'], 
'Forget Paris':['Comedy','Romance'], 
'Far From Home':['Adventure','Children\s'], 
'Goofy Movie A':['Animation','Children\'s','Comedy','Romance'], 
'Hideaway':['Thriller'], 
'Fluke':['Children\'s','Drama'], 
'Farinelli':['Drama','Musical'], 
'Gordy':['Comedy'], 
'Gumby':['Animation','Children\s'], 
'Glass Shield':['Crime','Drama'], 
'Hoop Dreams':['Documentary'], 
'Heavenly Creatures':['Drama','Fantasy','Romance','Thriller'], 
'Houseguest':['Comedy'], 
'Immortal Beloved':['Drama','Romance'], 
'Heavyweights':['Children\'s','Comedy'], 
'Hunted':['Action'], 
'I.Q.':['Comedy','Romance'], 
'Interview with the Vampire':['Drama','Horror'], 
'Jefferson in Paris':['Drama'], 
'Jerky Boys':['Comedy'], 
'Junior':['Comedy','Sci-Fi'], 
'Just Cause':['Mystery','Thriller'], 
'Kid in King Arthur\'s Court A':['Adventure','Children\'s','Comedy','Fantasy'], 
'Kiss of Death':['Crime','Drama','Thriller'], 
'Star Wars':['Action','Adventure','Fantasy'], 
'Little Women':['Drama'], 
'Little Princess A':['Children\'s','Drama'], 
'Ladybird Ladybird':['Drama'], 
'Enfer':['Drama'], 
'Like Water for Chocolate':['Drama','Romance'], 
'Legends of the Fall':['Drama','Romance','War','Western'], 
'Major Payne':['Comedy'], 
'Little Odessa':['Drama'], 
'My Crazy Life':['Drama'], 
'Love Affair':['Drama','Romance'], 
'Losing Isaiah':['Drama'], 
'Madness of King George':['Drama'], 
'Mary Shelley\'s Frankenstein':['Drama','Horror'], 
'Man of the House':['Comedy'], 
'Mixed Nuts':['Comedy'], 
'Milk Money':['Comedy','Romance'], 
'Miracle on 34th Street':['Drama'], 
'Miami Rhapsody':['Comedy'], 
'My Family':['Drama'], 
'Murder in the First':['Drama','Thriller'], 
'Nobody\'s Fool':['Drama'], 
'Nell':['Drama'], 
'New Jersey Drive':['Crime','Drama'], 
'New York Cop':['Action','Crime'], 
'Beyond Bedlam':['Drama','Horror'], 
'Nemesis 2':['Action','Sci-Fi','Thriller'], 
'Nina Takes a Lover':['Comedy','Romance'], 
'Natural Born Killers':['Action','Thriller'], 
'Only You':['Comedy','Romance'], 
'Once Were Warriors':['Crime','Drama'], 
'Poison Ivy II':['Thriller'], 
'Outbreak':['Action','Drama','Thriller'], 
'Professional':['','Crime'], 
'Perez Family':['Comedy','Romance'], 
'Pyromaniac\'s Love Story':['Comedy','Romance'], 
'Pulp Fiction':['Crime','Drama'], 
'Panther':['Drama'], 
'Pushing Hands':['Comedy'], 
'Priest':['Drama'], 
'Quiz Show':['Drama'], 
'Picture Bride':['Drama','Romance'], 
'Queen Margot':['Drama','Romance'], 
'Quick and the Dead':['Action','Adventure','Western'], 
'Roommates':['Comedy','Drama'], 
'Ready to Wear':['Comedy'], 
'Three Colors':['Drama'], 
'Three Colors':['Drama'], 
'Three Colors':['Drama'], 
'Red Firecracker Green Firecracker':['Drama'], 
'Rent-a-Kid':['Comedy'], 
'Relative Fear':['Horror','Thriller'], 
'Stuart Saves His Family':['Comedy'], 
'Swan Princess':['Animation','Children\'s'], 
'Secret of Roan Inish':['Drama'], 
'Specialist':['Action'], 
'Stargate':['Action','Adventure','Sci-Fi'], 
'Santa Clause':['Children\'s','Comedy','Fantasy'], 
'Shawshank Redemption':['Drama'], 
'Shallow Grave':['Thriller'], 
'Suture':['Film-Noir','Thriller'], 
'Strawberry and Chocolate':['Drama'], 
'Swimming with Sharks':['Comedy','Drama'], 
'Sum of Us':['Comedy'], 
'National Lampoon\'s Senior Trip':['Comedy'], 
'To Live':['Drama'], 
'Tank Girl':['Action','Comedy','Musical','Sci-Fi'], 
'Tales From the Crypt Presents':['Horror'], 
'Star Trek':['Action','Adventure','Sci-Fi'], 
'Tales from the Hood':['Comedy','Horror'], 
'Tom & Viv':['Drama'], 
'Village of the Damned':['Horror','Sci-Fi'], 
'Tommy Boy':['Comedy'], 
'Vanya on 42nd Street':['Drama'], 
'Underneath':['Mystery','Thriller'], 
'Walking Dead':['Drama','War'], 
'What\'s Eating Gilbert Grape':['Drama'], 
'Virtuosity':['Sci-Fi','Thriller'], 
'While You Were Sleeping':['Comedy','Romance'], 
'War':['Adventure','Drama'], 
'Double Happiness':['Drama'], 
'Muriel\'s Wedding':['Comedy','Romance'], 
'Baby-Sitters Club':['Children\'s'], 
'Ace Ventura':['Comedy'], 
'Adventures of Priscilla Queen of the Desert':['Comedy','Drama'], 
'Backbeat':['Drama','Musical'], 
'Bitter Moon':['Drama'], 
'Bullets Over Broadway':['Comedy'], 
'Clear and Present Danger':['Action','Adventure','Thriller'], 
'Client':['Drama','Mystery','Thriller'], 
'Corrina Corrina':['Comedy','Drama','Romance'], 
'Crooklyn':['Comedy'], 
'Crow':['Action','Romance','Thriller'], 
'Cobb':['Drama'], 
'Flintstones':['Children\'s','Comedy'], 
'Forrest Gump':['Comedy','Romance','War'], 
'Four Weddings and a Funeral':['Comedy','Romance'], 
'Higher Learning':['Drama'], 
'I Like It Like That':['Comedy','Drama','Romance'], 
'I Love Trouble':['Action','Comedy'], 
'It Could Happen to You':['Drama','Romance'], 
'Jungle Book':['Adventure','Children\'s','Romance'], 
'Wonderful Horrible Life of Leni Riefenstahl':['Documentary'], 
'Lion King':['Animation','Children\'s','Musical'], 
'Little Buddha':['Drama'], 
'Wes Craven\'s New Nightmare':['Horror'], 
'Mask':['Comedy','Crime','Fantasy'], 
'Maverick':['Action','Comedy','Western'], 
'Mrs. Parker and the Vicious Circle':['Drama'], 
'Naked Gun 33 1/3':['Comedy'], 
'Paper':['Comedy','Drama'], 
'Reality Bites':['Comedy','Drama'], 
'Red Rock West':['Thriller'], 
'Richie Rich':['Children\'s','Comedy'], 
'Safe Passage':['Drama'], 
'River Wild':['Action','Thriller'], 
'Speed':['Action','Romance','Thriller'], 
'Speechless':['Comedy','Romance'], 
'Timecop':['Action','Sci-Fi'], 
'True Lies':['Action','Adventure','Comedy','Romance'], 
'When a Man Loves a Woman':['Drama'], 
'Wolf':['Drama','Horror'], 
'Wyatt Earp':['Western'], 
'Bad Company':['Action'], 
'Man of No Importance A':['Drama'], 
'S.F.W.':['Drama'], 
'Low Down Dirty Shame A':['Action','Comedy'], 
'Boys Life':['Drama'], 
'Colonel Chabert Le':['Drama','Romance','War'], 
'Faster Pussycat! Kill! Kill!':['Action','Comedy','Drama'], 
'Jason\'s Lyric':['Crime','Drama'], 
'Secret Adventures of Tom Thumb':['Adventure','Children\'s'], 
'Street Fighter':['Action'], 
'Coldblooded':['Action'], 
'Desert Winds':['Drama'], 
'Fall Time':['Drama'], 
'Fear':['Horror'], 
'Frank and Ollie':['Documentary'], 
'Girl in the Cadillac':['Drama'], 
'Homage':['Drama'], 
'Mirage':['Action','Thriller'], 
'Open Season':['Comedy'], 
'Two Crimes':['Comedy','Crime','Drama'], 
'Brother Minister':['Documentary'], 
'Highlander III':['Action','Sci-Fi'], 
'Federal Hill':['Drama'], 
'In the Mouth of Madness':['Horror','Thriller'], 
'8 Seconds':['Drama'], 
'Above the Rim':['Drama'], 
'Addams Family Values':['Comedy'], 
'You So Crazy':['Comedy'], 
'Age of Innocence':['Drama'], 
'Airheads':['Comedy'], 
'Air Up There':['Comedy'], 
'Another Stakeout':['Comedy','Thriller'], 
'Bad Girls':['Western'], 
'Barcelona':['Comedy','Romance'], 
'Being Human':['Drama'], 
'Beverly Hillbillies':['Comedy'], 
'Beverly Hills Cop III':['Action','Comedy'], 
'Black Beauty':['Adventure','Children\'s'], 
'Blink':['Thriller'], 
'Blown Away':['Action','Thriller'], 
'Blue Chips':['Drama'], 
'Blue Sky':['Drama','Romance'], 
'Body Snatchers':['Horror','Sci-Fi','Thriller'], 
'Boxing Helena':['Mystery','Romance','Thriller'], 
'Bronx Tale A':['Drama'], 
'Cabin Boy':['Comedy'], 
'Calendar Girl':['Drama'], 
'Carlito\'s Way':['Crime','Drama'], 
'City Slickers II':['Comedy','Western'], 
'Clean Slate':['Comedy'], 
'Cliffhanger':['Action','Adventure','Crime'], 
'Coneheads':['Comedy','Sci-Fi'], 
'Color of Night':['Drama','Thriller'], 
'Cops and Robbersons':['Comedy'], 
'Cowboy Way':['Action','Comedy'], 
'Dangerous Game':['Drama'], 
'Dave':['Comedy','Romance'], 
'Dazed and Confused':['Comedy'], 
'Demolition Man':['Action','Sci-Fi'], 
'Endless Summer 2':['Documentary'], 
'Even Cowgirls Get the Blues':['Comedy','Romance'], 
'Fatal Instinct':['Comedy'], 
'Farewell My Concubine':['Drama','Romance'], 
'Favor':['Comedy','Romance'], 
'Fearless':['Drama'], 
'Fear of a Black Hat':['Comedy'], 
'With Honors':['Comedy','Drama'], 
'Flesh and Bone':['Drama','Mystery','Romance'], 
'Widows\' Peak':['Drama'], 
'For Love or Money':['Comedy'], 
'Firm':['Drama','Thriller'], 
'Free Willy':['Adventure','Children\'s','Drama'], 
'Fresh':['Drama'], 
'Fugitive':['Action','Thriller'], 
'Geronimo':['Drama','Western'], 
'Getaway':['Action'], 
'Getting Even with Dad':['Comedy'], 
'Go Fish':['Drama','Romance'], 
'Good Man in Africa A':['Action','Adventure'], 
'Guilty as Sin':['Crime','Drama','Thriller'], 
'Hard Target':['Action','Adventure','Crime','Thriller'], 
'Heaven & Earth':['Action','Drama','War'], 
'Hot Shots! Part Deux':['Action','Comedy','War'], 
'Live Nude Girls':['Comedy'], 
'Englishman Who Went Up a Hill But Came Down a Mountain':['Comedy','Romance'], 
'House of the Spirits':['Drama','Romance'], 
'House Party 3':['Comedy'], 
'Hudsucker Proxy':['Comedy','Romance'], 
'I\'ll Do Anything':['Comedy','Drama'], 
'In the Army Now':['Comedy','War'], 
'In the Line of Fire':['Action','Thriller'], 
'In the Name of the Father':['Drama'], 
'Inkwell':['Comedy','Drama'], 
'What\'s Love Got to Do with It?':['Drama'], 
'Jimmy Hollywood':['Comedy'], 
'Judgment Night':['Action'], 
'Jurassic Park':['Action','Adventure','Sci-Fi'], 
'Kalifornia':['Drama','Thriller'], 
'Killing Zoe':['Thriller'], 
'King of the Hill':['Drama'], 
'Lassie':['Adventure','Children\'s'], 
'Last Action Hero':['Action','Comedy'], 
'Life with Mikey':['Comedy'], 
'Lightning Jack':['Comedy','Western'], 
'M. Butterfly':['Drama'], 
'Made in America':['Comedy'], 
'Malice':['Thriller'], 
'Man Without a Face':['Drama'], 
'Manhattan Murder Mystery':['Comedy','Mystery'], 
'Menace II Society':['Action','Crime','Drama'], 
'Executive Decision':['Action','Thriller'], 
'In the Realm of the Senses':['Drama'], 
'What Happened Was...':['Comedy','Drama','Romance'], 
'Much Ado About Nothing':['Comedy','Romance'], 
'Mr. Jones':['Drama','Romance'], 
'Mr. Wonderful':['Comedy','Romance'], 
'Mrs. Doubtfire':['Comedy'], 
'Naked':['Drama'], 
'Next Karate Kid':['Action','Children\'s'], 
'New Age':['Drama'], 
'No Escape':['Action','Sci-Fi'], 
'North':['Comedy'], 
'Orlando':['Drama'], 
'Perfect World A':['Action','Drama'], 
'Philadelphia':['Drama'], 
'Piano':['Drama','Romance'], 
'Poetic Justice':['Drama'], 
'Program':['Action','Drama'], 
'Robert A. Heinlein\'s The Puppet Masters':['Horror','Sci-Fi'], 
'Radioland Murders':['Comedy','Mystery','Romance'], 
'Ref':['Comedy'], 
'Remains of the Day':['Drama'], 
'Renaissance Man':['Comedy','Drama','War'], 
'Rising Sun':['Action','Drama','Mystery'], 
'Road to Wellville':['Comedy'], 
'Robocop 3':['Sci-Fi','Thriller'], 
'Robin Hood':['Comedy'], 
'Romeo Is Bleeding':['Crime','Thriller'], 
'Romper Stomper':['Action','Drama'], 
'Ruby in Paradise':['Drama'], 
'Rudy':['Drama'], 
'Saint of Fort Washington':['Drama'], 
'Savage Nights':['Drama'], 
'Schindler\'s List':['Drama','War'], 
'Scout':['Drama'], 
'Searching for Bobby Fischer':['Drama'], 
'Second Best':['Drama'], 
'Secret Garden':['Children\'s','Drama'], 
'Serial Mom':['Comedy','Crime','Horror'], 
'Shadow':['Action'], 
'Shadowlands':['Drama','Romance'], 
'Short Cuts':['Drama'], 
'Simple Twist of Fate A':['Drama'], 
'Sirens':['Comedy','Drama'], 
'Six Degrees of Separation':['Drama'], 
'Sleepless in Seattle':['Comedy','Romance'], 
'Sliver':['Thriller'], 
'Blade Runner':['Film-Noir','Sci-Fi'], 
'Son in Law':['Comedy'], 
'So I Married an Axe Murderer':['Comedy','Romance','Thriller'], 
'Striking Distance':['Action'], 
'Harlem':['Drama'], 
'Super Mario Bros.':['Action','Adventure','Children\s','Sci-Fi'], 
'Surviving the Game':['Action','Adventure','Thriller'], 
'Terminal Velocity':['Action'], 
'Thirty-Two Short Films About Glenn Gould':['Documentary'], 
'Threesome':['Comedy','Romance'], 
'Nightmare Before Christmas':['Children\'s','Comedy','Musical'], 
'Three Musketeers':['Action','Adventure','Comedy'], 
'Tombstone':['Western'], 
'Trial by Jury':['Thriller'], 
'True Romance':['Action','Crime','Romance'], 
'War Room':['Documentary'], 
'Mamma Roma':['Drama'], 
'Pagemaster':['Action','Adventure','Animation','Children\'s'], 
'Paris France':['Comedy'], 
'Beans of Egypt Maine':['Drama'], 
'Killer':['Thriller'], 
'Welcome to the Dollhouse':['Comedy','Drama'], 
'Germinal':['Drama'], 
'Chasers':['Comedy'], 
'Cronos':['Horror'], 
'Naked in New York':['Comedy','Romance'], 
'Kika':['Drama'], 
'Bhaji on the Beach':['Comedy','Drama'], 
'Little Big League':['Children\'s','Comedy'], 
'Slingshot':['Comedy','Drama'], 
'Wedding Gift':['Drama'], 
'Foreign Student':['Drama'], 
'Ciao Professore!':['Drama'], 
'Spanking the Monkey':['Comedy','Drama'], 
'Little Rascals':['Children\'s','Comedy'], 
'Fausto':['Comedy'], 
'Andre':['Adventure','Children\'s'], 
'Hour of the Pig':['Drama','Mystery'], 
'Scorta La':['Thriller'], 
'Princess Caraboo':['Drama'], 
'Celluloid Closet':['Documentary'], 
'Metisse':['Comedy'], 
'Dear Diary':['Comedy','Drama'], 
'I Don\'t Want to Talk About It':['Drama'], 
'Brady Bunch Movie':['Comedy'], 
'Home Alone':['Children\'s','Comedy'], 
'Ghost':['Comedy','Romance','Thriller'], 
'Aladdin':['Animation','Children\'s','Comedy','Musical'], 
'Terminator 2':['Action','Sci-Fi','Thriller'], 
'Dances with Wolves':['Adventure','Drama','Western'], 
'Tough and Deadly':['Action','Drama','Thriller'], 
'Batman':['Action','Adventure','Crime','Drama'], 
'Silence of the Lambs':['Drama','Thriller'], 
'Snow White and the Seven Dwarfs':['Animation','Children\'s','Musical'], 
'Beauty and the Beast':['Animation','Children\'s','Musical'], 
'Pinocchio':['Animation','Children\'s'], 
'Pretty Woman':['Comedy','Romance'], 
'Window to Paris':['Comedy'], 
'Wild Bunch':['Western'], 
'Love and a .45':['Thriller'], 
'Wooden Man\'s Bride':['Drama'], 
'Great Day in Harlem A':['Documentary'], 
'Bye Bye Love':['Comedy'], 
'Criminals':['Documentary'], 
'One Fine Day':['Drama','Romance'], 
'Candyman':['Horror'], 
'Century':['Drama'], 
'Fargo':['Crime','Drama','Thriller'], 
'Homeward Bound II':['Adventure','Children\s'], 
'Heavy Metal':['Action','Adventure','Animation','Horror'], 
'Hellraiser':['Action','Horror','Sci-Fi'], 
'Pallbearer':['Comedy'], 
'Jane Eyre':['Drama','Romance'], 
'Loaded':['Drama','Thriller'], 
'Bread and Chocolate':['Drama'], 
'Aristocats':['Animation','Children\'s'], 
'Flower of My Secret':['Drama'], 
'Two Much':['Comedy','Romance'], 
'Ed':['Comedy'], 
'Scream of Stone':['Drama'], 
'My Favorite Season':['Drama'], 
'Modern Affair A':['Romance'], 
'Condition Red':['Action','Drama','Thriller'], 
'Asfour Stah':['Drama'], 
'Thin Line Between Love and Hate A':['Comedy'], 
'Last Supper':['Drama','Thriller'], 
'Primal Fear':['Drama','Thriller'], 
'Rude':['Drama'], 
'Carried Away':['Drama','Romance'], 
'All Dogs Go to Heaven 2':['Animation','Children\'s','Musical'], 
'Land and Freedom':['War'], 
'Denise Calls Up':['Comedy'], 
'Theodore Rex':['Comedy'], 
'Family Thing A':['Comedy','Drama'], 
'Frisk':['Drama'], 
'Sgt. Bilko':['Comedy'], 
'Jack and Sarah':['Romance'], 
'Girl 6':['Comedy'], 
'Diabolique':['Drama','Thriller'], 
'Little Indian Big City':['Comedy'], 
'Roula':['Drama'], 
'Peanuts - Die Bank zahlt alles':['Comedy'], 
'Happy Weekend':['Comedy'], 
'Nelly & Monsieur Arnaud':['Drama'], 
'Courage Under Fire':['Drama','War'], 
'Mission':['Action','Adventure','Mystery'], 
'Cold Fever':['Comedy','Drama'], 
'Moll Flanders':['Drama'], 
'Superweib Das':['Comedy'], 
'301 302':['Mystery'], 
'Dragonheart':['Action','Adventure','Fantasy'], 
'Und keiner weint mir nach':['Drama','Romance'], 
'Mutters Courage':['Comedy'], 
'Eddie':['Comedy'], 
'Yankee Zulu':['Comedy','Drama'], 
'Billy\'s Holiday':['Drama'], 
'Purple Noon':['Crime','Thriller'], 
'August':['Drama'], 
'James and the Giant Peach':['Animation','Children\'s','Musical'], 
'Fear':['Thriller'], 
'Kids in the Hall':['Comedy'], 
'Faithful':['Comedy'], 
'Underground':['War'], 
'All Things Fair':['Drama'], 
'Bloodsport 2':['Action'], 
'Pather Panchali':['Drama'], 
'Aparajito':['Drama'], 
'World of Apu':['Drama'], 
'Mystery Science Theater 3000':['Comedy','Sci-Fi'], 
'Tarantella':['Drama'], 
'Space Jam':['Adventure','Animation','Children\s','Comedy'], 
'Barbarella':['Adventure','Sci-Fi'], 
'Hostile Intentions':['Action','Drama','Thriller'], 
'They Bite':['Drama'], 
'Some Folks Call It a Sling Blade':['Drama','Thriller'], 
'Run of the Country':['Drama'], 
'Alphaville':['Sci-Fi'], 
'Clean Slate':['Crime'], 
'Tigrero':['Documentary','Drama'], 
'Eye of Vichy':['Documentary'], 
'Windows':['Drama'], 
'It\'s My Party':['Drama'], 
'Country Life':['Drama','Romance'], 
'Operation Dumbo Drop':['Action','Adventure','Comedy','War'], 
'Promise':['Romance'], 
'Mrs. Winterbourne':['Comedy','Romance'], 
'Solo':['Action','Sci-Fi','Thriller'], 
'Under the Domin Tree':['Drama'], 
'Substitute':['Action'], 
'True Crime':['Mystery','Thriller'], 
'Butterfly Kiss':['Thriller'], 
'Feeling Minnesota':['Drama','Romance'], 
'Delta of Venus':['Drama'], 
'To Cross the Rubicon':['Drama'], 
'Angus':['Comedy'], 
'Daens':['Drama'], 
'Faces':['Drama'], 
'Boys':['Drama'], 
'Quest':['Action','Adventure'], 
'Cosi':['Comedy'], 
'Sunset Park':['Drama'], 
'Mulholland Falls':['Crime','Film-Noir','Thriller'], 
'Truth About Cats & Dogs':['Comedy','Romance'], 
'Oliver & Company':['Animation','Children\'s'], 
'Celtic Pride':['Comedy'], 
'Flipper':['Adventure','Children\'s'], 
'Captives':['Drama'], 
'Of Love and Shadows':['Drama'], 
'Dead Man':['Western'], 
'Horseman on the Roof':['Drama'], 
'Switchblade Sisters':['Crime'], 
'Mouth to Mouth':['Comedy'], 
'Visitors':['Comedy','Sci-Fi'], 
'Multiplicity':['Comedy'], 
'Wallace & Gromit':['Animation'], 
'Halfmoon':['Drama'], 
'Haunted World of Edward D. Wood Jr.':['Documentary'], 
'Two Friends':['Drama'], 
'Craft':['Drama','Horror'], 
'Great White Hype':['Comedy'], 
'Last Dance':['Drama'], 
'War Stories':['Documentary'], 
'Cold Comfort Farm':['Comedy'], 
'Institute Benjamenta or This Dream People Call Human Life':['Drama'], 
'Low Life':['Drama'], 
'Heaven\'s Prisoners':['Mystery','Thriller'], 
'Original Gangstas':['Crime'], 
'Rock':['Action','Adventure','Thriller'], 
'Getting Away With Murder':['Comedy'], 
'Cemetery Man':['Comedy','Horror'], 
'Twister':['Action','Adventure','Romance','Thriller'], 
'Barb Wire':['Action','Sci-Fi'], 
'Garcu Le':['Drama'], 
'Honigmond':['Comedy'], 
'Ghost in the Shell':['Animation','Sci-Fi'], 
'Thinner':['Horror','Thriller'], 
'Spy Hard':['Comedy'], 
'Brothers in Trouble':['Drama'], 
'Close Shave A':['Animation','Comedy','Thriller'], 
'Force of Evil':['Film-Noir'], 
'Stupids':['Comedy'], 
'Arrival':['Action','Sci-Fi','Thriller'], 
'Man from Down Under':['Drama'], 
'Dr. Strangelove or':['Sci-Fi','War'], 
'Careful':['Comedy'], 
'Vermont Is For Lovers':['Comedy','Romance'], 
'Month by the Lake A':['Comedy','Drama'], 
'Gold Diggers':['Adventure','Children\s'], 
'Kim':['Children\'s','Drama'], 
'Carmen Miranda':['Documentary'], 
'Ashes of Time':['Drama'], 
'Jar':['Drama'], 
'Maya Lin':['Documentary'], 
'Stalingrad':['War'], 
'Phantom':['Adventure'], 
'Striptease':['Comedy','Crime'], 
'Last of the High Kings':['Drama'], 
'Heavy':['Drama','Romance'], 
'Jack':['Comedy','Drama'], 
'I Shot Andy Warhol':['Drama'], 
'Grass Harp':['Drama'], 
'Someone Else\'s America':['Drama'], 
'Marlene Dietrich':['Documentary'], 
'Costa Brava':['Drama'], 
'Vie est belle La':['Comedy','Drama'], 
'Quartier Mozart':['Comedy'], 
'Touki Bouki':['Drama'], 
'Wend Kuuni':['Drama'], 
'Spirits of the Dead':['Horror'], 
'Babyfever':['Comedy','Drama'], 
'Pharaoh\'s Army':['War'], 
'Trainspotting':['Drama'], 
'\'Til There Was You':['Drama','Romance'], 
'Independence Day':['Action','Sci-Fi'], 
'Stealing Beauty':['Drama'], 
'Fan':['Thriller'], 
'Hunchback of Notre Dame':['Animation','Children\'s','Musical'], 
'Cable Guy':['Comedy'], 
'Kingpin':['Comedy'], 
'Eraser':['Action','Thriller'], 
'Gate of Heavenly Peace':['Documentary'], 
'Nutty Professor':['Comedy','Fantasy','Romance','Sci-Fi'], 
'I Worst of All':['Drama'], 
'An Unforgettable Summer':['Drama'], 
'Last Klezmer':['Documentary'], 
'Hungarian Fairy Tale A':['Fantasy'], 
'My Life and Times With Antonin Artaud':['Drama'], 
'Midnight Dancers':['Comedy','Drama'], 
'Somebody to Love':['Drama'], 
'Very Natural Thing A':['Drama'], 
'Old Lady Who Walked in the Sea':['Comedy'], 
'Daylight':['Action','Adventure','Thriller'], 
'Frighteners':['Comedy','Horror'], 
'Lone Star':['Drama','Mystery'], 
'Harriet the Spy':['Children\'s','Comedy'], 
'Phenomenon':['Drama','Romance'], 
'Walking and Talking':['Romance'], 
'She\'s the One':['Comedy','Romance'], 
'Time to Kill A':['Drama'], 
'American Buffalo':['Drama'], 
'Rendezvous in Paris':['Comedy','Romance'], 
'Alaska':['Adventure','Children\'s'], 
'Fled':['Action','Adventure'], 
'Kazaam':['Children\'s','Comedy','Fantasy'], 
'Bewegte Mann Der':['Comedy'], 
'Magic Hunter':['Drama'], 
'Larger Than Life':['Comedy'], 
'Boy Called Hate A':['Drama'], 
'Power 98':['Action','Mystery','Thriller'], 
'Two Deaths':['Drama'], 
'Very Brady Sequel A':['Comedy'], 
'Stefano Quantestorie':['Comedy','Drama'], 
'Death in the Garden':['Drama'], 
'Crude Oasis':['Romance'], 
'Hedd Wyn':['Drama'], 
'Collectionneuse La':['Drama'], 
'Kaspar Hauser':['Drama'], 
'Echte Kerle':['Comedy','Romance'], 
'Diebinnen':['Drama'], 
'Convent':['Drama'], 
'Adventures of Pinocchio':['Adventure','Children\'s'], 
'Joe\'s Apartment':['Comedy','Musical'], 
'First Wives Club':['Comedy'], 
'Stonewall':['Drama'], 
'Ransom':['Drama','Thriller'], 
'High School High':['Comedy'], 
'Phat Beach':['Comedy'], 
'Foxfire':['Drama'], 
'Chain Reaction':['Action','Adventure','Thriller'], 
'Matilda':['Children\'s','Comedy'], 
'Emma':['Comedy','Drama','Romance'], 
'Crow':['Action','Thriller'], 
'House Arrest':['Comedy'], 
'Eyes Without a Face':['Horror'], 
'Tales from the Crypt Presents':['Horror'], 
'Lotto Land':['Drama'], 
'Story of Xinghua':['Drama'], 
'Day the Sun Turned Cold':['Drama'], 
'Flirt':['Drama'], 
'Big Squeeze':['Comedy','Drama'], 
'Spitfire Grill':['Drama'], 
'Escape from L.A.':['Action','Adventure','Sci-Fi','Thriller'], 
'Cyclo':['Crime','Drama'], 
'Basquiat':['Drama'], 
'Tin Cup':['Comedy','Romance'], 
'Dingo':['Drama'], 
'Ballad of Narayama':['Drama'], 
'Every Other Weekend':['Drama'], 
'Mille bolle blu':['Comedy'], 
'Crows and Sparrows':['Drama'], 
'Godfather':['Action','Crime','Drama'], 
'Hippie Revolution':['Documentary'], 
'Maybe Maybe Not':['Comedy'], 
'Supercop':['Action','Thriller'], 
'Manny & Lo':['Drama'], 
'Celestial Clockwork':['Comedy'], 
'Wife':['Comedy','Drama'], 
'Small Faces':['Drama'], 
'Bound':['Crime','Drama','Romance','Thriller'], 
'Carpool':['Comedy','Crime'], 
'Death in Brunswick':['Comedy'], 
'Kansas City':['Crime'], 
'Gone Fishin\'':['Comedy'], 
'Lover\'s Knot':['Comedy'], 
'Aiqing wansui':['Drama'], 
'Shadow of Angels':['Drama'], 
'Killer':['Crime','Drama'], 
'Nothing to Lose':['Drama'], 
'Police Story 4':['','Action'], 
'Girls Town':['Drama'], 
'Bye-Bye':['Drama'], 
'Relic':['Horror'], 
'Island of Dr. Moreau':['Sci-Fi','Thriller'], 
'First Kid':['Children\'s','Comedy'], 
'Trigger Effect':['Drama','Thriller'], 
'Sweet Nothing':['Drama'], 
'Bogus':['Children\'s','Drama','Fantasy'], 
'Bulletproof':['Action'], 
'Talk of Angels':['Drama'], 
'Land Before Time III':['Animation','Children\s'], 
'1-900':['Romance'], 
'Baton Rouge':['Thriller'], 
'Halloween':['Horror','Thriller'], 
'Twelfth Night':['Comedy','Drama','Romance'], 
'Mother Night':['Drama'], 
'Liebelei':['Romance'], 
'Venice/Venice':['Drama'], 
'Wild Reeds':['Drama'], 
'For Whom the Bell Tolls':['Adventure','War'], 
'Philadelphia Story':['Comedy','Romance'], 
'Singin\' in the Rain':['Musical','Romance'], 
'American in Paris An':['Musical','Romance'], 
'Funny Face':['Comedy','Musical'], 
'Breakfast at Tiffany\'s':['Drama','Romance'], 
'Vertigo':['Mystery','Thriller'], 
'Rear Window':['Mystery','Thriller'], 
'It Happened One Night':['Comedy'], 
'Gaslight':['Mystery','Thriller'], 
'Gay Divorcee':['Comedy','Musical','Romance'], 
'North by Northwest':['Drama','Thriller'], 
'Apartment':['Comedy','Drama'], 
'Some Like It Hot':['Comedy','Crime'], 
'Charade':['Comedy','Mystery','Romance','Thriller'], 
'Casablanca':['Drama','Romance','War'], 
'Maltese Falcon':['Film-Noir','Mystery'], 
'My Fair Lady':['Musical','Romance'], 
'Sabrina':['Comedy','Romance'], 
'Roman Holiday':['Comedy','Romance'], 
'Little Princess':['Children\'s','Drama'], 
'Meet Me in St. Louis':['Musical'], 
'Wizard of Oz':['Adventure','Children\'s','Drama','Musical'], 
'Gone with the Wind':['Drama','Romance','War'], 
'My Favorite Year':['Comedy'], 
'Sunset Blvd.':['Film-Noir'], 
'Citizen Kane':['Drama'], 
'Golden Earrings':['Adventure','Romance'], 
'All About Eve':['Drama'], 
'Women':['Comedy'], 
'Rebecca':['Romance','Thriller'], 
'Foreign Correspondent':['Thriller'], 
'Notorious':['Film-Noir','Romance','Thriller'], 
'Spellbound':['Mystery','Romance','Thriller'], 
'Affair to Remember An':['Romance'], 
'To Catch a Thief':['Comedy','Romance','Thriller'], 
'Father of the Bride':['Comedy'], 
'Band Wagon':['Comedy','Musical'], 
'Ninotchka':['Comedy','Romance'], 
'Love in the Afternoon':['Comedy','Romance'], 
'Gigi':['Musical'], 
'Reluctant Debutante':['Comedy','Drama'], 
'Adventures of Robin Hood':['Action','Adventure'], 
'Mark of Zorro':['Adventure'], 
'Laura':['Crime','Film-Noir','Mystery'], 
'Ghost and Mrs. Muir':['Drama','Romance'], 
'Lost Horizon':['Drama'], 
'Top Hat':['Comedy','Musical','Romance'], 
'To Be or Not to Be':['Comedy','Drama','War'], 
'My Man Godfrey':['Comedy'], 
'Giant':['Drama'], 
'East of Eden':['Drama'], 
'Thin Man':['Mystery'], 
'His Girl Friday':['Comedy'], 
'Around the World in 80 Days':['Adventure','Comedy'], 
'It\'s a Wonderful Life':['Drama'], 
'Mr. Smith Goes to Washington':['Drama'], 
'Bringing Up Baby':['Comedy'], 
'Penny Serenade':['Drama','Romance'], 
'Scarlet Letter':['Drama'], 
'Lady of Burlesque':['Comedy','Mystery'], 
'Of Human Bondage':['Drama'], 
'Angel on My Shoulder':['Crime','Drama'], 
'Little Lord Fauntleroy':['Drama'], 
'They Made Me a Criminal':['Crime','Drama'], 
'Inspector General':['Musical'], 
'Angel and the Badman':['Western'], 
'39 Steps':['Thriller'], 
'Walk in the Sun A':['Drama'], 
'Outlaw':['Western'], 
'Night of the Living Dead':['Horror','Sci-Fi'], 
'African Queen':['Action','Adventure','Romance','War'], 
'Beat the Devil':['Comedy','Drama'], 
'Cat on a Hot Tin Roof':['Drama'], 
'Last Time I Saw Paris':['Drama'], 
'Meet John Doe':['Drama'], 
'Algiers':['Drama','Romance'], 
'Something to Sing About':['Comedy','Musical'], 
'Farewell to Arms A':['Romance','War'], 
'Moonlight Murder':['Mystery'], 
'Blue Angel':['Drama'], 
'Nothing Personal':['Drama','War'], 
'In the Line of Duty 2':['Action'], 
'Dangerous Ground':['Drama'], 
'Picnic':['Drama'], 
'Madagascar Skin':['Romance'], 
'Pompatus of Love':['Comedy','Drama'], 
'Small Wonders':['Documentary'], 
'Fly Away Home':['Adventure','Children\'s'], 
'Bliss':['Drama','Romance'], 
'Grace of My Heart':['Comedy','Drama'], 
'Schlafes Bruder':['Drama'], 
'Maximum Risk':['Action','Adventure','Thriller'], 
'Michael Collins':['Drama','War'], 
'Rich Man\'s Wife':['Thriller'], 
'Infinity':['Drama'], 
'Big Night':['Drama'], 
'Last Man Standing':['Action','Drama','Western'], 
'Caught':['Drama','Thriller'], 
'Set It Off':['Action','Crime'], 
'2 Days in the Valley':['Crime'], 
'Curdled':['Crime'], 
'Associate':['Comedy'], 
'Ed\'s Next Move':['Comedy'], 
'Extreme Measures':['Drama','Thriller'], 
'Glimmer Man':['Action','Thriller'], 
'D3':['Children\'s','Comedy'], 
'Chamber':['Drama'], 
'Apple Dumpling Gang':['Children\'s','Comedy','Western'], 
'Davy Crockett King of the Wild Frontier':['Western'], 
'Escape to Witch Mountain':['Adventure','Children\'s','Fantasy'], 
'Love Bug':['Children\'s','Comedy'], 
'Herbie Rides Again':['Adventure','Children\'s','Comedy'], 
'Old Yeller':['Children\'s','Drama']}

