import random

movies = ['Tie Me Up! Tie Me Down!' ,' High Heels ' ,' Dead Zone '
 ,' Cuba '
 ,' Days of Heaven '
 ,' Octopussy '
 ,' Target Eagle '
 ,' American Angels: Baptism of Blood '
 ,' Subway '
 ,' Camille Claudel '
 ,' Fanny and Alexander '
 ,' Tragedy of a Ridiculous Man '
 ,' A Man & a Woman '
 ,' A Man & a Woman: Twenty Years Later '
 ,' Un Hombre y una Mujer '
 ,' Official Story '
 ,' Lindbergh Kidnapping Case '
 ,' Blackmail '
 ,' Donovan\'s Reef '
 ,' Tucker: The Man & His Dream '
 ,' Scrooged '
 ,' Raiders of the Lost Ark '
 ,' Running Man '
 ,' Predator 2 '
 ,' Colors '
 ,' Zandalee '
 ,' Miles from Home '
 ,' Happy Birthday to Me '
 ,' Final Notice '
 ,' Quintet '
 ,' Devil\'s Eye '
 ,' Wild Strawberries '
 ,' Seventh Seal '
 ,' Germicide '
 ,' Dreams '
 ,' Naked Night '
 ,' Through a Glass Darkly '
 ,' Cries & Whispers '
 ,' Barbarian & the Geisha '
 ,' Casino Royale '
 ,' Dr. No '
 ,' Elephant Walk '
 ,' Ten '
 ,' Man Who Loved Women '
 ,' Hawaii '
 ,' Torn Curtain '
 ,' Duet for One '
 ,' Sound of Music '
 ,' Gonzo Presents Muppet Weird Stuff '
 ,' Tartuffe '
 ,' A New Life '
 ,' Magic '
 ,' Tommy '
 ,' Big Fix '
 ,' Alan & Naomi '
 ,' Fatal Attraction '
 ,' Patriot Games '
 ,' Woman Next Door '
 ,' Hunting '
 ,' Bataan '
 ,' Siegfried '
 ,' Henry '
 ,' Big Blue '
 ,' Flight of the Intruder '
 ,' Nobody\'s Fool '
 ,' After Hours '
 ,' Desperately Seeking Susan '
 ,' A New Leaf '
 ,' Killers of Kilimanjaro '
 ,' Don Juan '
 ,' Babette\'s Feast '
 ,' Vincent '
 ,' Thunderball '
 ,' Lodger (Story of the London Fog) '
 ,' Appointment with Death '
 ,' Murder on the Orient Express '
 ,' Blood Alley '
 ,' Spy Who Loved Me '
 ,' Storm '
 ,' Bloodbath '
 ,' Miami Cops '
 ,' Island of Dr. Moreau '
 ,' Eighty-Four Charing Cross Road '
 ,' Elephant Man '
 ,' Dr Alien '
 ,' Creepshow '
 ,' Sammy & Rosie Get Laid '
 ,' Goalie\'s Anxiety at the Penalty Kick '
 ,' Mademoiselle Striptease '
 ,' Women '
 ,' That Naughty Girl '
 ,' Voulez-Vous Danser Avec Moi? '
 ,' A Coeur Joie '
 ,' Shalako '
 ,' Contempt '
 ,' Dear Brigitte '
 ,' A Very Private Affair '
 ,' Ravishing Idiot '
 ,' Bride Is Much Too Beautiful '
 ,' Doctor at Sea '
 ,' Le Repos Du Guerrier '
 ,' And God Created Woman '
 ,' Ms. Don Juan '
 ,' Siesta '
 ,' Rich & Strange '
 ,' Lionheart '
 ,' E. T. The Extra-Terrestrial '
 ,' Cool World '
 ,' Nadine '
 ,' Batman '
 ,' Blind Date '
 ,' Mother Lode '
 ,' Final Analysis '
 ,' Never Say Never Again '
 ,' Nine & a Half Weeks '
 ,' Killjoy '
 ,' No Mercy '
 ,' Marrying Man '
 ,' Misery '
 ,' Crisis '
 ,' Samson & Delilah '
 ,' Act of Piracy '
 ,' Split Decisions '
 ,' Vampire\'s Kiss '
 ,' Nightmare at Noon '
 ,' Presumed Innocent '
 ,' Reap the Wild Wind '
 ,' Pocket Money '
 ,' Mary White '
 ,' Catch a Rising Star '
 ,' Guilty by Suspicion '
 ,' Secret Beyond the Door '
 ,' Scarlet Street '
 ,' Daffy Duck\'s Quackbusters '
 ,' Rowlf\'s Rhapsodies with the Muppets '
 ,' Gandhi '
 ,' Wind & the Lion '
 ,' Carnal Knowledge '
 ,' Getting Straight '
 ,' Scarlet Letter '
 ,' Count of Old Town '
 ,' Autumn Sonata '
 ,' Gaslight '
 ,' Indiscreet '
 ,' Walpurgis Night '
 ,' Joan of Arc '
 ,' A Woman Called Golda '
 ,' A Walk in the Spring Rain '
 ,' Under Capricorn '
 ,' Notorious '
 ,' June Night '
 ,' Goodbye Again '
 ,' Anastasia '
 ,' Bells of St. Mary\'s '
 ,' Intermezzo '
 ,' A Woman\'s Face '
 ,' Swedenhielms '
 ,' Only One Night '
 ,' Dollar '
 ,' Elena & Her Men '
 ,' Europa Fifty-One '
 ,' Voyage in Italy '
 ,' Fear '
 ,' Stromboli '
 ,' Cactus Flower '
 ,' Hideaways '
 ,' Twenty Four Hours in a Woman\'s Life '
 ,' Programmed to Kill '
 ,' Conan the Barbarian '
 ,' Raw Nerve '
 ,' Think Dirty '
 ,' King of Comedy '
 ,' Best of the Big Laff Off '
 ,' Amadeus '
 ,' White Lightning '
 ,' Unbearable Lightness of Being '
 ,' Life & Times of Judge Roy Bean '
 ,' Airport '
 ,' Day for Night '
 ,' Secrets of Women '
 ,' Burnt Offerings '
 ,' Easy Rider '
 ,' Five Easy Pieces '
 ,' Day of the Locust '
 ,' Goldfinger '
 ,' Exorcist II '
 ,' White Lightning '
 ,' Lady for a Night '
 ,' Charly '
 ,' High Plains Drifter '
 ,' Honkytonk Man '
 ,' Nightbreed '
 ,' Under the Sun of Satan '
 ,' Vagabond '
 ,' Bill Cosby '
 ,' Monty Python & the Holy Grail '
 ,' John Cleese on How to Irritate People '
 ,' Matchmaker '
 ,' For Your Eyes Only '
 ,' Wings '
 ,' Medicine Man '
 ,' Good Fellas '
 ,' Kiss of the Spider Woman '
 ,' Rookie '
 ,' Sting '
 ,' Torpedo Run '
 ,' Instant Justice '
 ,' Cyrano de Bergerac '
 ,' Border Street '
 ,' Firehouse '
 ,' Morituri '
 ,' From the Life of the Marionettes '
 ,' Frantic '
 ,' Coma '
 ,' Dead Ringers '
 ,' Golden Ninja Invasion '
 ,' Exorcist '
 ,' Alice Doesn\'t Live Here Anymore '
 ,' Eyes of the Amaryllis '
 ,' What Price Glory? '
 ,' Inauguration of the Pleasure Dome '
 ,' School Daze '
 ,' End of Innocence '
 ,' Anderson Tapes '
 ,' Father Murphy '
 ,' Skull '
 ,' Quick & The Dead '
 ,' Best Defense '
 ,' Dreamscape '
 ,' Black Rain '
 ,' 8 1/2 '
 ,' One Frightened Night '
 ,' Year My Voice Broke '
 ,' Is Paris Burning? '
 ,' QB VII '
 ,' Island of Dr. Moreau '
 ,' Beyond the Limit '
 ,' Secret Agent '
 ,' Paramount Comedy Theater: Well-Developed '
 ,' Big Bust Out '
 ,' Fourth Protocol '
 ,' Gremlins 2: The New Batch '
 ,' Fast Times at Ridgemont High '
 ,' Mannequin '
 ,' Rabid '
 ,' Party '
 ,' Vampire Raiders '
 ,' Bloopers from Star Trek '
 ,' Destroyer '
 ,' Party Girl '
 ,' Twin Peaks '
 ,' Moonstruck '
 ,' Witches of Eastwick '
 ,' Moonraker '
 ,' Beat Street '
 ,' Running Out of Luck '
 ,' Never on Tuesday '
 ,' Shampoo '
 ,' Power '
 ,' Darling '
 ,' Ugly American '
 ,' Ambassador Bill '
 ,' Big Trail '
 ,' Hombre '
 ,' Coogan\'s Bluff '
 ,' Penn & Teller Get Killed '
 ,' Shy People '
 ,' It\'s My Turn '
 ,' Dangerous Liaisons '
 ,' Reversal of Fortune '
 ,' Meeting Venus '
 ,' Tomorrow Is Forever '
 ,' Like Father Like Son '
 ,' Rope '
 ,' Road to Hong Kong '
 ,' Shirley Valentine '
 ,' City of Joy '
 ,' Appaloosa '
 ,' Seven Minutes in Heaven '
 ,' Hearts of Darkness '
 ,' Tonight for Sure '
 ,' White Hunter '
 ,' Sundays & Cybele '
 ,' Puppet Master '
 ,' Night Gallery '
 ,' Pet Sematary '
 ,' America\'s Music '
 ,' Slap Shot '
 ,' O. C. & Stiggs '
 ,' A Fish Called Wanda '
 ,' A Lesson in Love '
 ,' Brink of Life '
 ,' Betty Blue '
 ,' Hair '
 ,' National Lampoon\'s Christmas Vacation '
 ,' Dersu Uzala '
 ,' Alice '
 ,' Fifth Floor '
 ,' Snow Kill '
 ,' People '
 ,' True Grit '
 ,' Battle of Midway '
 ,' Three Godfathers '
 ,' Hush '
 ,' A Stolen Life '
 ,' Old Maid '
 ,' All about Eve '
 ,' Fly '
 ,' Quick Change '
 ,' Lair of the White Worm '
 ,' Rainbow '
 ,' Man Who Knew Too Much '
 ,' Beauty & the Beast '
 ,' Foreign Correspondent '
 ,' Heiress '
 ,' Boy Who Could Fly '
 ,' Terrorists '
 ,' Wheel of Fortune '
 ,' Do the Right Thing '
 ,' Court-Martial of Jackie Robinson '
 ,' Elvira Madigan '
 ,' Hurricane Smith '
 ,' Fair Game '
 ,' Rape of the Sabines '
 ,' Risky Business '
 ,' I Love All of You (Je Vous Aime) '
 ,' Love Songs '
 ,' Le Choix des Armes '
 ,' Choice of Arms '
 ,' March or Die '
 ,' Last Metro '
 ,' Jean de Florette '
 ,' Fat Man & Little Boy '
 ,' Wild at Heart '
 ,' Family Business '
 ,' Stand & Deliver '
 ,' Looker '
 ,' Fire & Rain '
 ,' Best of Candid Camera '
 ,' Seven Sinners '
 ,' Judgment at Nuremberg '
 ,' Minsky\'s Follies '
 ,' Novice '
 ,' Wings of Desire '
 ,' Until the End of the World '
 ,' Castaway '
 ,' Alfred Hitchcock Presents '
 ,' Delicatessen '
 ,' Great Train Robbery '
 ,' Hanover Street '
 ,' Hunchback '
 ,' My Darling Clementine '
 ,' Wagon Master '
 ,' She Wore a Yellow Ribbon '
 ,' Fantasy Man '
 ,' Monster in the Closet '
 ,' Double Edge '
 ,' Network '
 ,' Chinatown '
 ,' Three Days of the Condor '
 ,' Voyage of the Damned '
 ,' Barfly '
 ,' Wait Until Spring '
 ,' Life with Father '
 ,' A Guy Named Joe '
 ,' Stavisky '
 ,' Time Bandits '
 ,' Shining '
 ,' Flame of Barbary Coast '
 ,' Naked Truth '
 ,' Brood '
 ,' Molly Maguires '
 ,' Beverly Hills Cop '
 ,' Blind Man\'s Bluff '
 ,' La Dolce Vita '
 ,' After the Fox '
 ,' Man with the Golden Gun '
 ,' Marbella '
 ,' Bobo '
 ,' Big Bands '
 ,' Killer Image. '
 ,' Kandyland '
 ,' Campus Man '
 ,' Jubal '
 ,' Purple Rose of Cairo '
 ,' Broadway Danny Rose '
 ,' Husbands & Wives '
 ,' Hannah & Her Sisters '
 ,' Hurricane '
 ,' Between Two Women '
 ,' Cannonball Run '
 ,' Doughnuts & Society '
 ,' Holocaust '
 ,' Meridian '
 ,' Diary of a Hitman '
 ,' Gor '
 ,' Surrender '
 ,' Places in the Heart '
 ,' Not Without My Daughter '
 ,' Heroes '
 ,' Absence of Malice '
 ,' Norma Rae '
 ,' Steel Magnolias '
 ,' Burbs '
 ,' Empire Strikes Back '
 ,' Star Wars '
 ,' Return of the Jedi '
 ,' Hear My Song '
 ,' Slightly Scarlet '
 ,' Gunfight at the OK Corral '
 ,' Range Feud '
 ,' Bloodsucking Pharaohs in Pittsburgh '
 ,' Roma '
 ,' China Syndrome '
 ,' Morning After '
 ,' Klute '
 ,' Electric Horseman '
 ,' Cat Ballou '
 ,' Coming Home '
 ,' Rebecca '
 ,' Jane Eyre '
 ,' Stacey! '
 ,' Naked Obsession '
 ,' Stripped to Kill II '
 ,' Rain Killer '
 ,' Valley Girl '
 ,' Silence of the Lambs '
 ,' Stealing Home '
 ,' Napoleon & Samantha '
 ,' Five Corners '
 ,' Blackboard Jungle '
 ,' My Left Foot '
 ,' Back to the Beach '
 ,' Painted Veil '
 ,' Inspiration '
 ,' Anna Christie '
 ,' Flesh & the Devil '
 ,' Woman of Affairs '
 ,' Anna Karenina '
 ,' Camille '
 ,' Mata Hari '
 ,' Wild Orchids '
 ,' Grand Hotel '
 ,' Susan Lennox '
 ,' Ninotchka '
 ,' Queen Christina '
 ,' Mysterious Lady '
 ,' Joyless Street '
 ,' Single Standard '
 ,' As You Desire Me '
 ,' Romance '
 ,' A Child Is Waiting '
 ,' Tootsie '
 ,' Let It Ride '
 ,' Julius Caesar '
 ,' Nineteen Forty-One '
 ,' Jaws '
 ,' Hot Pursuit '
 ,' Triumph of the Spirit '
 ,' Brannigan '
 ,' Buffet Froid '
 ,' Salvador '
 ,' Horse Soldiers '
 ,' Long John Silver '
 ,' Hustler '
 ,' Star Chamber '
 ,' Clara\'s Heart '
 ,' Burglar '
 ,' Comic Relief '
 ,' Bloodbrothers '
 ,' Rain Man '
 ,' Masculine Feminine '
 ,' Outer Limits '
 ,' Mama\'s Dirty Girls '
 ,' Last Ride of the Dalton Gang '
 ,' Why Me? '
 ,' Number Seventeen '
 ,' Manhunter '
 ,' Bonfire of the Vanities '
 ,' Working Girl '
 ,' Shining Through '
 ,' Slumber Party Massacre III '
 ,' Tokyo Pop '
 ,' Terminator 2 '
 ,' Terminator '
 ,' King Kong Lives! '
 ,' Those Daring Young Men in Their Jaunty '
 ,' At Play in the Fields of the Lord '
 ,' Crazy People '
 ,' Memoirs of an Invisible Man '
 ,' Clan of the Cave Bear '
 ,' Final Terror '
 ,' Reckless '
 ,' High Spirits '
 ,' Roxanne '
 ,' Blade Runner '
 ,' Wall Street '
 ,' Pope of Greenwich Village '
 ,' After School '
 ,' Flaming Frontiers '
 ,' Libeled Lady '
 ,' Inserts '
 ,' Blue Iguana '
 ,' Tender Mercies '
 ,' Nights in White Satin '
 ,' Videodrome '
 ,' Intimate Stranger '
 ,' Highlander '
 ,' Bodycount '
 ,' Tango & Cash '
 ,' There\'s a Girl in My Soup '
 ,' Swing Shift '
 ,' Foul Play '
 ,' Best Friends '
 ,' Butterflies Are Free '
 ,' Overboard '
 ,' Girl from Petrovka '
 ,' Housesitter '
 ,' Wildcats '
 ,' Protocol '
 ,' Seems Like Old Times '
 ,' Sugarland Express '
 ,' Private Benjamin '
 ,' Deceived '
 ,' Arrowsmith '
 ,' Say Goodbye Maggie Cole '
 ,' Circus World '
 ,' Affair in Trinidad '
 ,' Lady from Shanghai '
 ,' Lady in Question '
 ,' Gilda '
 ,' Loves of Carmen '
 ,' Dick Tracy '
 ,' Marnie '
 ,' Hot Child in the City '
 ,' Johnny Dangerously '
 ,' Stark '
 ,' Three Strange Loves '
 ,' My Fair Lady '
 ,' Unforgiven '
 ,' Robin & Marian '
 ,' Children\'s Hour '
 ,' Rainmaker '
 ,' Pat & Mike '
 ,' Lion in Winter '
 ,' Sea of Grass '
 ,' Guess Who\'s Coming to Dinner '
 ,' Desk Set '
 ,' Rooster Cogburn '
 ,' On Golden Pond '
 ,' Adam\'s Rib '
 ,' Boom Town '
 ,' Dragon Seed '
 ,' Little Women '
 ,' Philadelphia Story '
 ,' Without Love '
 ,' Woman of the Year '
 ,' Juice '
 ,' Hoosiers '
 ,' Tin Men '
 ,' Last Temptation of Christ '
 ,' Paris Trout '
 ,' Souvenir '
 ,' A Man for All Seasons '
 ,' Knights & Emeralds '
 ,' Masque of the Red Death '
 ,' Adventures of Smilin\' Jack '
 ,' Adventures in Dinosaur City '
 ,' Allnighter '
 ,' Caddyshack '
 ,' Tom Sawyer '
 ,' Rita '
 ,' Hawk of Powder River '
 ,' Tempest '
 ,' Running Mates '
 ,' Prettykill '
 ,' Judge Priest '
 ,' Harvey '
 ,' If Looks Could Kill '
 ,' Raising Arizona '
 ,' Once Around '
 ,' Loulou '
 ,' World According to Garp '
 ,' Virus '
 ,' Northwest Passage '
 ,' Gardens of Stone '
 ,' Enemies '
 ,' Addams Family '
 ,' Freaks '
 ,' Necessary Roughness '
 ,' A Show of Force '
 ,' Competition '
 ,' Crossing Delancey '
 ,' State of Things '
 ,' Business As Usual '
 ,' A Touch of Class '
 ,' Women in Love. '
 ,' Salome\'s Last Dance '
 ,' Casino '
 ,' Smiles of a Summer Night '
 ,' New Year\'s Day '
 ,' Mephisto '
 ,' Easy Virtue '
 ,' Swing It Sailor! '
 ,' Strictly Business '
 ,' Blame It on Rio '
 ,' Straight to Hell '
 ,' A View to a Kill '
 ,' American Anthem '
 ,' Bedtime Story '
 ,' Courtship of Eddie\'s Father '
 ,' Night Train to Katmandu '
 ,' Port of Call '
 ,' Paper Moon '
 ,' Yellowbeard '
 ,' Adventures of Sherlock Holmes\' Smarter '
 ,' Flashback '
 ,' World\'s Greatest Lover '
 ,' Killer\'s Kiss '
 ,' Deceivers '
 ,' Breathless '
 ,' Born on the Fourth of July '
 ,' Awakenings '
 ,' Annie Hall '
 ,' Manhattan '
 ,' Reds '
 ,' Crimes of the Heart '
 ,' Looking for Mr. Goodbar '
 ,' Godfather '
 ,' Godfather '
 ,' I Will '
 ,' Play It Again '
 ,' Love & Death '
 ,' Sleeper '
 ,' Fellini Satyricon '
 ,' Formula '
 ,' Black Sunday '
 ,' Bobby Deerfield '
 ,' Last of the Red Hot Lovers '
 ,' Mogambo '
 ,' To Catch a Thief '
 ,' Rear Window '
 ,' Woman Who Came Back '
 ,' Stanley & Livingstone '
 ,' Bad Seed '
 ,' Lethal Weapon 2 '
 ,' Blame It on the Bellboy '
 ,' Drop Kick '
 ,' Superman '
 ,' Superman IV: The Quest for Peace '
 ,' Quackser Fortune Has a Cousin in the Bronx '
 ,' Dead Calm '
 ,' Days of Thunder '
 ,' My Life As a Dog '
 ,' Moon in the Gutter '
 ,' Paris '
 ,' Unfaithfully Yours '
 ,' Bullseye! '
 ,' Erik the Viking '
 ,' Dragonard '
 ,' Hard Choices '
 ,' Rain People '
 ,' A Year of the Quiet Sun '
 ,' Desert Trail '
 ,' Almost an Angel '
 ,' Crocodile Dundee '
 ,' American Friend '
 ,' See You in the Morning '
 ,' Arrogant '
 ,' Dracula\'s Widow '
 ,' Ninja Masters of Death '
 ,' Mystery Train '
 ,' Go Tell the Spartans '
 ,' True Stories '
 ,' Ugetsu Monogatari '
 ,' Rebel Rousers '
 ,' Plain Clothes '
 ,' Whose Life Is It '
 ,' Running on Empty '
 ,' Funny about Love '
 ,' A Chorus Line '
 ,' Stewardess School '
 ,' Big Town '
 ,' Rumble Fish '
 ,' Outsiders '
 ,' Priceless Beauty '
 ,' Streets of Fire '
 ,' Men Don\'t Leave '
 ,' Everybody\'s All American '
 ,' Cape Fear '
 ,' Postman Always Rings Twice '
 ,' Crashing Thru '
 ,' Get Out Your Handkerchiefs '
 ,' Boy Friend '
 ,' Hard To Kill '
 ,' Psycho '
 ,' Jet Pilot '
 ,' Under Cover '
 ,' A Streetcar Named Desire '
 ,' Golden Child '
 ,' Statue '
 ,' Christopher Columbus '
 ,' In Country '
 ,' Wild Geese '
 ,' Second Coming of Suzanne. '
 ,' Bronco Billy '
 ,' Gauntlet '
 ,' Ratboy '
 ,' Lady Vanishes '
 ,' Kitchen Toto '
 ,' Carlton-Browne of the F.O. '
 ,' Racketeer '
 ,' Mr. & Mrs. Smith '
 ,' Alrededor de Medianoche '
 ,' Losin\' It '
 ,' Into the Homeland '
 ,' Boxing Babes '
 ,' Shock \'em Dead '
 ,' Heller in Pink Tights '
 ,' Two Women '
 ,' Gold of Naples '
 ,' Yesterday '
 ,' Legend of the Lost '
 ,' Brass Target '
 ,' Fall of the Roman Empire '
 ,' El Cid '
 ,' Desire under the Elms '
 ,' Two Nights with Cleo '
 ,' Black Orchid '
 ,' Angela '
 ,' A Special Day '
 ,' Blood Feud '
 ,' Sophia Loren '
 ,' Running Away '
 ,' Man of La Mancha '
 ,' Operation Crossbow '
 ,' Courage '
 ,' RAD '
 ,' Secret Admirer '
 ,' Cocaine Cowboys '
 ,' Test Pilot '
 ,' Ape Man '
 ,' Mission '
 ,' Curly Sue '
 ,' Lolita '
 ,' Sex '
 ,' Green Card '
 ,' Gator Bait II '
 ,' Being There '
 ,' Terms of Endearment '
 ,' Woman Times Seven '
 ,' Bliss of Mrs. Blossom '
 ,' Postcards from the Edge '
 ,' Two Mules for Sister Sara '
 ,' Dragonfight '
 ,' Back Door to Heaven '
 ,' Ciao Italia '
 ,' Madonna '
 ,' A Certain Sacrifice '
 ,' National Enquirer '
 ,' Immaculate Collection '
 ,' Madonna Live '
 ,' Madonna '
 ,' Madonna '
 ,' Hot to Trot '
 ,' Fire with Fire '
 ,' Hot Spot '
 ,' Amarcord '
 ,' Casablanca Express '
 ,' Out of the Blue '
 ,' Sands of Iwo Jima '
 ,' Hand '
 ,' Deep Cover '
 ,' Il Bidone '
 ,' El Guerrero Solitario '
 ,' Heartbreak Ridge '
 ,' Goodbye Girl '
 ,' Audrey Rose '
 ,' Polyester '
 ,' Robin Hood: Prince of Thieves '
 ,' White Sands '
 ,' Color of Money '
 ,' Children of a Lesser God '
 ,' Matador '
 ,' Women on the Verge of a Nervous Breakdown '
 ,' Pepi Luci Bom '
 ,' Forgotten '
 ,' Flame & the Arrow '
 ,' After the Shock '
 ,' Modern Love '
 ,' Riff Raff '
 ,' Glory Stompers '
 ,' Dances with Wolves '
 ,' Matewan '
 ,' Mississippi Burning '
 ,' Eiger Sanction '
 ,' Unsettled Land '
 ,' Cat Chaser '
 ,' Accused '
 ,' Winter People '
 ,' Reuben '
 ,' Made in Heaven '
 ,' Top Gun '
 ,' Witness '
 ,' House on Carroll Street '
 ,' Racing with the Moon '
 ,' Lovesick '
 ,' She\'s Having a Baby '
 ,' Greatest Story Ever Told '
 ,' Hawks '
 ,' So Fine '
 ,' Paths of Glory '
 ,' Tom Jones '
 ,' Sunshine Boys '
 ,' Caddyshack 2 '
 ,' Internal Affairs '
 ,' JFK '
 ,' New Jack City '
 ,' Scenes from a Mall '
 ,' Hope & Glory '
 ,' Ryan\'s Daughter '
 ,' Man Who Loved Cat Dancing '
 ,' Man Who Shot Liberty Valance '
 ,' Dead-Bang '
 ,' Big Top Pee-wee '
 ,' Time Machine '
 ,' Cabaret '
 ,' Arthur '
 ,' A Matter of Time '
 ,' New York '
 ,' Nightmare on Elm Street '
 ,' Fiendish Plot of Dr. Fu Manchu '
 ,' Four American Composers '
 ,' Asphalt Jungle '
 ,' Ladies of the Chorus '
 ,' How to Marry a Millionaire '
 ,' Hollywood Out-Takes & Rare Footage '
 ,' Nothing But Trouble '
 ,' Wisdom '
 ,' One Crazy Summer '
 ,' We\'re No Angels '
 ,' No Small Affair '
 ,' Ghost '
 ,' About Last Night '
 ,' Six Weeks '
 ,' Return of October '
 ,' Come Back '
 ,' Going Places '
 ,' Monte Walsh '
 ,' Mr. Arkadin '
 ,' White of the Eye '
 ,' Producers '
 ,' Front '
 ,' House of the Rising Sun '
 ,' In a Shallow Grave '
 ,' Mc Q '
 ,' Lady from Louisiana '
 ,' Wait Until Spring Bandini '
 ,' Long Voyage Home '
 ,' Trouble with Harry '
 ,' Encounters '
 ,' Hud '
 ,' Operation Pacific '
 ,' Surf Nazis Must Die '
 ,' Teahouse of the August Moon '
 ,' Back in the U.S.S.R. '
 ,' Man Who Haunted Himself '
 ,' Prisoner of Honor. '
 ,' Control '
 ,' Desert Rider '
 ,' Wholly Moses! '
 ,' Star Trek VI: The Undiscovered Country '
 ,' Star Trek V: The Final Frontier '
 ,' Circuitry Man '
 ,' Cobra '
 ,' Beverly Hills Cop II '
 ,' Red Sonja '
 ,' To Joy '
 ,' Macbeth '
 ,' Vertigo '
 ,' Young Love: Lemon Popsicle Seven '
 ,' Crack-Up '
 ,' Bury Me Not on the Lone Prairie '
 ,' Law & Order '
 ,' Man from Montana '
 ,' Long Gray Line '
 ,' Rio Grande '
 ,' Wings of Eagles '
 ,' Jamaica Inn '
 ,' Big Jake '
 ,' Quiet Man '
 ,' After the Rehearsal '
 ,' Big Jim McLain '
 ,' Smith! '
 ,' Wild One '
 ,' Manxman '
 ,' International Velvet '
 ,' Scanners '
 ,' Trick or Treat '
 ,' 48 Hrs. '
 ,' Trip to Bountiful '
 ,' Mister Roberts '
 ,' Z '
 ,' Maurice '
 ,' Hamlet '
 ,' La Femme Nikita '
 ,' Honeymoon in Vegas '
 ,' Going for the Gold '
 ,' Shout at the Devil '
 ,' A Smoky Mountain Christmas '
 ,' Getting Physical '
 ,' Torn Apart '
 ,' From the Hip '
 ,' Ratings Game '
 ,' Class Act '
 ,' Water '
 ,' Silent Movie '
 ,' Pink Cadillac '
 ,' Jerk '
 ,' Wild Times '
 ,' Sweet Liberty '
 ,' Grease II '
 ,' Married to the Mob '
 ,' Ladyhawke '
 ,' Fabulous Baker Boys '
 ,' Into the Night '
 ,' Russia House '
 ,' Tequila Sunrise '
 ,' B. A. D. Cats '
 ,' Last Movie '
 ,' Dillinger '
 ,' Little Dorrit '
 ,' My Best Girl '
 ,' Seizure '
 ,' A Chorus of Disapproval '
 ,' Rome Adventure '
 ,' Drowning by Numbers '
 ,' Born to Ride '
 ,' Her Alibi '
 ,' Glitz '
 ,' Dangerous Pursuit '
 ,' Experiment in Terror '
 ,' Hideaways '
 ,' What\'s New Pussycat '
 ,' What\'s New Pussycat? '
 ,' Packin\' It In '
 ,' Naked Gun: From the Files of Police Squad! '
 ,' In Too Deep '
 ,' Twins '
 ,' Experts '
 ,' Naked Lie '
 ,' Mistress '
 ,' Pleasure Palace '
 ,' Adam at 6 A.M. '
 ,' Web of Deceit '
 ,' New York Stories '
 ,' Dreams Lost '
 ,' Au Revoir les Enfants '
 ,' Quo Vadis '
 ,' Fighting Kentuckian '
 ,' Zardoz '
 ,' Police Academy 6: City under Siege '
 ,' Police Academy 5: Assignment Miami Beach '
 ,' Police Academy 3: Back in Training '
 ,' America\'s Music '
 ,' Julia '
 ,' Devils '
 ,' Ransom '
 ,' Cadillac Man '
 ,' Best of Times '
 ,' Death of a Salesman '
 ,' It Started with a Kiss '
 ,' Money '
 ,' Empire of the Sun '
 ,' Comfort of Strangers '
 ,' On Her Majesty\'s Secret Service '
 ,' Pretty in Pink '
 ,' PK. & the Kid. '
 ,' Lone Star Trail '
 ,' Summer '
 ,' Planes '
 ,' Pretty Woman '
 ,' Flatliners '
 ,' Hook '
 ,' Riders of Pasco Basin '
 ,' Gotta Dance '
 ,' Desperate Hours '
 ,' Gung Ho '
 ,' Shooting Elizabeth '
 ,' Strangers on a Train '
 ,' Sacketts '
 ,' To Die Standing '
 ,' Rodeo Girl '
 ,' Butch Cassidy & the Sundance Kid '
 ,' Hellfighters '
 ,' Final Countdown '
 ,' Blue Velvet '
 ,' Cousins '
 ,' Black & White in Color '
 ,' Another Woman '
 ,' Night on Earth '
 ,' Permanent Record '
 ,' Fisher King '
 ,' Another You '
 ,' Young Lions '
 ,' Cheerleader Camp '
 ,' Trapper County War '
 ,' Angel & the Badman '
 ,' Impulse '
 ,' Track Twenty-Nine '
 ,' Freejack '
 ,' John Wayne Matinee Double Feature '
 ,' Smallest Show on Earth '
 ,' Innerspace '
 ,' Presidio '
 ,' Joe Versus the Volcano '
 ,' Doors '
 ,' Welcome Home '
 ,' Cancel My Reservation '
 ,' North by Northwest '
 ,' Russians Are Coming '
 ,' Exodus '
 ,' Ballad of Narayama '
 ,' Out of the Darkness '
 ,' Garden of the Finzi-Continis '
 ,' Steppenwolf '
 ,' Mackintosh Man '
 ,' Partner '
 ,' Conformist '
 ,' Dirty Harry '
 ,' Ferris Bueller\'s Day Off '
 ,' Legend '
 ,' Buddy System '
 ,' A Dry White Season '
 ,' Rocky Horror Picture Show '
 ,' War & Peace '
 ,' Defense of the Realm '
 ,' Basil The Rat '
 ,' Fawlty Towers '
 ,' Going Under '
 ,' U S. Sub Standard. '
 ,' Hells Angels on Wheels '
 ,' Passenger '
 ,' Last Tango in Paris '
 ,' Indigo Autumn & Lilac Dream '
 ,' Kriemhild\'s Revenge '
 ,' Johnny Tiger '
 ,' Head Office '
 ,' Live & Let Die '
 ,' Le Charme Discret de la Bourgeoisie '
 ,' Blue City '
 ,' Bad Boys '
 ,' Whoopee Boys '
 ,' Last Picture Show '
 ,' Diamond Trap '
 ,' Endless Love '
 ,' Rocky '
 ,' Cocktail '
 ,' Sabotage '
 ,' Madame Rosa '
 ,' Fozzie\'s Muppet Scrapbook '
 ,' Desiree '
 ,' Spartacus '
 ,' Guys & Dolls '
 ,' Until They Sail '
 ,' Coming to America '
 ,' Lilies of the Field '
 ,' River\'s Edge '
 ,' Ruthless People '
 ,' Secret of My Success '
 ,' Shop on Main Street '
 ,' Funny Farm '
 ,' Lonely Passion of Judith Hearne '
 ,' California Suite '
 ,' Maximum Overdrive '
 ,' Pale Rider '
 ,' Kissing Place '
 ,' French Lesson '
 ,' Roller Blade '
 ,' A Shot in the Dark '
 ,' Treasure Seekers '
 ,' Missing '
 ,' Picasso Trigger '
 ,' Hard Ticket to Hawaii '
 ,' Diamonds are Forever '
 ,' Baby Face '
 ,' Violent Men '
 ,' Cocoon '
 ,' Clockwise '
 ,' Romantic Comedy '
 ,' Outland '
 ,' Hang \'em High '
 ,' Basic Instinct '
 ,' Total Recall '
 ,' Stakeout '
 ,' Unnamable II '
 ,' Trip '
 ,' Ironweed '
 ,' Kramer vs. Kramer '
 ,' Still of the Night '
 ,' Defending Your Life '
 ,' Deer Hunter '
 ,' Falling in Love '
 ,' Heartburn '
 ,' Silkwood '
 ,' Sophie\'s Choice '
 ,' Out of Africa '
 ,' French Lieutenant\'s Woman '
 ,' Plenty '
 ,' A Cry in the Dark '
 ,' She-Devil '
 ,' Death Becomes Her '
 ,' Kids & Pesticides '
 ,' On a Clear Day You Can See Forever '
 ,' Nuts '
 ,' Yentl '
 ,' Funny Girl '
 ,' Fellow Traveller '
 ,' Dodesukaden '
 ,' Sicilian '
 ,' So Ends Our Night '
 ,' Sword of the Valiant '
 ,' Devil\'s Wanton '
 ,' Driving Miss Daisy '
 ,' Seventh Cross '
 ,' Between Friends '
 ,' Raintree County '
 ,' Driver\'s Seat '
 ,' Reflections in a Golden Eye '
 ,' X '
 ,' Secret Ceremony '
 ,' Cleopatra '
 ,' Father of the Bride '
 ,' Who\'s Afraid of Virginia Woolf? '
 ,' A Little Night Music '
 ,' Giant '
 ,' Rumor Mill '
 ,' Lassie Come Home '
 ,' Return Engagement '
 ,' Hammersmith Is Out '
 ,' Super Duper Bloopers '
 ,' Elizabeth Taylor Collection '
 ,' Ash Wednesday '
 ,' Last Time I Saw Paris '
 ,' Cimarron '
 ,' Apache Woman '
 ,' Gary Numan - Berzerker '
 ,' Mystic Pizza '
 ,' Dogfight '
 ,' Adventures of Rex & Rinty '
 ,' Daphnis & Chloe '
 ,' Marathon '
 ,' Fort Apache '
 ,' Wee Willie Winkie '
 ,' Big Shots '
 ,' Doin\' Time on Planet Earth '
 ,' All the Right Moves '
 ,' Some Kind of Wonderful '
 ,' All New Tales from the Crypt '
 ,' Back to the Future '
 ,' Winter Light '
 ,' Silence '
 ,' Magician '
 ,' Four Horsemen of the Apocalypse '
 ,' Critical Condition '
 ,' Center of the Web '
 ,' Border Shootout '
 ,' Lean on Me '
 ,' On Wings of Eagles '
 ,' Texas '
 ,' Allegheny Uprising '
 ,' Dark Command '
 ,' Peggy Sue Got Married '
 ,' Dear America '
 ,' Prizzi\'s Honor '
 ,' Man with Two Brains '
 ,' Crimes of Passion '
 ,' Jewel of the Nile '
 ,' Romancing the Stone '
 ,' Accidental Tourist '
 ,' Sea Chase '
 ,' Another Time '
 ,' Cannibal Women in the Avocado Jungle of Death '
 ,' Mr Love. '
 ,' 2001: A Space Odyssey '
 ,' Persona '
 ,' Scenes from a Marriage '
 ,' Hour of the Wolf '
 ,' Passion of Anna '
 ,' Dangerous Moves '
 ,' Sayonara '
 ,' Where Eagles Dare '
 ,' Teen Wolf '
 ,' Amazon '
 ,' Paper Chase '
 ,' Virgin Spring '
 ,' Spider\'s Stratagem '
 ,' Play Misty for Me '
 ,' Going Ape '
 ,' Cool Hand Luke '
 ,' Phantom of the Ritz '
 ,' Crash & Burn '
 ,' After Dark My Sweet '
 ,' Christopher Columbus: The Discovery '
 ,' Young Sherlock Holmes '
 ,' Doc Hollywood '
 ,' Baja Oklahoma '
 ,' Aliens '
 ,' Alien Three '
 ,' Alien: resurrection '
 ,' Alien '
 ,' One Woman or Two '
 ,' Soggy Bottom U. S. A. '
 ,' Bang the Drum Slowly '
 ,' Catamount Killing '
 ,' Fuzz '
 ,' Shoot Loud '
 ,' Bedazzled '
 ,' Prince & the Pauper '
 ,' One Hundred Rifles '
 ,' Wild Party '
 ,' Bandolero! '
 ,' Last of Sheila '
 ,' Hannie Caulder '
 ,' Sounds of the Seventies...& the Beat Goes '
 ,' Bird '
 ,' Meet Millie '
 ,' Hell Comes to Frogtown '
 ,' Fortune Cookie '
 ,' Sun Shines Bright '
 ,' Squeeze '
 ,' Start the Revolution Without Me '
 ,' Major League '
 ,' Bright Lights '
 ,' Lost Boys '
 ,' Cookie '
 ,' Conversation '
 ,' American Graffiti '
 ,' Dangerous When Wet '
 ,' Stir Crazy '
 ,' Young Einstein '
 ,' Killing '
 ,' Cahill '
 ,' Savage Intruder '
 ,' Sheltering Sky '
 ,' An Officer & a Gentleman '
 ,' Black Widow '
 ,' Legal Eagles '
 ,' Bloody Mama '
 ,' A Patch of Blue '
 ,' I Died a Thousand Times '
 ,' Tentacles '
 ,' Scalphunters '
 ,' A Day in October '
 ,' A Fistful of Dollars '
 ,' My Science Project '
 ,' Great Race '
 ,' Searchers '
 ,' Meteor '
 ,' Rebel Without a Cause '
 ,' West Side Story '
 ,' Trash '
 ,' A Big Hand for the Little Lady '
 ,' A Fine Madness '
 ,' Glass Menagerie '
 ,' Harry & Son '
 ,' Rachel '
 ,' Paris Blues '
 ,' Fugitive Kind '
 ,' Mr. & Mrs. Bridge '
 ,' State of Grace '
 ,' Shadow of a Doubt '
 ,' Men '
 ,' Stage Fright '
 ,' Magic Town '
 ,' That Lucky Touch '
 ,' Lust for Gold '
 ,' Heat '
 ,' Employee\'s Entrance '
 ,' Night Is My Future '
 ,' Witches '
 ,' Vera Cruz '
 ,' Apache '
 ,' Twilight\'s Last Gleaming '
 ,' Frisco Kid '
 ,' Bank on the Stars '
 ,' Law of Desire '
 ,' Quiller Memorandum '
 ,' Longest Day '
 ,' Name of the Rose '
 ,' Bloodsport '
 ,' Torment '
 ,' Pelle the Conqueror '
 ,' Taps '
 ,' Freshman '
 ,' Last Emperor '
 ,' Grim Reaper '
 ,' Le Dernier Combat '
 ,' Too Beautiful for You '
 ,' Fire '
 ,' Heavens Above '
 ,' One Eyed Jacks '
 ,' Swing It '
 ,' Wolf at the Door '
 ,' Modern Times '
 ,' Thunderbolt & Lightfoot '
 ,' A Nous la Liberte '
 ,' Scum '
 ,' Inside Man '
 ,' Apocalypse Now '
 ,' Bellboy & the Playgirls '
 ,' Terror '
 ,' Raven '
 ,' They Came from Within '
 ,' Boy in Blue '
 ,' Killer Tomatoes Strike Back '
 ,' Attack of the Killer Tomatoes '
 ,' Untouchables '
 ,' Wise Guys '
 ,' American Autobahn '
 ,' Final Alliance '
 ,' Bounty '
 ,' Little Prince '
 ,' Posse '
 ,' Firefox '
 ,' Penitentiary III '
 ,' Ginger & Fred '
 ,' Wrong Box '
 ,' Wagonmaster '
 ,' They Were Expendable '
 ,' Last Hurrah '
 ,' Law of the Golden West '
 ,' Pioneer Marshal '
 ,' Ranger of the Cherokee Strip '
 ,' Vanishing Westerner '
 ,' Bandits of Dark Canyon '
 ,' Bold Frontiersman '
 ,' Wild Frontier '
 ,' Firemen\'s Ball '
 ,' Local Hero '
 ,' French Connection '
 ,' To Live & Die in L. A. '
 ,' Ferry to Hong Kong '
 ,' Eddie Murphy '
 ,' Secret Policeman\'s Private Parts '
 ,' Up the Creek '
 ,' Yol '
 ,' Sara Dane '
 ,' Night Tide '
 ,' His Majesty O\'Keefe '
 ,' North to Alaska '
 ,' Flight to Fury '
 ,' Ride in the Whirlwind '
 ,' Powderkeg '
 ,' I Confess '
 ,' Thirty-Nine Steps '
 ,' Topaz '
 ,' Murder '
 ,' Dial M for Murder '
 ,' Young & Innocent '
 ,' Creature from Black Lake '
 ,' Chariots of Fire '
 ,' Monty Python Live at the Hollywood Bowl '
 ,' Man Who Would Be King '
 ,' Victory '
 ,' Kelly\'s Heroes '
 ,' Next of Kin '
 ,' Chattahoochee '
 ,' Angelic Conversation '
 ,' Down by Law '
 ,' Killing Fields '
 ,' Survival Zone '
 ,' Monty Python\'s Life of Brian '
 ,' Monty Python\'s the Meaning of Life '
 ,' Red Tent '
 ,' Dakota '
 ,' Viva Zapata! '
 ,' Green Berets '
 ,' Big Bad John '
 ,' Ticket of Leave Man '
 ,' D-Day '
 ,' Apprenticeship of Duddy Kravitz '
 ,' A Clockwork Orange '
 ,' Full Metal Jacket '
 ,' Sanshiro Sugata '
 ,' Rhapsody in August '
 ,' No Regrets for Our Youth '
 ,' Bad Sleep Well '
 ,' Idiot '
 ,' Rashomon '
 ,' Sanjuro '
 ,' Seven Samurai '
 ,' Throne of Blood '
 ,' Yojimbo '
 ,' Kagemusha '
 ,' Ikiru '
 ,' Empire of Spiritual Ninja '
 ,' Ninja '
 ,' Metropolis '
 ,' Cloak & Dagger '
 ,' Spiders '
 ,' Human Desire '
 ,' Spies '
 ,' Testament of Dr. Mabuse '
 ,' Fury '
 ,' Mo\' Better Blues '
 ,' Matt Talbot '
 ,' Will Rogers '
 ,' For a Few Dollars More '
 ,' Thirty Seconds over Tokyo '
 ,' Class of 1984 '
 ,' Juggernaut '
 ,' Good Morning '
 ,' Blood on the Sun '
 ,' Paint Your Wagon '
 ,' Ensign Pulver '
 ,' Street People '
 ,' Manhunt '
 ,' Operation Nam '
 ,' Fighting Seabees '
 ,' Let It Rock '
 ,' Eraserhead '
 ,' Ladykillers '
 ,' Sweet Smell of Success '
 ,' And Now for Something Completely Different '
 ,' Crackers '
 ,' Green Glove '
 ,' Menace on the Mountain '
 ,' In Old California '
 ,' Thirty Is a Dangerous Age '
 ,' Ffolkes '
 ,' Chisum '
 ,' Hunt for Red October '
 ,' Closely Watched Trains '
 ,' Executive Action '
 ,' Flying Tigers '
 ,' Father\'s Little Dividend '
 ,' An Evening with Robin Williams '
 ,' Eddie Murphy Raw '
 ,' Harlem Nights '
 ,' Santee '
 ,' Good Father '
 ,' Sometimes a Great Notion '
 ,' Catch Twenty-Two '
 ,' Dark Age '
 ,' Deadline '
 ,' Mysterious Mr. Wong '
 ,' A Month in the Country '
 ,' Prom Night III '
 ,' Blood in '
 ,' Wrong Arm of the Law '
 ,' Orphans '
 ,' All the President\'s Men '
 ,' J-Men Forever '
 ,' Wild Bunch '
 ,' Judgement in Berlin '
 ,' Hot Line '
 ,' Rocket Gibraltar '
 ,' Yakuza '
 ,' Jeremiah Johnson '
 ,' Burn! '
 ,' Magnum Force '
 ,' Cyborg '
 ,' Prisoner of Zenda '
 ,' Scream '
 ,' Assault '
 ,' Flying Leathernecks '
 ,' What Comes Around '
 ,' Mon Oncle D\'Amerique '
 ,' Culpepper Cattle Company '
 ,' Survivors '
 ,' Roadhouse Sixty-Six '
 ,' Burning Poles '
 ,' Russkies '
 ,' My Blue Heaven '
 ,' Altered States '
 ,' Cowboys '
 ,' Code Name '
 ,' Patton '
 ,' Midnight Cowboy '
 ,' Falcon & the Snowman '
 ,' Maitresse '
 ,' Disorderlies '
 ,' Raging Bull '
 ,' Garrison Keillor\'s Home '
 ,' Overland Stage Raiders '
 ,' Pals of the Saddle '
 ,' Alone in the Dark '
 ,' Beguiled '
 ,' Escape from Alcatraz '
 ,' Criss Cross '
 ,' Midway '
 ,' Indiana Jones & the Last Crusade '
 ,' Duel '
 ,' Separate but Equal '
 ,' Gosta Berling\'s Saga '
 ,' Platoon '
 ,' Crawling Hand '
 ,' Willy Wonka & the Chocolate Factory '
 ,' Joe Kidd '
 ,' Santa Claus '
 ,' Boys Town '
 ,' Erasure '
 ,' A Question of Honor '
 ,' Check Your Guns '
 ,' West to Glory '
 ,' Throwback '
 ,' Border Feud '
 ,' Fighting Vigilantes '
 ,' Law of the Lash '
 ,' Outlaw Country '
 ,' Return of the Lash '
 ,' Mystery of the Hooded Horsemen '
 ,' Tex Rides with the Boy Scouts '
 ,' Shadows of the West '
 ,' Instant Karma '
 ,' Time Lock '
 ,' Appointment in Honduras '
 ,' Danton '
 ,' Alamo '
 ,' La Chevre '
 ,' Les Comperes '
 ,' Dead Poets Society '
 ,' Othello '
 ,' Battleground '
 ,' Kings of the Road (In the Course of Time) '
 ,' Hiroshima '
 ,' Return of Martin Guerre '
 ,' Somebody up There Likes Me '
 ,' Jack Benny Show '
 ,' Mutiny on the Bounty '
 ,' Death Valley Days '
 ,' Monty Python\'s Flying Circus '
 ,' Monty Python\'s Flying Circus '
 ,' Monty Python\'s Flying Circus '
 ,' Monty Python\'s Flying Circus '
 ,' Valkenvania '
 ,' Secret Policeman\'s Other Ball '
 ,' Taming of the Shrew '
 ,' From Russia with Love '
 ,' Offence '
 ,' Hollywood Mavericks '
 ,' Live at Harrah\'s '
 ,' Persuaders '
 ,' Nineteen Hundred '
 ,' Van '
 ,' My Country Right or Wrong '
 ,' Clint Eastwood Collection '
 ,' Complete Dirty Harry '
 ,' Dead Pool '
 ,' Good '
 ,' Rawhide '
 ,' Tightrope '
 ,' Hearts of Fire '
 ,' How the West Was Won '
 ,' Mummy\'s Hand '
 ,' Great White Death '
 ,' Mosquito Coast '
 ,' Today We Kill....Tomorrow We Die '
 ,' Tormenta Sobre Arizona '
 ,' Back to the Future II '
 ,' Maverick '
 ,' Shakespeare Series '
 ,' Deadly Trackers '
 ,' American Film Institute '
 ,' A Married Man '
 ,' Othello '
 ,' Only Way Home '
 ,' Tales of Tomorrow '
 ,' Inherit the Wind '
 ,' This Is Horror '
 ,' Conversation Piece '
 ,' Crimson Pirate '
 ,' Devil\'s Disciple '
 ,' Hallelujah Trail '
 ,' Train '
 ,' Jay Leno: The American Dream '
 ,' Primal Rage '
 ,' Industrial Symphony '
 ,' Howie Mandel\'s North American Watusi Tour '
 ,' Branford Marsalis '
 ,' L. A. Story '
 ,' Steve Martin Live! '
 ,' Steve Martin '
 ,' Runaway Barge '
 ,' Romulus & the Sabines '
 ,' Saint '
 ,' Strange Brew '
 ,' Another Forty-Eight Hours '
 ,' Best of Eddie Murphy '
 ,' What about Bob? '
 ,' Mummy\'s Revenge '
 ,' Harper '
 ,' Left Handed Gun '
 ,' Once upon a Wheel '
 ,' Prize '
 ,' Secret War of Harry Frigg '
 ,' Two Jakes '
 ,' Exile in Concert '
 ,' Joe Piscopo New Jersey Special '
 ,' Joe Piscopo Video '
 ,' Death Valley Days '
 ,' Salsa: The Motion Picture '
 ,' Hollywood\'s Greatest War Movies '
 ,' Out for Justice '
 ,' Case of the Mukkinese Battle Horn '
 ,' Goon Show Movie '
 ,' Great McGonagall '
 ,' I\'m All Right Jack '
 ,' Magic Christian '
 ,' Never Let Go '
 ,' Pink Panther '
 ,' Two-Way Stretch '
 ,' Face at the Window '
 ,' Tom Thumb '
 ,' Beartooth '
 ,' James Taylor in Concert '
 ,' Gangbusters '
 ,' El Rublo de las Dos Caras '
 ,' Law & Jake Wade '
 ,' Chuka '
 ,' Cry of the Innocent '
 ,' Edison the Man '
 ,' Keeper of the Flame '
 ,' Spencer Tracy Legacy '
 ,' Cheyenne '
 ,' Dawn Rider '
 ,' Duke '
 ,' Frontier Horizon '
 ,' Hell Town '
 ,' Hurricane Express '
 ,' Hurricane Express '
 ,' In Harm\'s Way '
 ,' John Wayne Collection '
 ,' John Wayne Collector\'s Limited Edition '
 ,' John Wayne Four Pack '
 ,' John Wayne Matinee Double Feature '
 ,' John Wayne Matinee Double Feature '
 ,' John Wayne Matinee Double Feature '
 ,' John Wayne Six Pack '
 ,' John Wayne Western Greats '
 ,' King of the Pecos '
 ,' Lawless Frontier '
 ,' Lawless Frontier '
 ,' Lawless Nineties '
 ,' Lucky Texan '
 ,' McQ '
 ,' Neath Arizona Skies '
 ,' Neath the Arizona Skies '
 ,' Randy Rides Alone '
 ,' Range Feud '
 ,' Red River '
 ,' Riders of Destiny '
 ,' Sagebrush Trail '
 ,' Shadow of the Eagle '
 ,' Blood & Guns '
 ,' Hot Money '
 ,' Comedy Tonight '
 ,' Robin Williams ']

names = {' Rose Swanson '
 ,' Forrest Logan '
 ,' Myrtle Hanson '
 ,' Lucy Hoffman '
 ,' Alma Parks '
 ,' Carmen Weber '
 ,' Nathaniel Doyle '
 ,' James Jensen '
 ,' Misty Graves '
 ,' Bonnie Griffith '
 ,' Shane Douglas '
 ,' Boyd Flores '
 ,' Sarah Snyder '
 ,' Brent Tate '
 ,' Brandy Powell '
 ,' Cassandra Cannon '
 ,' Juana Murray '
 ,' Brendan Lowe '
 ,' Woodrow Dean '
 ,' Winifred Elliott '
 ,' Megan Hunter '
 ,' Levi Schneider '
 ,' Whitney Jacobs '
 ,' Kyle Romero '
 ,' Kelly Bailey '
 ,' Mae Mcgee '
 ,' Otis Sanders '
 ,' Tommy Carter '
 ,' Jay Joseph '
 ,' Ricky Mcdaniel '
 ,' Lynn Newton '
 ,' Tim Robbins '
 ,' Terry Cruz '
 ,' Krystal Hammond '
 ,' Gerard Floyd '
 ,' Johnnie Kelley '
 ,' Gilberto Sandoval '
 ,' Tom Scott '
 ,' Caleb Willis '
 ,' Kimberly Alexander '
 ,' Rachel Figueroa '
 ,' Kristy Byrd '
 ,' Kellie Mckenzie '
 ,' Eva Caldwell '
 ,' Archie Medina '
 ,' Ebony Riley '
 ,' Robin Oliver '
 ,' Margie Woods '
 ,' Willie Gardner '
 ,' Gustavo Bell '
 ,' Jerald Wilson '
 ,' Kari Gray '
 ,' Erin Gibbs '
 ,' Timmy Ballard '
 ,' Courtney Schwartz '
 ,' Tricia Stewart '
 ,' Scott Parker '
 ,' Joyce Todd '
 ,' Kay Mccarthy '
 ,' Peggy Chambers '
 ,' Marion Massey '
 ,' Rex Neal '
 ,' Vicki Kennedy '
 ,' Terrence Morris '
 ,' Everett Moss '
 ,' Geraldine Armstrong '
 ,' Damon Frank '
 ,' Javier Martinez '
 ,' Renee Reeves '
 ,' Angelina Pierce '
 ,' Randal Butler '
 ,' Paula Dunn '
 ,' Heidi Goodman '
 ,' Martin Cooper '
 ,' Fernando Silva '
 ,' Leon Burton '
 ,' Ralph Wilkerson '
 ,' Wilson Young '
 ,' Stacy Johnston '
 ,' Traci Turner '
 ,' John Mason '
 ,' Clarence Gross '
 ,' Alyssa Barnes '
 ,' Shelly Phillips '
 ,' Henrietta Hopkins '
 ,' Raul Adkins '
 ,' Joanne Bradley '
 ,' Leona Carr '
 ,' Dave Roberson '
 ,' Francisco Ramos '
 ,' Edmund Kelly '
 ,' Emmett Curtis '
 ,' Douglas Taylor '
 ,' Emanuel Potter '
 ,' Marty Jenkins '
 ,' Gerardo Dawson '
 ,' Elijah Roy '
 ,' Johanna Greer '
 ,' Violet Hubbard '
 ,' Tanya Barton '}

"""
names = {' Rose Swanson '
 ,' Forrest Logan '
 ,' Myrtle Hanson '
 ,' Lucy Hoffman '
}
"""
critics = {}
temp = {}

for name in names:
    i = random.randrange(3,10)
    while(i>0):
        temp[movies[random.randrange(0,1659)]] = random.uniform(0.1,5.0)
        i = i - 1
    critics[name] = temp    
    temp = {}
print critics
    
        
