movies = ['Toy Story',
'Jumanji', 
'Grumpier Old Men', 
'Waiting to Exhale', 
'Father of the Bride Part II', 
'Heat', 
'Sabrina', 
'Tom and Huck', 
'Sudden Death', 
'GoldenEye', 
'American President', 
'Dracula', 
'Balto', 
'Nixon', 
'Cutthroat Island', 
'Casino', 
'Sense and Sensibility', 
'Four Rooms', 
'Ace Ventura', 
'Money Train', 
'Get Shorty', 
'Copycat', 
'Assassins', 
'Powder', 
'Leaving Las Vegas', 
'Othello', 
'Now and Then', 
'Persuasion', 
'City of Lost Children', 
'Shanghai Triad', 
'Dangerous Minds', 
'Twelve Monkeys', 
'Wings of Courage', 
'Babe', 
'Carrington', 
'Dead Man Walking', 
'Across the Sea of Time', 
'It Takes Two', 
'Clueless', 
'Cry Beloved Country', 
'Richard III', 
'Dead Presidents', 
'Restoration', 
'Mortal Kombat', 
'To Die For', 
'How to Make an American Quilt', 
'Seven', 
'Pocahontas', 
'When Night Is Falling', 
'Usual Suspects', 
'Guardian Angel', 
'Mighty Aphrodite', 
'Lamerica', 
'Big Green', 
'Georgia', 
'Kids of the Round Table', 
'Home for the Holidays', 
'Postino Il', 
'Confessional', 
'Indian in the Cupboard', 
'Eye for an Eye', 
'Mr. Holland\'s Opus', 
'Don\'t Be a Menace to South Central While Drinking Your Juice in the Hood', 
'Two if by Sea', 
'Bio-Dome', 
'Lawnmower Man 2', 
'Two Bits', 
'French Twist', 
'Friday', 
'From Dusk Till Dawn', 
'Fair Game', 
'Kicking and Screaming', 
'Bed of Roses', 
'Big Bully', 
'Screamers', 
'Nico Icon', 
'Crossing Guard', 
'Juror', 
'White Balloon', 
'Things to Do in Denver when You\'re Dead', 
'Antonia\'s Line', 
'Once Upon a Time... When We Were Colored', 
'Last Summer in the Hamptons', 
'Angels and Insects', 
'White Squall', 
'Dunston Checks In', 
'Black Sheep', 
'Nick of Time', 
'Journey of August King', 
'Mary Reilly', 
'Vampire in Brooklyn', 
'Beautiful Girls', 
'Broken Arrow', 
'In the Bleak Midwinter', 
'Hate', 
'Shopping', 
'Heidi Fleiss', 
'City Hall', 
'Bottle Rocket', 
'Mr. Wrong', 
'Unforgettable', 
'Happy Gilmore', 
'Bridges of Madison County', 
'Nobody Loves Me', 
'Muppet Treasure Island', 
'Catwalk', 
'Headless Body in Topless Bar', 
'Braveheart', 
'Taxi Driver', 
'Rumble in the Bronx', 
'Before and After', 
'Margaret\'s Museum', 
'Happiness Is in the Field', 
'Anne Frank Remembered', 
'Young Poisoner\'s Handbook', 
'If Lucy Fell', 
'Steal Big Steal Little', 
'Race the Sun', 
'Boys of St. Vincent', 
'Boomerang', 
'Chungking Express', 
'Star Maker', 
'Flirting With Disaster', 
'NeverEnding Story III', 
'Silence of the Palace', 
'Jupiter\'s Wife', 
'Pie in the Sky', 
'Angela', 
'Frankie Starlight', 
'Jade', 
'Nueba Yol', 
'Sonic Outlaws', 
'Down Periscope', 
'From the Journals of Jean Seberg', 
'Man of the Year', 
'Neon Bible', 
'Target', 
'Up Close and Personal', 
'Birdcage', 
'Shadows', 
'Gospa', 
'Brothers McMullen', 
'Bad Boys', 
'Amazing Panda Adventure', 
'Basketball Diaries', 
'Awfully Big Adventure An', 
'Amateur', 
'Apollo 13', 
'Rob Roy', 
'Addiction', 
'Batman Forever', 
'Belle de jour', 
'Beyond Rangoon', 
'Blue in the Face', 
'Canadian Bacon', 
'Casper', 
'Clockers', 
'Congo', 
'Crimson Tide', 
'Crumb', 
'Desperado', 
'Devil in a Blue Dress', 
'Die Hard', 
'Doom Generation', 
'Feast of July', 
'First Knight', 
'Free Willy 2', 
'Hackers', 
'Jeffrey', 
'Johnny Mnemonic', 
'Judge Dredd', 
'Jury Duty', 
'Kids', 
'Living in Oblivion', 
'Lord of Illusions', 
'Love & Human Remains', 
'Mad Love', 
'Mallrats', 
'Mighty Morphin Power Rangers', 
'Moonlight and Valentino', 
'Mute Witness', 
'Nadja', 
'Net', 
'Nine Months', 
'Party Girl', 
'Prophecy', 
'Reckless', 
'Safe', 
'Scarlet Letter', 
'Show', 
'Showgirls', 
'Smoke', 
'Something to Talk About', 
'Species', 
'Stars Fell on Henrietta', 
'Strange Days', 
'Umbrellas of Cherbourg', 
'Tie That Binds', 
'Three Wishes', 
'Total Eclipse', 
'To Wong Foo Thanks for Everything! Julie Newmar', 
'Under Siege 2', 
'Unstrung Heroes', 
'Unzipped', 
'Walk in the Clouds A', 
'Waterworld', 
'White Man\'s Burden', 
'Wild Bill', 
'Browning Version', 
'Bushwhacked', 
'Burnt By the Sun', 
'Before the Rain', 
'Before Sunrise', 
'Billy Madison', 
'Babysitter', 
'Boys on the Side', 
'Cure', 
'Castle Freak', 
'Circle of Friends', 
'Clerks', 
'Don Juan DeMarco', 
'Disclosure', 
'Dream Man', 
'Drop Zone', 
'Destiny Turns on the Radio', 
'Death and the Maiden', 
'Dolores Claiborne', 
'Dumb & Dumber', 
'Eat Drink Man Woman', 
'Exotica', 
'Exit to Eden', 
'Ed Wood', 
'French Kiss', 
'Forget Paris', 
'Far From Home', 
'Goofy Movie A', 
'Hideaway', 
'Fluke', 
'Farinelli', 
'Gordy', 
'Gumby', 
'Glass Shield', 
'Hoop Dreams', 
'Heavenly Creatures', 
'Houseguest', 
'Immortal Beloved', 
'Heavyweights', 
'Hunted', 
'I.Q.', 
'Interview with the Vampire', 
'Jefferson in Paris', 
'Jerky Boys', 
'Junior', 
'Just Cause', 
'Kid in King Arthur\'s Court A', 
'Kiss of Death', 
'Star Wars', 
'Little Women', 
'Little Princess A', 
'Ladybird Ladybird', 
'Enfer', 
'Like Water for Chocolate', 
'Legends of the Fall', 
'Major Payne', 
'Little Odessa', 
'My Crazy Life', 
'Love Affair', 
'Losing Isaiah', 
'Madness of King George', 
'Mary Shelley\'s Frankenstein', 
'Man of the House', 
'Mixed Nuts', 
'Milk Money', 
'Miracle on 34th Street', 
'Miami Rhapsody', 
'My Family', 
'Murder in the First', 
'Nobody\'s Fool', 
'Nell', 
'New Jersey Drive', 
'New York Cop', 
'Beyond Bedlam', 
'Nemesis 2', 
'Nina Takes a Lover', 
'Natural Born Killers', 
'Only You', 
'Once Were Warriors', 
'Poison Ivy II', 
'Outbreak', 
'Professional', 
'Perez Family', 
'Pyromaniac\'s Love Story', 
'Pulp Fiction', 
'Panther', 
'Pushing Hands', 
'Priest', 
'Quiz Show', 
'Picture Bride', 
'Queen Margot', 
'Quick and the Dead', 
'Roommates', 
'Ready to Wear', 
'Three Colors', 
'Three Colors', 
'Three Colors', 
'Red Firecracker Green Firecracker', 
'Rent-a-Kid', 
'Relative Fear', 
'Stuart Saves His Family', 
'Swan Princess', 
'Secret of Roan Inish', 
'Specialist', 
'Stargate', 
'Santa Clause', 
'Shawshank Redemption', 
'Shallow Grave', 
'Suture', 
'Strawberry and Chocolate', 
'Swimming with Sharks', 
'Sum of Us', 
'National Lampoon\'s Senior Trip', 
'To Live', 
'Tank Girl', 
'Tales From the Crypt Presents', 
'Star Trek', 
'Tales from the Hood', 
'Tom & Viv', 
'Village of the Damned', 
'Tommy Boy', 
'Vanya on 42nd Street', 
'Underneath', 
'Walking Dead', 
'What\'s Eating Gilbert Grape', 
'Virtuosity', 
'While You Were Sleeping', 
'War', 
'Double Happiness', 
'Muriel\'s Wedding', 
'Baby-Sitters Club', 
'Ace Ventura', 
'Adventures of Priscilla Queen of the Desert', 
'Backbeat', 
'Bitter Moon', 
'Bullets Over Broadway', 
'Clear and Present Danger', 
'Client', 
'Corrina Corrina', 
'Crooklyn', 
'Crow', 
'Cobb', 
'Flintstones', 
'Forrest Gump', 
'Four Weddings and a Funeral', 
'Higher Learning', 
'I Like It Like That', 
'I Love Trouble', 
'It Could Happen to You', 
'Jungle Book', 
'Wonderful Horrible Life of Leni Riefenstahl', 
'Lion King', 
'Little Buddha', 
'Wes Craven\'s New Nightmare', 
'Mask', 
'Maverick', 
'Mrs. Parker and the Vicious Circle', 
'Naked Gun 33 1/3', 
'Paper', 
'Reality Bites', 
'Red Rock West', 
'Richie Rich', 
'Safe Passage', 
'River Wild', 
'Speed', 
'Speechless', 
'Timecop', 
'True Lies', 
'When a Man Loves a Woman', 
'Wolf', 
'Wyatt Earp', 
'Bad Company', 
'Man of No Importance A', 
'S.F.W.', 
'Low Down Dirty Shame A', 
'Boys Life', 
'Colonel Chabert Le', 
'Faster Pussycat! Kill! Kill!', 
'Jason\'s Lyric', 
'Secret Adventures of Tom Thumb', 
'Street Fighter', 
'Coldblooded', 
'Desert Winds', 
'Fall Time', 
'Fear', 
'Frank and Ollie', 
'Girl in the Cadillac', 
'Homage', 
'Mirage', 
'Open Season', 
'Two Crimes', 
'Brother Minister', 
'Highlander III', 
'Federal Hill', 
'In the Mouth of Madness', 
'8 Seconds', 
'Above the Rim', 
'Addams Family Values', 
'You So Crazy', 
'Age of Innocence', 
'Airheads', 
'Air Up There', 
'Another Stakeout', 
'Bad Girls', 
'Barcelona', 
'Being Human', 
'Beverly Hillbillies', 
'Beverly Hills Cop III', 
'Black Beauty', 
'Blink', 
'Blown Away', 
'Blue Chips', 
'Blue Sky', 
'Body Snatchers', 
'Boxing Helena', 
'Bronx Tale A', 
'Cabin Boy', 
'Calendar Girl', 
'Carlito\'s Way', 
'City Slickers II', 
'Clean Slate', 
'Cliffhanger', 
'Coneheads', 
'Color of Night', 
'Cops and Robbersons', 
'Cowboy Way', 
'Dangerous Game', 
'Dave', 
'Dazed and Confused', 
'Demolition Man', 
'Endless Summer 2', 
'Even Cowgirls Get the Blues', 
'Fatal Instinct', 
'Farewell My Concubine', 
'Favor', 
'Fearless', 
'Fear of a Black Hat', 
'With Honors', 
'Flesh and Bone', 
'Widows\' Peak', 
'For Love or Money', 
'Firm', 
'Free Willy', 
'Fresh', 
'Fugitive', 
'Geronimo', 
'Getaway', 
'Getting Even with Dad', 
'Go Fish', 
'Good Man in Africa A', 
'Guilty as Sin', 
'Hard Target', 
'Heaven & Earth', 
'Hot Shots! Part Deux', 
'Live Nude Girls', 
'Englishman Who Went Up a Hill But Came Down a Mountain', 
'House of the Spirits', 
'House Party 3', 
'Hudsucker Proxy', 
'I\'ll Do Anything', 
'In the Army Now', 
'In the Line of Fire', 
'In the Name of the Father', 
'Inkwell', 
'What\'s Love Got to Do with It?', 
'Jimmy Hollywood', 
'Judgment Night', 
'Jurassic Park', 
'Kalifornia', 
'Killing Zoe', 
'King of the Hill', 
'Lassie', 
'Last Action Hero', 
'Life with Mikey', 
'Lightning Jack', 
'M. Butterfly', 
'Made in America', 
'Malice', 
'Man Without a Face', 
'Manhattan Murder Mystery', 
'Menace II Society', 
'Executive Decision', 
'In the Realm of the Senses', 
'What Happened Was...', 
'Much Ado About Nothing', 
'Mr. Jones', 
'Mr. Wonderful', 
'Mrs. Doubtfire', 
'Naked', 
'Next Karate Kid', 
'New Age', 
'No Escape', 
'North', 
'Orlando', 
'Perfect World A', 
'Philadelphia', 
'Piano', 
'Poetic Justice', 
'Program', 
'Robert A. Heinlein\'s The Puppet Masters', 
'Radioland Murders', 
'Ref', 
'Remains of the Day', 
'Renaissance Man', 
'Rising Sun', 
'Road to Wellville', 
'Robocop 3', 
'Robin Hood', 
'Romeo Is Bleeding', 
'Romper Stomper', 
'Ruby in Paradise', 
'Rudy', 
'Saint of Fort Washington', 
'Savage Nights', 
'Schindler\'s List', 
'Scout', 
'Searching for Bobby Fischer', 
'Second Best', 
'Secret Garden', 
'Serial Mom', 
'Shadow', 
'Shadowlands', 
'Short Cuts', 
'Simple Twist of Fate A', 
'Sirens', 
'Six Degrees of Separation', 
'Sleepless in Seattle', 
'Sliver', 
'Blade Runner', 
'Son in Law', 
'So I Married an Axe Murderer', 
'Striking Distance', 
'Harlem', 
'Super Mario Bros.', 
'Surviving the Game', 
'Terminal Velocity', 
'Thirty-Two Short Films About Glenn Gould', 
'Threesome', 
'Nightmare Before Christmas', 
'Three Musketeers', 
'Tombstone', 
'Trial by Jury', 
'True Romance', 
'War Room', 
'Mamma Roma', 
'Pagemaster', 
'Paris France', 
'Beans of Egypt Maine', 
'Killer', 
'Welcome to the Dollhouse', 
'Germinal', 
'Chasers', 
'Cronos', 
'Naked in New York', 
'Kika', 
'Bhaji on the Beach', 
'Little Big League', 
'Slingshot', 
'Wedding Gift', 
'Foreign Student', 
'Ciao Professore!', 
'Spanking the Monkey', 
'Little Rascals', 
'Fausto', 
'Andre', 
'Hour of the Pig', 
'Scorta La', 
'Princess Caraboo', 
'Celluloid Closet', 
'Metisse', 
'Dear Diary', 
'I Don\'t Want to Talk About It', 
'Brady Bunch Movie', 
'Home Alone', 
'Ghost', 
'Aladdin', 
'Terminator 2', 
'Dances with Wolves', 
'Tough and Deadly', 
'Batman', 
'Silence of the Lambs', 
'Snow White and the Seven Dwarfs', 
'Beauty and the Beast', 
'Pinocchio', 
'Pretty Woman', 
'Window to Paris', 
'Wild Bunch', 
'Love and a .45', 
'Wooden Man\'s Bride', 
'Great Day in Harlem A', 
'Bye Bye Love', 
'Criminals', 
'One Fine Day', 
'Candyman', 
'Century', 
'Fargo', 
'Homeward Bound II', 
'Heavy Metal', 
'Hellraiser', 
'Pallbearer', 
'Jane Eyre', 
'Loaded', 
'Bread and Chocolate', 
'Aristocats', 
'Flower of My Secret', 
'Two Much', 
'Ed', 
'Scream of Stone', 
'My Favorite Season', 
'Modern Affair A', 
'Condition Red', 
'Asfour Stah', 
'Thin Line Between Love and Hate A', 
'Last Supper', 
'Primal Fear', 
'Rude', 
'Carried Away', 
'All Dogs Go to Heaven 2', 
'Land and Freedom', 
'Denise Calls Up', 
'Theodore Rex', 
'Family Thing A', 
'Frisk', 
'Sgt. Bilko', 
'Jack and Sarah', 
'Girl 6', 
'Diabolique', 
'Little Indian Big City', 
'Roula', 
'Peanuts - Die Bank zahlt alles', 
'Happy Weekend', 
'Nelly & Monsieur Arnaud', 
'Courage Under Fire', 
'Mission', 
'Cold Fever', 
'Moll Flanders', 
'Superweib Das', 
'301 302', 
'Dragonheart', 
'Und keiner weint mir nach', 
'Mutters Courage', 
'Eddie', 
'Yankee Zulu', 
'Billy\'s Holiday', 
'Purple Noon', 
'August', 
'James and the Giant Peach', 
'Fear', 
'Kids in the Hall', 
'Faithful', 
'Underground', 
'All Things Fair', 
'Bloodsport 2', 
'Pather Panchali', 
'Aparajito', 
'World of Apu', 
'Mystery Science Theater 3000', 
'Tarantella', 
'Space Jam', 
'Barbarella', 
'Hostile Intentions', 
'They Bite', 
'Some Folks Call It a Sling Blade', 
'Run of the Country', 
'Alphaville', 
'Clean Slate', 
'Tigrero', 
'Eye of Vichy', 
'Windows', 
'It\'s My Party', 
'Country Life', 
'Operation Dumbo Drop', 
'Promise', 
'Mrs. Winterbourne', 
'Solo', 
'Under the Domin Tree', 
'Substitute', 
'True Crime', 
'Butterfly Kiss', 
'Feeling Minnesota', 
'Delta of Venus', 
'To Cross the Rubicon', 
'Angus', 
'Daens', 
'Faces', 
'Boys', 
'Quest', 
'Cosi', 
'Sunset Park', 
'Mulholland Falls', 
'Truth About Cats & Dogs', 
'Oliver & Company', 
'Celtic Pride', 
'Flipper', 
'Captives', 
'Of Love and Shadows', 
'Dead Man', 
'Horseman on the Roof', 
'Switchblade Sisters', 
'Mouth to Mouth', 
'Visitors', 
'Multiplicity', 
'Wallace & Gromit', 
'Halfmoon', 
'Haunted World of Edward D. Wood Jr.', 
'Two Friends', 
'Craft', 
'Great White Hype', 
'Last Dance', 
'War Stories', 
'Cold Comfort Farm', 
'Institute Benjamenta or This Dream People Call Human Life', 
'Low Life', 
'Heaven\'s Prisoners', 
'Original Gangstas', 
'Rock', 
'Getting Away With Murder', 
'Cemetery Man', 
'Twister', 
'Barb Wire', 
'Garcu Le', 
'Honigmond', 
'Ghost in the Shell', 
'Thinner', 
'Spy Hard', 
'Brothers in Trouble', 
'Close Shave A', 
'Force of Evil', 
'Stupids', 
'Arrival', 
'Man from Down Under', 
'Dr. Strangelove or', 
'Careful', 
'Vermont Is For Lovers', 
'Month by the Lake A', 
'Gold Diggers', 
'Kim', 
'Carmen Miranda', 
'Ashes of Time', 
'Jar', 
'Maya Lin', 
'Stalingrad', 
'Phantom', 
'Striptease', 
'Last of the High Kings', 
'Heavy', 
'Jack', 
'I Shot Andy Warhol', 
'Grass Harp', 
'Someone Else\'s America', 
'Marlene Dietrich', 
'Costa Brava', 
'Vie est belle La', 
'Quartier Mozart', 
'Touki Bouki', 
'Wend Kuuni', 
'Spirits of the Dead', 
'Babyfever', 
'Pharaoh\'s Army', 
'Trainspotting', 
'\'Til There Was You', 
'Independence Day', 
'Stealing Beauty', 
'Fan', 
'Hunchback of Notre Dame', 
'Cable Guy', 
'Kingpin', 
'Eraser', 
'Gate of Heavenly Peace', 
'Nutty Professor', 
'I Worst of All', 
'An Unforgettable Summer', 
'Last Klezmer', 
'Hungarian Fairy Tale A', 
'My Life and Times With Antonin Artaud', 
'Midnight Dancers', 
'Somebody to Love', 
'Very Natural Thing A', 
'Old Lady Who Walked in the Sea', 
'Daylight', 
'Frighteners', 
'Lone Star', 
'Harriet the Spy', 
'Phenomenon', 
'Walking and Talking', 
'She\'s the One', 
'Time to Kill A', 
'American Buffalo', 
'Rendezvous in Paris', 
'Alaska', 
'Fled', 
'Kazaam', 
'Bewegte Mann Der', 
'Magic Hunter', 
'Larger Than Life', 
'Boy Called Hate A', 
'Power 98', 
'Two Deaths', 
'Very Brady Sequel A', 
'Stefano Quantestorie', 
'Death in the Garden', 
'Crude Oasis', 
'Hedd Wyn', 
'Collectionneuse La', 
'Kaspar Hauser', 
'Echte Kerle', 
'Diebinnen', 
'Convent', 
'Adventures of Pinocchio', 
'Joe\'s Apartment', 
'First Wives Club', 
'Stonewall', 
'Ransom', 
'High School High', 
'Phat Beach', 
'Foxfire', 
'Chain Reaction', 
'Matilda', 
'Emma', 
'Crow', 
'House Arrest', 
'Eyes Without a Face', 
'Tales from the Crypt Presents', 
'Lotto Land', 
'Story of Xinghua', 
'Day the Sun Turned Cold', 
'Flirt', 
'Big Squeeze', 
'Spitfire Grill', 
'Escape from L.A.', 
'Cyclo', 
'Basquiat', 
'Tin Cup', 
'Dingo', 
'Ballad of Narayama', 
'Every Other Weekend', 
'Mille bolle blu', 
'Crows and Sparrows', 
'Godfather', 
'Hippie Revolution', 
'Maybe Maybe Not', 
'Supercop', 
'Manny & Lo', 
'Celestial Clockwork', 
'Wife', 
'Small Faces', 
'Bound', 
'Carpool', 
'Death in Brunswick', 
'Kansas City', 
'Gone Fishin\'', 
'Lover\'s Knot', 
'Aiqing wansui', 
'Shadow of Angels', 
'Killer', 
'Nothing to Lose', 
'Police Story 4', 
'Girls Town', 
'Bye-Bye', 
'Relic', 
'Island of Dr. Moreau', 
'First Kid', 
'Trigger Effect', 
'Sweet Nothing', 
'Bogus', 
'Bulletproof', 
'Talk of Angels', 
'Land Before Time III', 
'1-900', 
'Baton Rouge', 
'Halloween', 
'Twelfth Night', 
'Mother Night', 
'Liebelei', 
'Venice/Venice', 
'Wild Reeds', 
'For Whom the Bell Tolls', 
'Philadelphia Story', 
'Singin\' in the Rain', 
'American in Paris An', 
'Funny Face', 
'Breakfast at Tiffany\'s', 
'Vertigo', 
'Rear Window', 
'It Happened One Night', 
'Gaslight', 
'Gay Divorcee', 
'North by Northwest', 
'Apartment', 
'Some Like It Hot', 
'Charade', 
'Casablanca', 
'Maltese Falcon', 
'My Fair Lady', 
'Sabrina', 
'Roman Holiday', 
'Little Princess', 
'Meet Me in St. Louis', 
'Wizard of Oz', 
'Gone with the Wind', 
'My Favorite Year', 
'Sunset Blvd.', 
'Citizen Kane', 
'2001', 
'Golden Earrings', 
'All About Eve', 
'Women', 
'Rebecca', 
'Foreign Correspondent', 
'Notorious', 
'Spellbound', 
'Affair to Remember An', 
'To Catch a Thief', 
'Father of the Bride', 
'Band Wagon', 
'Ninotchka', 
'Love in the Afternoon', 
'Gigi', 
'Reluctant Debutante', 
'Adventures of Robin Hood', 
'Mark of Zorro', 
'Laura', 
'Ghost and Mrs. Muir', 
'Lost Horizon', 
'Top Hat', 
'To Be or Not to Be', 
'My Man Godfrey', 
'Giant', 
'East of Eden', 
'Thin Man', 
'His Girl Friday', 
'Around the World in 80 Days', 
'It\'s a Wonderful Life', 
'Mr. Smith Goes to Washington', 
'Bringing Up Baby', 
'Penny Serenade', 
'Scarlet Letter', 
'Lady of Burlesque', 
'Of Human Bondage', 
'Angel on My Shoulder', 
'Little Lord Fauntleroy', 
'They Made Me a Criminal', 
'Inspector General', 
'Angel and the Badman', 
'39 Steps', 
'Walk in the Sun A', 
'Outlaw', 
'Night of the Living Dead', 
'African Queen', 
'Beat the Devil', 
'Cat on a Hot Tin Roof', 
'Last Time I Saw Paris', 
'Meet John Doe', 
'Algiers', 
'Something to Sing About', 
'Farewell to Arms A', 
'Moonlight Murder', 
'Blue Angel', 
'Nothing Personal', 
'In the Line of Duty 2', 
'Dangerous Ground', 
'Picnic', 
'Madagascar Skin', 
'Pompatus of Love', 
'Small Wonders', 
'Fly Away Home', 
'Bliss', 
'Grace of My Heart', 
'Schlafes Bruder', 
'Maximum Risk', 
'Michael Collins', 
'Rich Man\'s Wife', 
'Infinity', 
'Big Night', 
'Last Man Standing', 
'Caught', 
'Set It Off', 
'2 Days in the Valley', 
'Curdled', 
'Associate', 
'Ed\'s Next Move', 
'Extreme Measures', 
'Glimmer Man', 
'D3', 
'Chamber', 
'Apple Dumpling Gang', 
'Davy Crockett King of the Wild Frontier', 
'Escape to Witch Mountain', 
'Love Bug', 
'Herbie Rides Again', 
'Old Yeller']
