critics={'Lisa Rose': {'Lady in the Water': 2.5, 'Snakes on a Plane': 3.5,
'Just My Luck': 3.0, 'Superman Returns': 3.5, 'You, Me and Dupree': 2.5,
'The Night Listener': 3.0},
'Gene Seymour': {'Lady in the Water': 3.0, 'Snakes on a Plane': 3.5,
'Just My Luck': 1.5, 'Superman Returns': 5.0, 'The Night Listener': 3.0,
'You, Me and Dupree': 3.5},
'Michael Phillips': {'Lady in the Water': 2.5, 'Snakes on a Plane': 3.0,
'Superman Returns': 3.5, 'The Night Listener': 4.0},
'Claudia Puig': {'Snakes on a Plane': 3.5, 'Just My Luck': 3.0,
'The Night Listener': 4.5, 'Superman Returns': 4.0,
'You, Me and Dupree': 2.5},
'Mick LaSalle': {'Lady in the Water': 3.0, 'Snakes on a Plane': 4.0,
'Just My Luck': 2.0, 'Superman Returns': 3.0, 'The Night Listener': 3.0,
'You, Me and Dupree': 2.0},
'Jack Matthews': {'Lady in the Water': 3.0, 'Snakes on a Plane': 4.0,
'The Night Listener': 3.0, 'Superman Returns': 5.0, 'You, Me and Dupree': 3.5},
'Toby': {'Snakes on a Plane':4.5,'You, Me and Dupree':1.0,'Superman Returns':4.0},
' Martin Cooper ': {' Legend of the Lost ': 4.9, ' Separate but Equal ': 2.5, ' Judgement in Berlin ': 2.8, " Mo' Better Blues ": 2.0, ' Meeting Venus ': 4.7, ' Midnight Cowboy ': 2.8}, ' Juana Murray ': {' Thunderbolt & Lightfoot ': 1.9, ' Creepshow ': 2.5, ' Unbearable Lightness of Being ': 1.2, ' Come Back ': 1.4, ' Sun Shines Bright ': 2.2, ' Madonna ': 2.4, ' Siesta ': 2.2, ' Buffet Froid ': 1.2}, ' Misty Graves ': {' Jack Benny Show ': 0.6, ' A New Leaf ': 1.3, ' Fisher King ': 3.3, ' Clint Eastwood Collection ': 1.1, ' Little Women ': 4.0, ' Defense of the Realm ': 0.8}, ' Francisco Ramos ': {' Broadway Danny Rose ': 2.7, ' Crimes of Passion ': 2.1, ' Fair Game ': 4.7}, ' Jerald Wilson ': {' A Nous la Liberte ': 0.7, ' Black Rain ': 4.2, ' John Wayne Collection ': 4.4, ' Return of the Jedi ': 1.5, ' Crocodile Dundee ': 0.4}, ' Tom Scott ': {' Tin Men ': 2.5, ' Kings of the Road (In the Course of Time) ': 2.5, " Losin' It ": 0.3, ' Shooting Elizabeth ': 4.5, ' Bloody Mama ': 4.7, ' Falling in Love ': 2.3, ' Kissing Place ': 4.8}, ' Ebony Riley ': {' Dead Zone ': 0.2, ' Duet for One ': 1.6, ' Star Trek V: The Final Frontier ': 1.7, ' Life with Father ': 4.8, ' Dirty Harry ': 2.7}, ' Randal Butler ': {' Hush ': 1.1, ' Sweet Smell of Success ': 1.6, ' Boy Who Could Fly ': 4.7, ' Posse ': 4.3}, ' Violet Hubbard ': {' Paris ': 4.8, ' Whose Life Is It ': 3.8, ' Apocalypse Now ': 4.4, ' Dakota ': 3.4, ' Rookie ': 2.4, ' Midnight Cowboy ': 2.9}, ' Joanne Bradley ': {' Conversation Piece ': 3.7, " Devil's Eye ": 4.0, ' Fatal Attraction ': 2.7, ' Sophia Loren ': 3.0, ' Burbs ': 1.4, ' Predator 2 ': 0.4, ' Rainbow ': 4.6}, ' Shelly Phillips ': {' Knights & Emeralds ': 1.5, ' A Man for All Seasons ': 1.6, ' Flame & the Arrow ': 4.6, ' Burbs ': 0.9, ' Overboard ': 1.5, ' Accused ': 0.7}, ' Brent Tate ': {' Rainbow ': 1.0, ' Frisco Kid ': 1.1, ' Wild Orchids ': 3.8, ' Big Top Pee-wee ': 3.9, ' Alien Three ': 2.2, " Howie Mandel's North American Watusi Tour ": 3.7, ' Pals of the Saddle ': 3.4}, ' Mae Mcgee ': {' Best of the Big Laff Off ': 1.2, ' Man Who Loved Women ': 1.9, ' Secret of My Success ': 3.8, " Father's Little Dividend ": 0.7, " His Majesty O'Keefe ": 2.2}, ' Carmen Weber ': {' Cat Chaser ': 1.6, ' Bride Is Much Too Beautiful ': 0.4, ' She-Devil ': 1.9, ' Charly ': 2.1, ' Vanishing Westerner ': 5.0, ' Rawhide ': 2.9}, ' Clarence Gross ': {' Lair of the White Worm ': 4.9, ' Juice ': 4.8, ' Mosquito Coast ': 4.4, ' Erasure ': 2.7, " In Harm's Way ": 4.3, ' Man Who Shot Liberty Valance ': 3.1, " Howie Mandel's North American Watusi Tour ": 4.1, ' White Hunter ': 4.9}, ' Ralph Wilkerson ': {' Persona ': 4.9, ' Joe Piscopo New Jersey Special ': 3.8, ' I Died a Thousand Times ': 1.7, ' Deep Cover ': 4.3, ' Black & White in Color ': 3.4, ' Creature from Black Lake ': 1.3, ' John Wayne Collection ': 4.4}, ' Tommy Carter ': {' Persuaders ': 2.2, ' Prize ': 2.3, ' Purple Rose of Cairo ': 0.2, ' Local Hero ': 2.7, ' Dark Age ': 2.0, ' Two Women ': 3.0, ' Pope of Greenwich Village ': 1.1, ' Looker ': 0.3, " What's New Pussycat ": 2.3}, ' Emanuel Potter ': {' Glory Stompers ': 1.0, ' Raven ': 4.5, ' Train ': 2.0, ' Shalako ': 4.3, ' Foreign Correspondent ': 3.4}, ' Henrietta Hopkins ': {' Looking for Mr. Goodbar ': 1.7, ' Appaloosa ': 3.1, ' Midnight Cowboy ': 4.0, ' Shadow of a Doubt ': 1.8, ' Until the End of the World ': 3.4, ' Elena & Her Men ': 2.1, ' Saint ': 1.3}, ' John Mason ': {' Le Repos Du Guerrier ': 4.6, ' Runaway Barge ': 4.7, ' Adam at 6 A.M. ': 1.5, ' Running on Empty ': 2.7, ' Permanent Record ': 0.8, ' Man Who Loved Cat Dancing ': 2.7, ' Barbarian & the Geisha ': 0.2, ' Yellowbeard ': 4.9}, ' Scott Parker ': {' Rashomon ': 1.1, ' Defending Your Life ': 4.4, ' Rio Grande ': 0.7, ' Police Academy 6: City under Siege ': 3.5}, ' Alyssa Barnes ': {' Only Way Home ': 3.5, ' Stark ': 1.1, ' Purple Rose of Cairo ': 1.1, ' A Matter of Time ': 0.2, ' Bloopers from Star Trek ': 3.8, ' A New Life ': 1.8}, ' Bonnie Griffith ': {' Apprenticeship of Duddy Kravitz ': 0.4, " There's a Girl in My Soup ": 2.8, ' Out for Justice ': 2.1, ' Tentacles ': 0.2, ' Going Ape ': 1.7, ' Gremlins 2: The New Batch ': 0.1, ' Bad Sleep Well ': 0.4, ' Border Feud ': 0.5}, ' Peggy Chambers ': {' Sophia Loren ': 4.5, ' Bobby Deerfield ': 3.1, " There's a Girl in My Soup ": 1.8}, ' Woodrow Dean ': {' Gor ': 4.2, ' Big Jake ': 4.0, ' Mutiny on the Bounty ': 2.4, ' Official Story ': 4.7, ' Bronco Billy ': 3.9, ' Dr Alien ': 1.3, ' State of Things ': 3.8, ' Rooster Cogburn ': 2.9}, ' Ricky Mcdaniel ': {' King Kong Lives! ': 1.0, ' Beverly Hills Cop II ': 3.2, ' Pet Sematary ': 0.6, ' Magic Town ': 1.2, ' A Nous la Liberte ': 0.8, ' Prisoner of Honor. ': 0.5, ' Deceivers ': 0.4, ' Raw Nerve ': 3.0}, ' Marty Jenkins ': {' Hear My Song ': 1.2, ' Dangerous Pursuit ': 2.6, ' White Sands ': 2.7, ' Power ': 3.6, ' Island of Dr. Moreau ': 0.8, ' Rain People ': 4.6, ' A Chorus of Disapproval ': 1.3, ' Un Hombre y una Mujer ': 4.9, ' Fellow Traveller ': 3.2}, ' Nathaniel Doyle ': {' Hells Angels on Wheels ': 3.5, ' Long John Silver ': 3.2, ' Terror ': 2.2, ' Metropolis ': 3.6, ' Flesh & the Devil ': 3.8, ' Fear ': 0.4}, ' Forrest Logan ': {" America's Music ": 1.3, " Nobody's Fool ": 0.4, ' Culpepper Cattle Company ': 2.7, ' Sea Chase ': 2.4, ' Heartbreak Ridge ': 1.4}, ' Geraldine Armstrong ': {' Pope of Greenwich Village ': 3.3, ' Hour of the Wolf ': 2.2, ' Spartacus ': 2.8, ' Foreign Correspondent ': 0.9, ' Posse ': 2.7}, ' Heidi Goodman ': {' Crash & Burn ': 1.7, ' Man Who Haunted Himself ': 4.8, ' Ginger & Fred ': 4.7, ' Mistress ': 3.3}, ' Renee Reeves ': {' Law & Jake Wade ': 0.1, ' Family Business ': 0.2, ' Range Feud ': 1.3}, ' Gerard Floyd ': {' Crash & Burn ': 0.4, ' Hear My Song ': 2.2, ' Nights in White Satin ': 2.5, ' Moonstruck ': 1.4, ' Ten ': 2.0, ' Next of Kin ': 4.8, " Adventures of Sherlock Holmes' Smarter ": 4.7, ' Three Godfathers ': 2.7, " Father's Little Dividend ": 4.7}, ' Raul Adkins ': {' Raintree County ': 1.1, ' Maurice ': 0.1, ' Queen Christina ': 2.9, ' John Wayne Matinee Double Feature ': 1.8, ' Norma Rae ': 5.0, ' Black & White in Color ': 3.3}, ' Sarah Snyder ': {' Street People ': 1.4, ' Frisco Kid ': 3.5, ' Single Standard ': 1.2, ' Range Feud ': 0.2, ' A Fish Called Wanda ': 3.5, ' Savage Intruder ': 2.1}, ' Kristy Byrd ': {' A Clockwork Orange ': 0.4, ' Big Jake ': 2.2, ' Matador ': 2.7}, ' Brendan Lowe ': {' Pioneer Marshal ': 0.6, ' Killers of Kilimanjaro ': 4.8, ' Shakespeare Series ': 2.4, ' To Catch a Thief ': 3.3, ' A Smoky Mountain Christmas ': 0.1}, ' Javier Martinez ': {' Gator Bait II ': 0.9, ' Wrong Arm of the Law ': 3.9, ' Robin Williams ': 2.7, ' Prettykill ': 1.6, " Fozzie's Muppet Scrapbook ": 2.2}, ' Whitney Jacobs ': {' Burbs ': 1.0, ' All the Right Moves ': 3.4, ' Bloodsport ': 4.2}, ' James Jensen ': {' Lair of the White Worm ': 4.8, " On Her Majesty's Secret Service ": 2.2, ' I Died a Thousand Times ': 3.7, ' Act of Piracy ': 2.6, ' In Old California ': 1.3, ' Hammersmith Is Out ': 0.8}, ' Alma Parks ': {' Sea of Grass ': 0.2, ' Terms of Endearment ': 3.0, ' Matt Talbot ': 3.3, ' Indigo Autumn & Lilac Dream ': 2.2, ' Running Man ': 3.1, ' Woman Next Door ': 2.1}, ' Kay Mccarthy ': {' A Woman Called Golda ': 4.0, ' Camille ': 1.5, " Mummy's Hand ": 0.7, ' James Taylor in Concert ': 2.5}, ' Joyce Todd ': {' A Smoky Mountain Christmas ': 1.5, ' My Country Right or Wrong ': 0.6, " Vampire's Kiss ": 3.7, ' Vertigo ': 1.2}, ' Everett Moss ': {' Battleground ': 4.2, ' Wings of Eagles ': 4.2, ' A Man & a Woman: Twenty Years Later ': 3.3}, ' Myrtle Hanson ': {' Ginger & Fred ': 1.3, ' Miles from Home ': 4.3, ' Big Jake ': 2.5, ' Time Bandits ': 4.8, ' Terror ': 3.5, ' Days of Thunder ': 1.4, ' Violent Men ': 0.9, ' Unfaithfully Yours ': 1.2}, ' Courtney Schwartz ': {' Born to Ride ': 2.4, ' White Lightning ': 0.8, ' Dark Command ': 3.7, ' Ranger of the Cherokee Strip ': 1.2, ' Christopher Columbus ': 3.4, " I'm All Right Jack ": 4.1}, ' Otis Sanders ': {' Rich & Strange ': 3.9, ' Arrowsmith ': 0.9, ' Shirley Valentine ': 4.9, ' Only Way Home ': 3.9, ' Loves of Carmen ': 0.2}, ' Willie Gardner ': {' Like Father Like Son ': 2.7, ' Crisis ': 1.1, ' Desperately Seeking Susan ': 4.5, ' Risky Business ': 4.8, ' Yakuza ': 3.0}, ' Kellie Mckenzie ': {' For Your Eyes Only ': 3.9, ' Last Hurrah ': 3.0, ' Start the Revolution Without Me ': 4.1, ' One Woman or Two ': 2.1, ' Libeled Lady ': 2.0, ' Amadeus ': 3.1}, ' Dave Roberson ': {' Lady for a Night ': 1.0, ' Powderkeg ': 4.1, ' Guilty by Suspicion ': 1.1, ' Cannibal Women in the Avocado Jungle of Death ': 1.2}, ' Paula Dunn ': {' Paris ': 1.2, ' Persuaders ': 1.8, ' Train ': 4.3, ' Wild Times ': 2.2, ' Sunshine Boys ': 3.8, ' Stir Crazy ': 1.9, ' Frontier Horizon ': 3.8}, ' Kimberly Alexander ': {' Frontier Horizon ': 0.6, ' Wisdom ': 0.3, ' Another Woman ': 3.2, ' Silent Movie ': 0.6}, ' Shane Douglas ': {' Gator Bait II ': 2.5, ' Conversation Piece ': 3.4, ' Out of Africa ': 3.7, ' Miles from Home ': 1.1, ' White Lightning ': 2.6, ' Heartbreak Ridge ': 4.6, ' Executive Action ': 4.3, ' Mr Love. ': 0.3}, ' Damon Frank ': {' Holocaust ': 1.4, ' John Cleese on How to Irritate People ': 4.5, ' A Stolen Life ': 1.0, ' Scum ': 2.2, ' Crawling Hand ': 3.9, ' Seizure ': 3.5, ' Hard To Kill ': 4.5, ' Kiss of the Spider Woman ': 2.4, ' Cocaine Cowboys ': 0.7}, ' Lucy Hoffman ': {' Wolf at the Door ': 3.3, ' Bold Frontiersman ': 0.2, ' Rita ': 0.2, ' American Anthem ': 4.1, ' Patriot Games ': 4.8, ' Cat Ballou ': 0.1, ' Firehouse ': 1.0, ' Rain People ': 0.1, ' Gaslight ': 5.0}, ' Rose Swanson ': {' Wait Until Spring Bandini ': 0.5, ' Roller Blade ': 4.1, ' Joyless Street ': 0.2, ' Class Act ': 2.6, ' Madonna ': 0.4, ' Bloopers from Star Trek ': 0.9, ' Strictly Business ': 4.3, ' Foul Play ': 3.1}, ' Cassandra Cannon ': {' After the Rehearsal ': 1.4, ' Stromboli ': 3.5, ' Monster in the Closet ': 3.2}, ' Margie Woods ': {' Cool Hand Luke ': 3.6, ' Hud ': 2.1, ' Sabotage ': 0.2, ' Bloodsucking Pharaohs in Pittsburgh ': 4.4}, ' Gerardo Dawson ': {' Firefox ': 1.8, ' Whose Life Is It ': 1.4, " Losin' It ": 4.0, ' To Catch a Thief ': 0.9, ' Men ': 5.0, ' Flying Tigers ': 2.4}, ' Vicki Kennedy ': {' Russians Are Coming ': 2.4, ' Paramount Comedy Theater: Well-Developed ': 3.6, ' Why Me? ': 1.7, ' Life & Times of Judge Roy Bean ': 1.4, ' Cool World ': 4.0, ' Plenty ': 1.4}, ' Wilson Young ': {' Fury ': 2.8, ' See You in the Morning ': 1.2, ' Rome Adventure ': 4.6, ' Ensign Pulver ': 2.6}, ' Marion Massey ': {' Appaloosa ': 1.8, ' Do the Right Thing ': 4.7, ' Roma ': 3.8, ' Ransom ': 4.7, ' Hope & Glory ': 1.0, ' Ballad of Narayama ': 2.9}, ' Boyd Flores ': {' Only Way Home ': 1.6, ' Mother Lode ': 2.1, ' King Kong Lives! ': 3.3, ' Adam at 6 A.M. ': 3.8, ' Phantom of the Ritz ': 0.8, ' Rebel Without a Cause ': 0.9, ' Dead Ringers ': 2.3, ' Vampire Raiders ': 2.4}, ' Emmett Curtis ': {' Burn! ': 4.3, ' Secrets of Women ': 4.7, ' Dangerous Liaisons ': 2.0, ' Cancel My Reservation ': 2.7, ' Marbella ': 1.5, ' Deadly Trackers ': 3.7, ' Shout at the Devil ': 2.7}, ' Kari Gray ': {' Critical Condition ': 4.7, ' Spies ': 2.4, ' Santa Claus ': 2.3, ' A Stolen Life ': 0.5}, ' Gustavo Bell ': {' For a Few Dollars More ': 5.0, ' Bliss of Mrs. Blossom ': 5.0, ' Knights & Emeralds ': 0.7, ' Stand & Deliver ': 1.7, ' What Price Glory? ': 0.3, " In Harm's Way ": 3.4, ' North by Northwest ': 1.2, ' Outlaw Country ': 0.9}, ' Robin Oliver ': {' Looker ': 4.3, ' Il Bidone ': 3.8, ' Day of the Locust ': 4.3}, ' Edmund Kelly ': {' Wait Until Spring Bandini ': 2.3, ' Autumn Sonata ': 0.4, ' Roadhouse Sixty-Six ': 3.0, ' Curly Sue ': 1.6, ' Cocoon ': 2.1, ' Still of the Night ': 0.7, ' Circuitry Man ': 3.2, ' From the Hip ': 1.4, ' Dragonfight ': 3.7}, ' Kyle Romero ': {' A Special Day ': 1.4, ' One Woman or Two ': 0.2, ' Year My Voice Broke ': 0.8, ' Criss Cross ': 0.5, ' Inside Man ': 1.4, ' Trash ': 3.5}, ' Krystal Hammond ': {' Kramer vs. Kramer ': 2.4, ' Dear America ': 2.3, ' Ninja Masters of Death ': 1.3, " On Her Majesty's Secret Service ": 2.1, ' Children of a Lesser God ': 4.2, ' Man with the Golden Gun ': 1.7, ' Rich & Strange ': 2.2, ' Planes ': 1.4, ' Red Sonja ': 4.1}, ' Fernando Silva ': {" Alice Doesn't Live Here Anymore ": 1.7, ' Zardoz ': 3.3, ' Torn Apart ': 2.1, ' Les Comperes ': 2.6, ' And Now for Something Completely Different ': 1.8, ' Coming to America ': 3.0}, ' Gilberto Sandoval ': {' And God Created Woman ': 4.6, ' Live & Let Die ': 1.2, ' Robin Hood: Prince of Thieves ': 1.9, ' Subway ': 4.2, ' Bloodbath ': 2.3, ' White Hunter ': 3.0}, ' Tim Robbins ': {' Too Beautiful for You ': 4.8, ' A Patch of Blue ': 4.3, ' Fawlty Towers ': 4.0, ' Forgotten ': 1.4, ' Stacey! ': 0.4, ' Father Murphy ': 1.1, ' Saint ': 4.5}, ' Elijah Roy ': {' King Kong Lives! ': 0.3, ' Sheltering Sky ': 3.0, ' Fat Man & Little Boy ': 2.9}, ' Johnnie Kelley ': {' Big Blue ': 0.3, ' Cimarron ': 4.1, ' John Cleese on How to Irritate People ': 1.7, ' Brannigan ': 3.5, ' Through a Glass Darkly ': 1.4, ' American Film Institute ': 4.3}, ' Leona Carr ': {' Great Train Robbery ': 2.6, ' Winter Light ': 1.9, ' Manhunt ': 3.8, ' Formula ': 2.7, 'Tie Me Up! Tie Me Down!': 3.4, ' Men ': 4.0}, ' Traci Turner ': {' Purple Rose of Cairo ': 3.3, ' Riders of Destiny ': 4.4, ' What Price Glory? ': 0.8, ' Desk Set ': 0.3, ' From the Life of the Marionettes ': 3.0, ' Sabotage ': 1.1, ' A Married Man ': 4.9}, ' Caleb Willis ': {" We're No Angels ": 2.3, ' Coma ': 2.6, ' Maitresse ': 3.5, ' Passion of Anna ': 0.5, ' Doughnuts & Society ': 0.7, ' Full Metal Jacket ': 2.1}, ' Eva Caldwell ': {' Hear My Song ': 2.8, ' Seven Minutes in Heaven ': 4.0, ' Fisher King ': 1.3, ' Glory Stompers ': 2.5, ' Comedy Tonight ': 4.0, ' Juice ': 1.4}, ' Archie Medina ': {' Hideaways ': 0.9, ' Like Father Like Son ': 0.5, ' Tex Rides with the Boy Scouts ': 3.3, ' Night Gallery ': 2.8, ' Conversation ': 0.3, ' Valley Girl ': 4.7}, ' Tanya Barton ': {' Silence of the Lambs ': 1.4, " Employee's Entrance ": 4.7, ' Dark Command ': 4.0, ' Hot Line ': 4.4}, ' Megan Hunter ': {' Witness ': 4.4, ' Between Two Women ': 3.3, ' Made in Heaven ': 3.5, ' Murder on the Orient Express ': 3.8, ' Bodycount ': 2.3, ' A Clockwork Orange ': 3.5, ' Eyes of the Amaryllis ': 3.2, ' Three Strange Loves ': 0.2, ' Willy Wonka & the Chocolate Factory ': 1.1}, ' Brandy Powell ': {' Blue City ': 4.7, ' Bobby Deerfield ': 3.7, " Mama's Dirty Girls ": 3.1, ' Dogfight ': 2.2, ' Cancel My Reservation ': 1.5, ' Tightrope ': 1.9, ' Alamo ': 2.5, ' Saint ': 1.1}, ' Levi Schneider ': {' School Daze ': 2.1, ' Big Shots ': 5.0, ' Crocodile Dundee ': 3.1, ' A Clockwork Orange ': 2.7, ' Chattahoochee ': 2.7, ' Rain People ': 1.7, ' Until the End of the World ': 3.0, ' Ash Wednesday ': 0.4, ' Savage Intruder ': 3.0}, ' Terry Cruz ': {' Back in the U.S.S.R. ': 2.1, ' Stealing Home ': 4.4, ' Magic Town ': 4.6}, ' Erin Gibbs ': {' Fire with Fire ': 2.7, " Hollywood's Greatest War Movies ": 0.5, ' My Fair Lady ': 2.8, ' Medicine Man ': 2.1, ' Fawlty Towers ': 0.5, ' Romulus & the Sabines ': 1.8, ' Being There ': 0.6, ' Fighting Kentuckian ': 4.2, ' Father Murphy ': 0.6}, ' Kelly Bailey ': {' Bloodsport ': 2.3, ' Sweet Smell of Success ': 0.5, ' Big Jake ': 4.8, ' Not Without My Daughter ': 4.6, ' Death of a Salesman ': 3.5, ' After Dark My Sweet ': 1.5, ' Rhapsody in August ': 2.3, ' Anastasia ': 0.2, ' Romancing the Stone ': 1.7}, ' Angelina Pierce ': {' Danton ': 1.3, ' Stacey! ': 2.1, ' Raising Arizona ': 4.3, ' Golden Child ': 3.3, ' Flying Leathernecks ': 2.4}, ' Lynn Newton ': {' Manhunt ': 2.5, ' To Die Standing ': 4.2, " National Lampoon's Christmas Vacation ": 0.6, ' Hells Angels on Wheels ': 5.0, ' Betty Blue ': 4.3, ' Terminator ': 3.4, ' Nine & a Half Weeks ': 4.7, ' Tom Thumb ': 4.7}, ' Tricia Stewart ': {' Zandalee ': 0.4, ' Chattahoochee ': 2.2, ' Never on Tuesday ': 2.7, ' Double Edge ': 2.1}, ' Stacy Johnston ': {' Death Valley Days ': 1.4, ' Time Bandits ': 2.2, ' Goodbye Girl ': 0.2, ' Subway ': 1.7, ' Masque of the Red Death ': 0.5, ' Unnamable II ': 0.7}, ' Douglas Taylor ': {' No Small Affair ': 0.8, ' Flight of the Intruder ': 2.6, ' New Jack City ': 4.8, ' Kiss of the Spider Woman ': 1.8, ' Man Who Loved Women ': 0.4, ' Running Out of Luck ': 1.8}, ' Rex Neal ': {' Left Handed Gun ': 2.6, ' Alien Three ': 1.5, ' Blue Velvet ': 1.1, ' Buddy System ': 0.7, ' King of the Pecos ': 1.8, ' Elena & Her Men ': 1.2, ' Night on Earth ': 3.1}, ' Terrence Morris ': {' Il Bidone ': 1.0, ' Funny Girl ': 3.6, " Nobody's Fool ": 1.6, " Hang 'em High ": 0.7}, ' Leon Burton ': {' Women ': 2.6, ' Back to the Future II ': 1.7, ' Case of the Mukkinese Battle Horn ': 4.2, ' Two Women ': 3.4, ' Island of Dr. Moreau ': 1.0}, ' Johanna Greer ': {' Crash & Burn ': 2.7, ' Dear America ': 4.1, ' Judgment at Nuremberg ': 4.2, ' Back to the Future ': 4.8, ' Black Orchid ': 1.3, " Daffy Duck's Quackbusters ": 4.9}, ' Timmy Ballard ': {' One Frightened Night ': 2.5, ' Primal Rage ': 4.4, ' Catch a Rising Star ': 0.7, ' Tom Sawyer ': 0.8, ' Mc Q ': 4.6, ' Deceivers ': 2.0}, ' Jay Joseph ': {' Henry ': 4.1, ' Deceivers ': 3.2, ' Mr. & Mrs. Smith ': 1.5, ' In a Shallow Grave ': 4.5, ' Texas ': 1.0}, ' Winifred Elliott ': {' Best Defense ': 4.9, ' Crash & Burn ': 2.2, ' Erik the Viking ': 2.7, ' Shoot Loud ': 4.6, ' B. A. D. Cats ': 3.0, ' Prettykill ': 0.8, ' Still of the Night ': 3.4, ' Rebel Rousers ': 3.0}, ' Rachel Figueroa ': {' Lair of the White Worm ': 3.6, ' Ladyhawke ': 3.6, ' Mystic Pizza ': 4.5, ' Jet Pilot ': 2.5, ' La Chevre ': 0.6, ' Le Dernier Combat ': 2.5, ' After Dark My Sweet ': 1.3, ' Baja Oklahoma ': 4.7}}

category = {'Tie Me Up! Tie Me Down!','Comedy'
'High Heels','Comedy'
'Dead Zone',' Horror'
'Cuba','Action'
'Days of Heaven','Drama'
'Octopussy','Action'
'Target Eagle','Action'
'American Angels: Baptism of Blood',' Drama'
'Subway','Drama'
'Camille Claudel','Drama'
'Fanny and Alexander','Drama'
'Tragedy of a Ridiculous Man','Drama'
'A Man & a Woman','Drama'
'A Man & a Woman: Twenty Years Later','Drama'
'Un Hombre y una Mujer','Drama'
'Official Story',' Drama'
'Lindbergh Kidnapping Case',' Drama'
'Blackmail','Mystery'
'Donovan\'s Reef','Comedy'
'Tucker: The Man & His Dream','Drama'
'Scrooged','Comedy'
'Raiders of the Lost Ark','Action'
'Running Man',' Science Fiction'
'Predator 2','Action'
'Colors','Drama'
'Zandalee','Drama'
'Miles from Home','Drama'
'Happy Birthday to Me','Horror'
'Final Notice','Mystery'
'Quintet','Drama'
'Devil\'s Eye',' Drama'
'Wild Strawberries','Drama'
'Seventh Seal',' Drama'
'Germicide','Drama'
'Dreams','Drama'
'Naked Night',' Drama'
'Through a Glass Darkly','Drama'
'Cries & Whispers','Drama'
'Barbarian & the Geisha',' Action'
'Casino Royale','Comedy'
'Dr. No','Action'
'Elephant Walk','Drama'
'Ten','Comedy'
'Man Who Loved Women','Comedy'
'Hawaii','Drama'
'Torn Curtain','Mystery'
'Duet for One','Drama'
'Sound of Music',' Music'
'Gonzo Presents Muppet Weird Stuff','Comedy'
'Tartuffe','Comedy'
'A New Life','Comedy'
'Magic','Mystery'
'Tommy','Music'
'Big Fix',' Mystery'
'Alan & Naomi','Drama'
'Fatal Attraction','Mystery'
'Patriot Games','Action'
'Woman Next Door',' Drama'
'Hunting','Mystery'
'Bataan','War'
'Siegfried',' Drama'
'Henry',' Horror'
'Big Blue','Drama'
'Flight of the Intruder','Drama'
'Nobody\'s Fool','Comedy'
'After Hours','Comedy'
'Desperately Seeking Susan','Comedy'
'A New Leaf','Comedy'
'Killers of Kilimanjaro','Action'
'Don Juan','Action'
'Babette\'s Feast','Drama'
'Vincent',' Drama'
'Thunderball','Action'
'Lodger (Story of the London Fog)','Mystery'
'Appointment with Death','Mystery'
'Murder on the Orient Express','Mystery'
'Blood Alley','War'
'Spy Who Loved Me','Action'
'Storm','Action'
'Bloodbath','Horror'
'Miami Cops','Action'
'Island of Dr. Moreau','Horror'
'Eighty-Four Charing Cross Road','Drama'
'Elephant Man',' Drama'
'Dr Alien','Science Fiction'
'Creepshow','Horror'
'Sammy & Rosie Get Laid','Drama'
'Goalie\'s Anxiety at the Penalty Kick',' Drama'
'Mademoiselle Striptease','Comedy'
'Women',' Drama'
'That Naughty Girl','Comedy'
'Voulez-Vous Danser Avec Moi?','Comedy'
'A Coeur Joie',' Action'
'Shalako','Westerns'
'Contempt','Drama'
'Dear Brigitte','Comedy'
'A Very Private Affair','Drama'
'Ravishing Idiot',' Comedy'
'Bride Is Much Too Beautiful','Comedy'
'Doctor at Sea','Comedy'
'Le Repos Du Guerrier','War'
'And God Created Woman','Drama'
'Ms. Don Juan','Drama'
'Siesta','Drama'
'Rich & Strange','Drama'
'Lionheart','Action'
'E. T. The Extra-Terrestrial','Science Fiction'
'Cool World','Drama'
'Nadine','Comedy'
'Batman','Action'
'Blind Date','Comedy'
'Mother Lode','Action'
'Final Analysis','Drama'
'Never Say Never Again','Action'
'Nine & a Half Weeks','Drama'
'Killjoy','Mystery'
'No Mercy','Drama'
'Marrying Man',' Comedy'
'Misery','Horror'
'Crisis','Drama'
'Samson & Delilah','Drama'
'Act of Piracy','Mystery'
'Split Decisions','Drama'
'Vampire\'s Kiss','Comedy'
'Nightmare at Noon','Action'
'Presumed Innocent','Mystery'
'Reap the Wild Wind','Drama'
'Pocket Money','Comedy'
'Mary White','Drama'
'Catch a Rising Star',' Comedy'
'Guilty by Suspicion','Drama'
'Secret Beyond the Door','Mystery'
'Scarlet Street','Drama'
'Daffy Duck\'s Quackbusters','Action'
'Rowlf\'s Rhapsodies with the Muppets','Comedy'
'Gandhi','Drama'
'Wind & the Lion',' Action'
'Carnal Knowledge','Drama'
'Getting Straight','Comedy'
'Scarlet Letter',' Drama'
'Count of Old Town',' Comedy'
'Autumn Sonata','Drama'
'Gaslight','Drama'
'Indiscreet','Drama'
'Walpurgis Night','Drama'
'Joan of Arc','Drama'
'A Woman Called Golda','Drama'
'A Walk in the Spring Rain','Drama'
'Under Capricorn','Drama'
'Notorious','Mystery'
'June Night','Drama'
'Goodbye Again','Drama'
'Anastasia','Drama'
'Bells of St. Mary\'s',' Drama'
'Intermezzo','Drama'
'A Woman\'s Face','Drama'
'Swedenhielms','Drama'
'Only One Night','Drama'
'Dollar','Drama'
'Elena & Her Men','Drama'
'Europa Fifty-One','Drama'
'Voyage in Italy','Drama'
'Fear','Drama'
'Stromboli','Drama'
'Cactus Flower','Comedy'
'Hideaways','Comedy'
'Twenty Four Hours in a Woman\'s Life','Drama'
'Programmed to Kill','Action'
'Conan the Barbarian','Action'
'Raw Nerve','Mystery'
'Think Dirty','Comedy'
'King of Comedy','Drama'
'Best of the Big Laff Off',' Comedy'
'Amadeus','Drama'
'White Lightning','Action'
'Unbearable Lightness of Being',' Drama'
'Life & Times of Judge Roy Bean','WEstern'
'Airport','Drama'
'Day for Night','Drama'
'Secrets of Women','Comedy'
'Burnt Offerings','Horror'
'Easy Rider','Drama'
'Five Easy Pieces','Drama'
'Day of the Locust',' Drama'
'Goldfinger','Action'
'Exorcist II','Horror'
'White Lightning',''
'Lady for a Night','Drama'
'Charly','Drama'
'High Plains Drifter','Western'
'Honkytonk Man','Drama'
'Nightbreed','Horror'
'Under the Sun of Satan','Drama'
'Vagabond','Drama'
'Bill Cosby','Comedy'
'Monty Python & the Holy Grail','Comedy'
'John Cleese on How to Irritate People','Comedy'
'Matchmaker',' Comedy'
'For Your Eyes Only','Action'
'Wings','War'
'Medicine Man','Action'
'Good Fellas','Drama'
'Kiss of the Spider Woman','Drama'
'Rookie','Action'
'Sting','Drama'
'Torpedo Run','War'
'Instant Justice','Drama'
'Cyrano de Bergerac','Drama'
'Border Street','Drama'
'Firehouse','Comedy'
'Morituri','Drama'
'From the Life of the Marionettes','Drama'
'Frantic','Mystery'
'Coma','Science Fiction'
'Dead Ringers','Drama'
'Golden Ninja Invasion','Action'
'Exorcist','Horror'
'Alice Doesn\'t Live Here Anymore','Comedy'
'Eyes of the Amaryllis','Drama'
'What Price Glory?','War'
'Inauguration of the Pleasure Dome','Short'
'School Daze','Comedy'
'End of Innocence','Drama'
'Anderson Tapes','Mystery'
'Father Murphy','Comedy'
'Skull','Drama'
'Quick & The Dead','WEstern'
'Best Defense','Comedy'
'Dreamscape','Science Fiction'
'Black Rain','Action'
'8 1/2','Drama'
'One Frightened Night','Horror'
'Year My Voice Broke','Drama'
'Is Paris Burning?','War'
'QB VII','Drama'
'Island of Dr. Moreau','Horror'
'Beyond the Limit','Drama'
'Secret Agent','Mystery'
'Paramount Comedy Theater: Well-Developed','Comedy'
'Big Bust Out','Action'
'Fourth Protocol','Mystery'
'Gremlins 2: The New Batch','Comedy'
'Fast Times at Ridgemont High','Comedy'
'Mannequin','Comedy'
'Rabid','Horror'
'Party',' Comedy'
'Vampire Raiders','Action'
'Bloopers from Star Trek','Comedy'
'Destroyer','Action'
'Party Girl','Comedy'
'Twin Peaks','Mystery'
'Moonstruck','Comedy'
'Witches of Eastwick',' Comedy'
'Moonraker','Action'
'Beat Street','Drama'
'Running Out of Luck','Comedy'
'Never on Tuesday','Drama'
'Shampoo','Comedy'
'Power','Drama'
'Darling','Drama'
'Ugly American','Drama'
'Ambassador Bill','Comedy'
'Big Trail','WEstern'
'Hombre','Western'
'Coogan\'s Bluff','Action'
'Penn & Teller Get Killed','Comedy'
'Shy People','Drama'
'It\'s My Turn','Comedy'
'Dangerous Liaisons','Drama'
'Reversal of Fortune','Drama'
'Meeting Venus','Comedy'
'Tomorrow Is Forever','Drama'
'Like Father Like Son','Comedy'
'Rope','Drama'
'Road to Hong Kong','Comedy'
'Shirley Valentine','Comedy'
'City of Joy','Drama'
'Appaloosa','WEstern'
'Seven Minutes in Heaven','Comedy'
'Hearts of Darkness','Drama'
'Tonight for Sure','Comedy'
'White Hunter','Adventure'
'Sundays & Cybele','Drama'
'Puppet Master','Science Fiction'
'Night Gallery','Horror'
'Pet Sematary','Horror'
'America\'s Music','Music'
'Slap Shot','Comedy'
'O. C. & Stiggs','Comedy'
'A Fish Called Wanda','Comedy'
'A Lesson in Love','Comedy'
'Brink of Life','Drama'
'Betty Blue','Drama'
'Hair','Music'
'National Lampoon\'s Christmas Vacation','Comedy'
'Dersu Uzala','Adventure'
'Alice','Comedy'
'Fifth Floor','Mystery'
'Snow Kill','Drama'
'People','Drama'
'True Grit','Western'
'Battle of Midway','War'
'Three Godfathers','Western'
'Hush','Mystery'
'A Stolen Life','Drama'
'Old Maid','Drama'
'All about Eve','Drama'
'Fly','Horror'
'Quick Change','Comedy'
'Lair of the White Worm','Horror'
'Rainbow','Drama'
'Man Who Knew Too Much','Mystery'
'Beauty & the Beast','Science Fiction'
'Foreign Correspondent','Mystery'
'Heiress','Drama'
'Boy Who Could Fly','Drama'
'Terrorists','Action'
'Wheel of Fortune','Drama'
'Do the Right Thing','Drama'
'Court-Martial of Jackie Robinson','Drama'
'Elvira Madigan','Drama'
'Hurricane Smith','Action'
'Fair Game','Action'
'Rape of the Sabines','Action'
'Risky Business','Comedy'
'I Love All of You (Je Vous Aime)','Drama'
'Love Songs','Drama'
'Le Choix des Armes','Mystery'
'Choice of Arms','Action'
'March or Die','War'
'Last Metro','Drama'
'Jean de Florette','Drama'
'Fat Man & Little Boy','Drama'
'Wild at Heart','Drama'
'Family Business','Action'
'Stand & Deliver','Drama'
'Looker','Science Fiction'
'Fire & Rain','Action'
'Best of Candid Camera',' Comedy'
'Seven Sinners','Drama'
'Judgment at Nuremberg','Drama'
'Minsky\'s Follies','Comedy'
'Novice',' Comedy'
'Wings of Desire','Drama'
'Until the End of the World','Drama'
'Castaway','Drama'
'Alfred Hitchcock Presents','Mystery'
'Delicatessen','Comedy'
'Great Train Robbery','Mystery'
'Hanover Street','Drama'
'Hunchback','Drama'
'My Darling Clementine','Western'
'Wagon Master','Western'
'She Wore a Yellow Ribbon','Western'
'Fantasy Man','Comedy'
'Monster in the Closet','Comedy'
'Double Edge','Drama'
'Network','Comedy'
'Chinatown','Drama'
'Three Days of the Condor','Drama'
'Voyage of the Damned','Drama'
'Barfly','Drama'
'Wait Until Spring','Drama'
'Life with Father','Comedy'
'A Guy Named Joe','Drama'
'Stavisky','Drama'
'Time Bandits','Comedy'
'Shining','Horror'
'Flame of Barbary Coast','Western'
'Naked Truth',' Comedy'
'Brood','Horror'
'Molly Maguires','Action'
'Beverly Hills Cop','Comedy'
'Blind Man\'s Bluff','Mystery'
'La Dolce Vita','Drama'
'After the Fox','Comedy'
'Man with the Golden Gun','Action'
'Marbella','Action'
'Bobo','Comedy'
'Big Bands','Music'
'Killer Image.','Mystery'
'Kandyland','Drama'
'Campus Man','Drama'
'Jubal','Drama'
'Purple Rose of Cairo',' Comedy'
'Broadway Danny Rose','Comedy'
'Husbands & Wives','Comedy'
'Hannah & Her Sisters','Comedy'
'Hurricane','Action'
'Between Two Women','Drama'
'Cannonball Run',' Comedy'
'Doughnuts & Society','Comedy'
'Holocaust','Drama'
'Meridian','Science Fiction'
'Diary of a Hitman','Drama'
'Gor','Action'
'Surrender','Comedy'
'Places in the Heart','Drama'
'Not Without My Daughter','Drama'
'Heroes','Drama'
'Absence of Malice','Drama'
'Norma Rae','Drama'
'Steel Magnolias','Drama'
'Burbs','Comedy'
'Empire Strikes Back','Science Fiction'
'Star Wars','Science Fiction'
'Return of the Jedi','Science Fiction'
'Hear My Song','Drama'
'Slightly Scarlet','Action'
'Gunfight at the OK Corral','Western'
'Range Feud','Western'
'Bloodsucking Pharaohs in Pittsburgh','Comedy'
'Roma','Drama'
'China Syndrome','Drama'
'Morning After','Mystery'
'Klute','Drama'
'Electric Horseman','Comedy'
'Cat Ballou','Comedy'
'Coming Home','Drama'
'Rebecca','Drama'
'Jane Eyre','Drama'
'Stacey!','Action'
'Naked Obsession','Mystery'
'Stripped to Kill II','Mystery'
'Rain Killer','Mystery'
'Valley Girl','Comedy'
'Silence of the Lambs','Mystery'
'Stealing Home','Drama'
'Napoleon & Samantha','Comedy'
'Five Corners','Drama'
'Blackboard Jungle','Drama'
'My Left Foot','Drama'
'Back to the Beach','Comedy'
'Painted Veil','Drama'
'Inspiration','Drama'
'Anna Christie','Drama'
'Flesh & the Devil','Drama'
'Woman of Affairs','Drama'
'Anna Karenina','Drama'
'Camille','Drama'
'Mata Hari','Drama'
'Wild Orchids','Drama'
'Grand Hotel','Drama'
'Susan Lennox','Drama'
'Ninotchka','Comedy'
'Queen Christina','Drama'
'Mysterious Lady','Drama'
'Joyless Street','Drama'
'Single Standard','Drama'
'As You Desire Me','Drama'
'Romance','Drama'
'A Child Is Waiting','Drama'
'Tootsie','Comedy'
'Let It Ride','Comedy'
'Julius Caesar','Drama'
'Nineteen Forty-One','Comedy'
'Jaws','Action'
'Hot Pursuit','Drama'
'Triumph of the Spirit','Drama'
'Brannigan','Drama'
'Buffet Froid','Comedy'
'Salvador','Drama'
'Horse Soldiers','Western'
'Long John Silver','Action'
'Hustler','Drama'
'Star Chamber','Drama'
'Clara\'s Heart','Drama'
'Burglar','Comedy'
'Comic Relief','Comedy'
'Bloodbrothers','Drama'
'Rain Man','Drama'
'Masculine Feminine','Drama'
'Outer Limits','Science Fiction'
'Mama\'s Dirty Girls','Horror'
'Last Ride of the Dalton Gang','Western'
'Why Me?','Comedy'
'Number Seventeen','Crime'
'Manhunter','Drama'
'Bonfire of the Vanities','Drama'
'Working Girl','Comedy'
'Shining Through','Mystery'
'Slumber Party Massacre III','Horror'
'Tokyo Pop','Comedy'
'Terminator 2','Action'
'Terminator','Action'
'King Kong Lives!','Action'
'Those Daring Young Men in Their Jaunty','Comedy'
'At Play in the Fields of the Lord','Drama'
'Crazy People','Comedy'
'Memoirs of an Invisible Man','Comedy'
'Clan of the Cave Bear','Drama'
'Final Terror','Horror'
'Reckless','Drama'
'High Spirits','Comedy'
'Roxanne','Comedy'
'Blade Runner','Action'
'Wall Street','Drama'
'Pope of Greenwich Village','Drama'
'After School','Drama'
'Flaming Frontiers','Western'
'Libeled Lady','Comedy'
'Inserts','Drama'
'Blue Iguana','Drama'
'Tender Mercies','Drama'
'Nights in White Satin','Drama'
'Videodrome','Horror'
'Intimate Stranger','Mystery'
'Highlander','Science Fiction'
'Bodycount','Action'
'Tango & Cash','Action'
'There\'s a Girl in My Soup','Comedy'
'Swing Shift','Drama'
'Foul Play','Comedy'
'Best Friends','Comedy'
'Butterflies Are Free','Drama'
'Overboard','Comedy'
'Girl from Petrovka','Drama'
'Housesitter','Comedy'
'Wildcats','Comedy'
'Protocol','Comedy'
'Seems Like Old Times','Comedy'
'Sugarland Express','Drama'
'Private Benjamin','Comedy'
'Deceived','Mystery'
'Arrowsmith','Drama'
'Say Goodbye Maggie Cole','Drama'
'Circus World','Drama'
'Affair in Trinidad','Drama'
'Lady from Shanghai','Mystery'
'Lady in Question','Drama'
'Gilda','Drama'
'Loves of Carmen','Drama'
'Dick Tracy','Comedy'
'Marnie','Drama'
'Hot Child in the City','Mystery'
'Johnny Dangerously','Comedy'
'Stark','Mystery'
'Three Strange Loves','Drama'
'My Fair Lady','Music'
'Unforgiven','Drama'
'Robin & Marian','Action'
'Children\'s Hour','Drama'
'Rainmaker','Drama'
'Pat & Mike','Comedy'
'Lion in Winter','Drama'
'Sea of Grass','Western'
'Guess Who\'s Coming to Dinner','Drama'
'Desk Set','Comedy'
'Rooster Cogburn','Western'
'On Golden Pond','Drama'
'Adam\'s Rib','Comedy'
'Boom Town','Drama'
'Dragon Seed','Drama'
'Little Women','Drama'
'Philadelphia Story','Comedy'
'Without Love','Comedy'
'Woman of the Year','Comedy'
'Juice','Drama'
'Hoosiers','Drama'
'Tin Men','Comedy'
'Last Temptation of Christ','Drama'
'Paris Trout','Drama'
'Souvenir','Drama'
'A Man for All Seasons','Drama'
'Knights & Emeralds','Drama'
'Masque of the Red Death','Horror'
'Adventures of Smilin\' Jack','Mystery'
'Adventures in Dinosaur City','Action'
'Allnighter','Comedy'
'Caddyshack','Comedy'
'Tom Sawyer','Music'
'Rita','Comedy'
'Hawk of Powder River','Western'
'Tempest','Drama'
'Running Mates','Drama'
'Prettykill','Drama'
'Judge Priest','Drama'
'Harvey','Comedy'
'If Looks Could Kill','Action'
'Raising Arizona','Comedy'
'Once Around','Comedy'
'Loulou','Drama'
'World According to Garp','Drama'
'Virus','Science Fiction'
'Northwest Passage','Action'
'Gardens of Stone','Drama'
'Enemies','Drama'
'Addams Family','Comedy'
'Freaks','Horror'
'Necessary Roughness','Comedy'
'A Show of Force','Drama'
'Competition','Drama'
'Crossing Delancey','Comedy'
'State of Things','Drama'
'Business As Usual','Comedy'
'A Touch of Class','Comedy'
'Women in Love.','Drama'
'Salome\'s Last Dance','Comedy'
'Casino','Mystery'
'Smiles of a Summer Night','Comedy'
'New Year\'s Day','Comedy'
'Mephisto','Drama'
'Easy Virtue','Mystery'
'Swing It Sailor!','Comedy'
'Strictly Business','Comedy'
'Blame It on Rio','Comedy'
'Straight to Hell','Action'
'A View to a Kill','Action'
'American Anthem','Drama'
'Bedtime Story','Comedy'
'Courtship of Eddie\'s Father','Comedy'
'Night Train to Katmandu','Action'
'Port of Call','Drama'
'Paper Moon','Comedy'
'Yellowbeard','Comedy'
'Adventures of Sherlock Holmes\' Smarter','Comedy'
'Flashback','Comedy'
'World\'s Greatest Lover','Comedy'
'Killer\'s Kiss','Mystery'
'Deceivers','Action'
'Breathless','Action'
'Born on the Fourth of July','Drama'
'Awakenings','Drama'
'Annie Hall','Comedy'
'Manhattan','Comedy'
'Reds','Drama'
'Crimes of the Heart','Comedy'
'Looking for Mr. Goodbar','Drama'
'Godfather','Drama'
'Godfather','Drama'
'I Will','Comedy'
'Play It Again',' Sam'
'Love & Death','Comedy'
'Sleeper','Comedy'
'Fellini Satyricon','Drama'
'Formula','Mystery'
'Black Sunday','Drama'
'Bobby Deerfield','Drama'
'Last of the Red Hot Lovers','Comedy'
'Mogambo','Action'
'To Catch a Thief','Mystery'
'Rear Window','Mystery'
'Woman Who Came Back','Drama'
'Stanley & Livingstone','Action'
'Bad Seed','Horror'
'Lethal Weapon 2','Action'
'Blame It on the Bellboy','Comedy'
'Drop Kick','Drama'
'Superman','Action'
'Superman IV: The Quest for Peace','Action'
'Quackser Fortune Has a Cousin in the Bronx','Comedy'
'Dead Calm','Mystery'
'Days of Thunder','Action'
'My Life As a Dog','Comedy'
'Moon in the Gutter','Action'
'Paris','Drama'
'Unfaithfully Yours','Comedy'
'Bullseye!','Comedy'
'Erik the Viking','Action'
'Dragonard','Drama'
'Hard Choices','Drama'
'Rain People','Drama'
'A Year of the Quiet Sun','Drama'
'Desert Trail','western'
'Almost an Angel','Comedy'
'Crocodile Dundee','Comedy'
'American Friend','Mystery'
'See You in the Morning','Drama'
'Arrogant','Drama'
'Dracula\'s Widow','Horror'
'Ninja Masters of Death','Action'
'Mystery Train','Comedy'
'Go Tell the Spartans','War'
'True Stories','Comedy'
'Ugetsu Monogatari','Drama'
'Rebel Rousers','Action'
'Plain Clothes','Comedy'
'Whose Life Is It','Drama'
'Running on Empty','Drama'
'Funny about Love','Comedy'
'A Chorus Line','Music'
'Stewardess School','Comedy'
'Big Town','Drama'
'Rumble Fish','Drama'
'Outsiders','Drama'
'Priceless Beauty','Science Fiction'
'Streets of Fire','Action'
'Men Don\'t Leave','Drama'
'Everybody\'s All American','Romance'
'Cape Fear','Mystery'
'Postman Always Rings Twice','Mystery'
'Crashing Thru','Western'
'Get Out Your Handkerchiefs','Comedy'
'Boy Friend','Music'
'Hard To Kill','Action'
'Psycho','Horror'
'Jet Pilot','Action'
'Under Cover','Mystery'
'A Streetcar Named Desire','Drama'
'Golden Child','Comedy'
'Statue','Drama'
'Christopher Columbus','Drama'
'In Country','Drama'
'Wild Geese','Action'
'Second Coming of Suzanne.','Drama'
'Bronco Billy','Westerns'
'Gauntlet','Action'
'Ratboy','Drama'
'Lady Vanishes','Mystery'
'Kitchen Toto','Drama'
'Carlton-Browne of the F.O.','Comedy'
'Racketeer','Drama'
'Mr. & Mrs. Smith','Comedy'
'Alrededor de Medianoche','Drama'
'Losin\' It','Comedy'
'Into the Homeland','Action'
'Boxing Babes','Action'
'Shock \'em Dead','Horror'
'Heller in Pink Tights','Drama'
'Two Women','Drama'
'Gold of Naples','Drama'
'Yesterday','Comedy'
'Legend of the Lost','Action'
'Brass Target','Action'
'Fall of the Roman Empire','Drama'
'El Cid','Drama'
'Desire under the Elms','Drama'
'Two Nights with Cleo','Drama'
'Black Orchid','Drama'
'Angela','Drama'
'A Special Day','Drama'
'Blood Feud','Action'
'Sophia Loren','Drama'
'Running Away','Drama'
'Man of La Mancha','Music'
'Operation Crossbow','Action'
'Courage','Drama'
'RAD','Action'
'Secret Admirer','Comedy'
'Cocaine Cowboys','Action'
'Test Pilot','Drama'
'Ape Man','Horror'
'Mission','Drama'
'Curly Sue','Comedy'
'Lolita','Drama'
'Sex','Drama'
'Green Card','Comedy'
'Gator Bait II','Action'
'Being There','Comedy'
'Terms of Endearment','Drama'
'Woman Times Seven','Comedy'
'Bliss of Mrs. Blossom','Comedy'
'Postcards from the Edge','Comedy'
'Two Mules for Sister Sara','Western'
'Dragonfight','Drama'
'Back Door to Heaven','Drama'
'Ciao Italia','Music'
'Madonna','Music'
'A Certain Sacrifice','Music'
'National Enquirer','Music'
'Immaculate Collection','Music'
'Madonna Live','Music'
'Madonna','Music'
'Madonna','Music'
'Hot to Trot','Comedy'
'Fire with Fire','Drama'
'Hot Spot','Drama'
'Amarcord','Drama'
'Casablanca Express','Action'
'Out of the Blue','Drama'
'Sands of Iwo Jima','War'
'Hand','Horror'
'Deep Cover','Mystery'
'Il Bidone','Drama'
'El Guerrero Solitario','Drama'
'Heartbreak Ridge','War'
'Goodbye Girl','Comedy'
'Audrey Rose','Drama'
'Polyester','Comedy'
'Robin Hood: Prince of Thieves','Action'
'White Sands','Drama'
'Color of Money','Drama'
'Children of a Lesser God','Drama'
'Matador','Comedy'
'Women on the Verge of a Nervous Breakdown','Comedy'
'Pepi Luci Bom','Comedy'
'Forgotten','Mystery'
'Flame & the Arrow','Action'
'After the Shock','Drama'
'Modern Love','Comedy'
'Riff Raff','Comedy'
'Glory Stompers','Action'
'Dances with Wolves','Western'
'Matewan','Drama'
'Mississippi Burning','Drama'
'Eiger Sanction','Action'
'Unsettled Land','Drama'
'Cat Chaser','Drama'
'Accused','Drama'
'Winter People','Drama'
'Reuben','Comedy'
'Made in Heaven','Fantasy'
'Top Gun','Action'
'Witness','Drama'
'House on Carroll Street','Mystery'
'Racing with the Moon','Drama'
'Lovesick','Comedy'
'She\'s Having a Baby','Comedy'
'Greatest Story Ever Told','Drama'
'Hawks','Drama'
'So Fine','Comedy'
'Paths of Glory','Drama'
'Tom Jones','Drama'
'Sunshine Boys','Comedy'
'Caddyshack 2','Comedy'
'Internal Affairs','Drama'
'JFK','Drama'
'New Jack City','Action'
'Scenes from a Mall','Comedy'
'Hope & Glory','War'
'Ryan\'s Daughter','Drama'
'Man Who Loved Cat Dancing','western'
'Man Who Shot Liberty Valance','western'
'Dead-Bang','Action'
'Big Top Pee-wee','Comedy'
'Time Machine','Science Fiction'
'Cabaret','Drama'
'Arthur','Comedy'
'A Matter of Time','Drama'
'New York','Drama'
'Nightmare on Elm Street','Horror'
'Fiendish Plot of Dr. Fu Manchu','Comedy'
'Four American Composers','Music'
'Asphalt Jungle','Action'
'Ladies of the Chorus','Music'
'How to Marry a Millionaire','Comedy'
'Hollywood Out-Takes & Rare Footage','Comedy'
'Nothing But Trouble','Comedy'
'Wisdom','Action'
'One Crazy Summer','Comedy'
'We\'re No Angels','Comedy'
'No Small Affair','Comedy'
'Ghost','Science Fiction'
'About Last Night','Drama'
'Six Weeks','Drama'
'Return of October','Comedy'
'Come Back','Drama'
'Going Places','Drama'
'Monte Walsh','Western'
'Mr. Arkadin','Drama'
'White of the Eye','Mystery'
'Producers','Comedy'
'Front','Drama'
'House of the Rising Sun','Drama'
'In a Shallow Grave','Drama'
'Mc Q','Action'
'Lady from Louisiana','Drama'
'Wait Until Spring Bandini','Drama'
'Long Voyage Home','Drama'
'Trouble with Harry','Mystery'
'Encounters','Drama'
'Hud','Drama'
'Operation Pacific','War'
'Surf Nazis Must Die','Horror'
'Teahouse of the August Moon','Drama'
'Back in the U.S.S.R.','Action'
'Man Who Haunted Himself','Drama'
'Prisoner of Honor.','Drama'
'Control','Drama'
'Desert Rider','Western'
'Wholly Moses!','Comedy'
'Star Trek VI: The Undiscovered Country','Science Fiction'
'Star Trek V: The Final Frontier','Action'
'Circuitry Man','Action'
'Cobra','Action'
'Beverly Hills Cop II','Comedy'
'Red Sonja','Action'
'To Joy','Drama'
'Macbeth','Drama'
'Vertigo','Drama'
'Young Love: Lemon Popsicle Seven','Comedy'
'Crack-Up','Mystery'
'Bury Me Not on the Lone Prairie','Western'
'Law & Order','Western'
'Man from Montana','Western'
'Long Gray Line','Drama'
'Rio Grande','Western'
'Wings of Eagles','Drama'
'Jamaica Inn','Drama'
'Big Jake','Action'
'Quiet Man','Drama'
'After the Rehearsal','Drama'
'Big Jim McLain','Western'
'Smith!','Western'
'Wild One','Drama'
'Manxman','Drama'
'International Velvet','Drama'
'Scanners','Horror'
'Trick or Treat','Horror'
'48 Hrs.','Action'
'Trip to Bountiful','Drama'
'Mister Roberts','Comedy'
'Z','Drama'
'Maurice','Drama'
'Hamlet','Drama'
'La Femme Nikita','Drama'
'Honeymoon in Vegas','Comedy'
'Going for the Gold','Action'
'Shout at the Devil','Action'
'A Smoky Mountain Christmas','Music'
'Getting Physical','Drama'
'Torn Apart','Drama'
'From the Hip','Comedy'
'Ratings Game','Comedy'
'Class Act','Drama'
'Water','Comedy'
'Silent Movie','Comedy'
'Pink Cadillac','Comedy'
'Jerk','Comedy'
'Wild Times',''
'Sweet Liberty','Comedy'
'Grease II','Music'
'Married to the Mob','Comedy'
'Ladyhawke','Adventure'
'Fabulous Baker Boys','Drama'
'Into the Night','Comedy'
'Russia House','Drama'
'Tequila Sunrise','Mystery'
'B. A. D. Cats','Action'
'Last Movie','Drama'
'Dillinger','Drama'
'Little Dorrit','Drama'
'My Best Girl','Drama'
'Seizure','Horror'
'A Chorus of Disapproval','Comedy'
'Rome Adventure','Drama'
'Drowning by Numbers','Mystery'
'Born to Ride','Action'
'Her Alibi','Comedy'
'Glitz','Mystery'
'Dangerous Pursuit','Mystery'
'Experiment in Terror','Mystery'
'Hideaways','Comedy'
'What\'s New Pussycat','Comedy'
'What\'s New Pussycat?','Comedy'
'Packin\' It In','Comedy'
'Naked Gun: From the Files of Police Squad!','Comedy'
'In Too Deep','Drama'
'Twins','Comedy'
'Experts','Comedy'
'Naked Lie','Drama'
'Mistress','Drama'
'Pleasure Palace','Action'
'Adam at 6 A.M.','Drama'
'Web of Deceit','Drama'
'New York Stories','Comedy'
'Dreams Lost','Drama'
'Au Revoir les Enfants','Drama'
'Quo Vadis','Drama'
'Fighting Kentuckian','Action'
'Zardoz','Science Fiction'
'Police Academy 6: City under Siege','Comedy'
'Police Academy 5: Assignment Miami Beach','Comedy'
'Police Academy 3: Back in Training','Comedy'
'America\'s Music','Music'
'Julia','Drama'
'Devils','Drama'
'Ransom','Drama'
'Cadillac Man','Comedy'
'Best of Times','Comedy'
'Death of a Salesman','Drama'
'It Started with a Kiss','Drama'
'Money','Drama'
'Empire of the Sun','Drama'
'Comfort of Strangers','Mystery'
'On Her Majesty\'s Secret Service','Action'
'Pretty in Pink','Drama'
'PK. & the Kid.','Drama'
'Lone Star Trail','Western'
'Summer','Comedy'
'Planes','Comedy'
'Pretty Woman','Comedy'
'Flatliners','Drama'
'Hook','Action'
'Riders of Pasco Basin','Western'
'Gotta Dance','Music'
'Desperate Hours','Mystery'
'Gung Ho','Comedy'
'Shooting Elizabeth','Mystery'
'Strangers on a Train','Mystery'
'Sacketts','Western'
'To Die Standing','Action'
'Rodeo Girl','Drama'
'Butch Cassidy & the Sundance Kid','Western'
'Hellfighters','Action'
'Final Countdown','Action'
'Blue Velvet','Mystery'
'Cousins','Comedy'
'Black & White in Color','Comedy'
'Another Woman','Drama'
'Night on Earth','Drama'
'Permanent Record','Drama'
'Fisher King','Drama'
'Another You','Comedy'
'Young Lions','Drama'
'Cheerleader Camp','Horror'
'Trapper County War','Action'
'Angel & the Badman','Western'
'Impulse','Mystery'
'Track Twenty-Nine','Drama'
'Freejack','Action'
'John Wayne Matinee Double Feature','Western'
'Smallest Show on Earth','Comedy'
'Innerspace','Science Fiction'
'Presidio','Action'
'Joe Versus the Volcano','Comedy'
'Doors','Drama'
'Welcome Home','Comedy'
'Cancel My Reservation','Comedy'
'North by Northwest','Mystery'
'Russians Are Coming','Comedy'
'Exodus','Drama'
'Ballad of Narayama','Drama'
'Out of the Darkness','Mystery'
'Garden of the Finzi-Continis','Drama'
'Steppenwolf','Drama'
'Mackintosh Man','Action'
'Partner','Drama'
'Conformist','Drama'
'Dirty Harry','Drama'
'Ferris Bueller\'s Day Off','Comedy'
'Legend','Science Fiction'
'Buddy System','Drama'
'A Dry White Season','Drama'
'Rocky Horror Picture Show','Music'
'War & Peace','Drama'
'Defense of the Realm','Drama'
'Basil The Rat','Comedy'
'Fawlty Towers','Comedy'
'Going Under','Comedy'
'U S. Sub Standard.','Comedy'
'Hells Angels on Wheels','Action'
'Passenger','Drama'
'Last Tango in Paris','Drama'
'Indigo Autumn & Lilac Dream','Drama'
'Kriemhild\'s Revenge','Drama'
'Johnny Tiger','Drama'
'Head Office','Comedy'
'Live & Let Die','Action'
'Le Charme Discret de la Bourgeoisie','Comedy'
'Blue City','Action'
'Bad Boys','Drama'
'Whoopee Boys','Comedy'
'Last Picture Show','Drama'
'Diamond Trap','Drama'
'Endless Love','Drama'
'Rocky','Drama'
'Cocktail','Drama'
'Sabotage','Mystery'
'Madame Rosa','Drama'
'Fozzie\'s Muppet Scrapbook','Comedy'
'Desiree','Drama'
'Spartacus','Drama'
'Guys & Dolls','Comedy'
'Until They Sail','Drama'
'Coming to America','Comedy'
'Lilies of the Field','Drama'
'River\'s Edge','Drama'
'Ruthless People','Comedy'
'Secret of My Success','Comedy'
'Shop on Main Street','Drama'
'Funny Farm','Comedy'
'Lonely Passion of Judith Hearne','Drama'
'California Suite','Comedy'
'Maximum Overdrive','Horror'
'Pale Rider','Western'
'Kissing Place','Drama'
'French Lesson','Comedy'
'Roller Blade','Action'
'A Shot in the Dark','Comedy'
'Treasure Seekers','Action'
'Missing','Drama'
'Picasso Trigger','Action'
'Hard Ticket to Hawaii','Action'
'Diamonds are Forever','Action'
'Baby Face','Drama'
'Violent Men','Action'
'Cocoon','Science Fiction'
'Clockwise','Comedy'
'Romantic Comedy','Comedy'
'Outland','Science Fiction'
'Hang \'em High','Western'
'Basic Instinct','Mystery'
'Total Recall','Action'
'Stakeout','Comedy'
'Unnamable II','Drama'
'Trip','Drama'
'Ironweed','Drama'
'Kramer vs. Kramer','Drama'
'Still of the Night','Mystery'
'Defending Your Life','Comedy'
'Deer Hunter','Drama'
'Falling in Love','Drama'
'Heartburn','Comedy'
'Silkwood','Drama'
'Sophie\'s Choice','Drama'
'Out of Africa','Drama'
'French Lieutenant\'s Woman','Drama'
'Plenty','Drama'
'A Cry in the Dark','Drama'
'She-Devil','Comedy'
'Death Becomes Her','Drama'
'Kids & Pesticides','Drama'
'On a Clear Day You Can See Forever','Music'
'Nuts','Drama'
'Yentl','Music'
'Funny Girl','Music'
'Fellow Traveller','Drama'
'Dodesukaden','Drama'
'Sicilian','Drama'
'So Ends Our Night','Drama'
'Sword of the Valiant','Action'
'Devil\'s Wanton','Drama'
'Driving Miss Daisy','Drama'
'Seventh Cross','Drama'
'Between Friends','Drama'
'Raintree County','Drama'
'Driver\'s Seat','Drama'
'Reflections in a Golden Eye','Drama'
'X','Drama'
'Secret Ceremony','Drama'
'Cleopatra','Drama'
'Father of the Bride','Comedy'
'Who\'s Afraid of Virginia Woolf?','Drama'
'A Little Night Music','Music'
'Giant','Drama'
'Rumor Mill','Drama'
'Lassie Come Home','Drama'
'Return Engagement','Drama'
'Hammersmith Is Out','Drama'
'Super Duper Bloopers','Comedy'
'Elizabeth Taylor Collection','Drama'
'Ash Wednesday','Drama'
'Last Time I Saw Paris','Drama'
'Cimarron','Western'
'Apache Woman','Western'
'Gary Numan - Berzerker','Music'
'Mystic Pizza','Comedy'
'Dogfight','Action'
'Adventures of Rex & Rinty','western'
'Daphnis & Chloe','Music'
'Marathon','Comedy'
'Fort Apache','Western'
'Wee Willie Winkie','Drama'
'Big Shots','Action'
'Doin\' Time on Planet Earth','Comedy'
'All the Right Moves','Drama'
'Some Kind of Wonderful','Drama'
'All New Tales from the Crypt','Horror'
'Back to the Future','Comedy'
'Winter Light','Drama'
'Silence','Drama'
'Magician','Drama'
'Four Horsemen of the Apocalypse','Drama'
'Critical Condition','Comedy'
'Center of the Web','Mystery'
'Border Shootout','Action'
'Lean on Me','Drama'
'On Wings of Eagles','Drama'
'Texas','Western'
'Allegheny Uprising','Drama'
'Dark Command','Western'
'Peggy Sue Got Married','Drama'
'Dear America','War'
'Prizzi\'s Honor','Comedy'
'Man with Two Brains','Comedy'
'Crimes of Passion','Drama'
'Jewel of the Nile','Action'
'Romancing the Stone','Action'
'Accidental Tourist','Comedy'
'Sea Chase','War'
'Another Time','Drama'
'Cannibal Women in the Avocado Jungle of Death','Comedy'
'Mr Love.','Comedy'
'2001: A Space Odyssey','Science Fiction'
'Persona','Drama'
'Scenes from a Marriage','Drama'
'Hour of the Wolf','Drama'
'Passion of Anna','Drama'
'Dangerous Moves','Drama'
'Sayonara','Drama'
'Where Eagles Dare','War'
'Teen Wolf','Drama'
'Amazon','Action'
'Paper Chase','Drama'
'Virgin Spring','Drama'
'Spider\'s Stratagem','Drama'
'Play Misty for Me','Mystery'
'Going Ape','Comedy'
'Cool Hand Luke','Drama'
'Phantom of the Ritz','Horror'
'Crash & Burn','Science Fiction'
'After Dark My Sweet','Mystery'
'Christopher Columbus: The Discovery','Adventure'
'Young Sherlock Holmes','Mystery'
'Doc Hollywood','Comedy'
'Baja Oklahoma','Comedy'
'Aliens','Science Fiction'
'Alien Three','Science Fiction'
'Alien: resurrection','Science Fiction'
'Alien','Science Fiction'
'One Woman or Two','Comedy'
'Soggy Bottom U. S. A.','Comedy'
'Bang the Drum Slowly','Drama'
'Catamount Killing','Action'
'Fuzz','Action'
'Shoot Loud','Mystery'
'Bedazzled','Comedy'
'Prince & the Pauper','Action'
'One Hundred Rifles','Western'
'Wild Party','Drama'
'Bandolero!','Western'
'Last of Sheila','Mystery'
'Hannie Caulder','Drama'
'Sounds of the Seventies...& the Beat Goes','Music'
'Bird','Drama'
'Meet Millie','Drama'
'Hell Comes to Frogtown','Science Fiction'
'Fortune Cookie','Comedy'
'Sun Shines Bright','Action'
'Squeeze','Action'
'Start the Revolution Without Me','Comedy'
'Major League','Comedy'
'Bright Lights','Drama'
'Lost Boys','Horror'
'Cookie','Comedy'
'Conversation','Drama'
'American Graffiti','Comedy'
'Dangerous When Wet','Music'
'Stir Crazy','Comedy'
'Young Einstein','Comedy'
'Killing','Drama'
'Cahill','Western'
'Savage Intruder','Horror'
'Sheltering Sky','Drama'
'An Officer & a Gentleman','Drama'
'Black Widow','Mystery'
'Legal Eagles','Comedy'
'Bloody Mama','Action'
'A Patch of Blue','Drama'
'I Died a Thousand Times','Drama'
'Tentacles','Horror'
'Scalphunters','Westerns'
'A Day in October','Drama'
'A Fistful of Dollars','Westerns'
'My Science Project','Comedy'
'Great Race','Comedy'
'Searchers','Western'
'Meteor','Action'
'Rebel Without a Cause','Drama'
'West Side Story','Music'
'Trash','Comedy'
'A Big Hand for the Little Lady','Comedy'
'A Fine Madness','Comedy'
'Glass Menagerie','Drama'
'Harry & Son','Drama'
'Rachel','Drama'
'Paris Blues','Drama'
'Fugitive Kind','Drama'
'Mr. & Mrs. Bridge','Drama'
'State of Grace','Drama'
'Shadow of a Doubt','Drama'
'Men','Drama'
'Stage Fright','Mystery'
'Magic Town','Drama'
'That Lucky Touch','Action'
'Lust for Gold','Drama'
'Heat','Mystery'
'Employee\'s Entrance','Drama'
'Night Is My Future','Drama'
'Witches','Science Fiction'
'Vera Cruz','Action'
'Apache','Western'
'Twilight\'s Last Gleaming','Drama'
'Frisco Kid','Comedy'
'Bank on the Stars','Drama'
'Law of Desire','Drama'
'Quiller Memorandum','Mystery'
'Longest Day','War'
'Name of the Rose','Drama'
'Bloodsport','Action'
'Torment','Horror'
'Pelle the Conqueror','Drama'
'Taps','Drama'
'Freshman','Comedy'
'Last Emperor','Drama'
'Grim Reaper','Drama'
'Le Dernier Combat','Drama'
'Too Beautiful for You','Drama'
'Fire','Action'
'Heavens Above','Comedy'
'One Eyed Jacks','Western'
'Swing It','Comedy'
'Wolf at the Door','Drama'
'Modern Times','Comedy'
'Thunderbolt & Lightfoot','Action'
'A Nous la Liberte','Drama'
'Scum','Action'
'Inside Man','Action'
'Apocalypse Now','Drama'
'Bellboy & the Playgirls','Drama'
'Terror','Horror'
'Raven','Horror'
'They Came from Within','Horror'
'Boy in Blue','Drama'
'Killer Tomatoes Strike Back','Comedy'
'Attack of the Killer Tomatoes','Comedy'
'Untouchables','Drama'
'Wise Guys','Comedy'
'American Autobahn','Drama'
'Final Alliance','Action'
'Bounty','Drama'
'Little Prince','Music'
'Posse','Western'
'Firefox','Action'
'Penitentiary III','Action'
'Ginger & Fred','Comedy'
'Wrong Box','Comedy'
'Wagonmaster','Western'
'They Were Expendable','War'
'Last Hurrah','Drama'
'Law of the Golden West','Western'
'Pioneer Marshal','Western'
'Ranger of the Cherokee Strip','Western'
'Vanishing Westerner','Western'
'Bandits of Dark Canyon','Western'
'Bold Frontiersman','Western'
'Wild Frontier','Western'
'Firemen\'s Ball','Comedy'
'Local Hero','Comedy'
'French Connection','Drama'
'To Live & Die in L. A.','Action'
'Ferry to Hong Kong','Drama'
'Eddie Murphy','Comedy'
'Secret Policeman\'s Private Parts','Comedy'
'Up the Creek','Comedy'
'Yol','Drama'
'Sara Dane','Drama'
'Night Tide','Drama'
'His Majesty O\'Keefe','Action'
'North to Alaska','Western'
'Flight to Fury','Action'
'Ride in the Whirlwind','Western'
'Powderkeg','Western'
'I Confess','Drama'
'Thirty-Nine Steps','Science Fiction'
'Topaz','Mystery'
'Murder','Mystery'
'Dial M for Murder','Mystery'
'Young & Innocent','Mystery'
'Creature from Black Lake','Horror'
'Chariots of Fire','Drama'
'Monty Python Live at the Hollywood Bowl','Comedy'
'Man Who Would Be King','Drama'
'Victory','Drama'
'Kelly\'s Heroes','War'
'Next of Kin','Mystery'
'Chattahoochee','Drama'
'Angelic Conversation','Comedy'
'Down by Law','Comedy'
'Killing Fields','Drama'
'Survival Zone','Action'
'Monty Python\'s Life of Brian','Comedy'
'Monty Python\'s the Meaning of Life','Comedy'
'Red Tent','Action'
'Dakota','Western'
'Viva Zapata!','Drama'
'Green Berets','War'
'Big Bad John','Action'
'Ticket of Leave Man','Mystery'
'D-Day','War'
'Apprenticeship of Duddy Kravitz','Drama'
'A Clockwork Orange','Science Fiction'
'Full Metal Jacket','War'
'Sanshiro Sugata','Drama'
'Rhapsody in August','Drama'
'No Regrets for Our Youth','Drama'
'Bad Sleep Well','Drama'
'Idiot','Drama'
'Rashomon','Drama'
'Sanjuro','Mystery'
'Seven Samurai','Drama'
'Throne of Blood','Drama'
'Yojimbo','Action'
'Kagemusha','Drama'
'Ikiru','Drama'
'Empire of Spiritual Ninja','Action'
'Ninja','Action'
'Metropolis','Science Fiction'
'Cloak & Dagger','Mystery'
'Spiders','Drama'
'Human Desire','Drama'
'Spies','Drama'
'Testament of Dr. Mabuse','Drama'
'Fury','Drama'
'Mo\' Better Blues','Drama'
'Matt Talbot','Drama'
'Will Rogers','Comedy'
'For a Few Dollars More','Westerns'
'Thirty Seconds over Tokyo','War'
'Class of 1984','Drama'
'Juggernaut','Action'
'Good Morning','Comedy'
'Blood on the Sun','Drama'
'Paint Your Wagon','Music'
'Ensign Pulver','Comedy'
'Street People','Action'
'Manhunt','Action'
'Operation Nam','War'
'Fighting Seabees','War'
'Let It Rock','Drama'
'Eraserhead','Horror'
'Ladykillers','Comedy'
'Sweet Smell of Success','Drama'
'And Now for Something Completely Different','Comedy'
'Crackers','Action'
'Green Glove','Drama'
'Menace on the Mountain','Action'
'In Old California','Western'
'Thirty Is a Dangerous Age','Comedy'
'Ffolkes','Action'
'Chisum','Western'
'Hunt for Red October','Drama'
'Closely Watched Trains','Drama'
'Executive Action','Drama'
'Flying Tigers','Action'
'Father\'s Little Dividend','Comedy'
'An Evening with Robin Williams','Comedy'
'Eddie Murphy Raw','Comedy'
'Harlem Nights','Comedy'
'Santee','Western'
'Good Father','Drama'
'Sometimes a Great Notion','Drama'
'Catch Twenty-Two','Comedy'
'Dark Age','Action'
'Deadline','Mystery'
'Mysterious Mr. Wong','Mystery'
'A Month in the Country','Drama'
'Prom Night III','Horror'
'Blood in','Drama'
'Wrong Arm of the Law','Comedy'
'Orphans','Drama'
'All the President\'s Men','Drama'
'J-Men Forever','Action'
'Wild Bunch','Western'
'Judgement in Berlin','Drama'
'Hot Line','Comedy'
'Rocket Gibraltar','Drama'
'Yakuza','Action'
'Jeremiah Johnson','Drama'
'Burn!','Drama'
'Magnum Force','Action'
'Cyborg','Action'
'Prisoner of Zenda','Comedy'
'Scream','Horror'
'Assault','Drama'
'Flying Leathernecks','Action'
'What Comes Around','Drama'
'Mon Oncle D\'Amerique','Comedy'
'Culpepper Cattle Company','Western'
'Survivors','Comedy'
'Roadhouse Sixty-Six','Action'
'Burning Poles','Music'
'Russkies','Action'
'My Blue Heaven','Comedy'
'Altered States','Science Fiction'
'Cowboys','Western'
'Code Name','Drama'
'Patton','War'
'Midnight Cowboy','Drama'
'Falcon & the Snowman','Drama'
'Maitresse','Drama'
'Disorderlies','Comedy'
'Raging Bull','Drama'
'Garrison Keillor\'s Home','Comedy'
'Overland Stage Raiders','Western'
'Pals of the Saddle','Western'
'Alone in the Dark','Horror'
'Beguiled','Drama'
'Escape from Alcatraz','Drama'
'Criss Cross','Drama'
'Midway','War'
'Indiana Jones & the Last Crusade','Action'
'Duel','Mystery'
'Separate but Equal','Drama'
'Gosta Berling\'s Saga','Drama'
'Platoon','Drama'
'Crawling Hand','Science Fiction'
'Willy Wonka & the Chocolate Factory','Music'
'Joe Kidd','Western'
'Santa Claus','Comedy'
'Boys Town','Drama'
'Erasure','Music'
'A Question of Honor','Drama'
'Check Your Guns','Western'
'West to Glory','Western'
'Throwback','Western'
'Border Feud','Action'
'Fighting Vigilantes','western'
'Law of the Lash','Western'
'Outlaw Country','Western'
'Return of the Lash','Action'
'Mystery of the Hooded Horsemen','Western'
'Tex Rides with the Boy Scouts','Western'
'Shadows of the West','Western'
'Instant Karma','Comedy'
'Time Lock','Drama'
'Appointment in Honduras','Drama'
'Danton','Drama'
'Alamo','Action'
'La Chevre','Drama'
'Les Comperes','Comedy'
'Dead Poets Society','Drama'
'Othello','Drama'
'Battleground','War'
'Kings of the Road (In the Course of Time)','Drama'
'Hiroshima','Drama'
'Return of Martin Guerre','Drama'
'Somebody up There Likes Me','Drama'
'Jack Benny Show','Comedy'
'Mutiny on the Bounty','Action'
'Death Valley Days','western'
'Monty Python\'s Flying Circus','Comedy'
'Monty Python\'s Flying Circus','Comedy'
'Monty Python\'s Flying Circus','Comedy'
'Monty Python\'s Flying Circus','Comedy'
'Valkenvania','Comedy'
'Secret Policeman\'s Other Ball','Comedy'
'Taming of the Shrew','Drama'
'From Russia with Love','Action'
'Offence','Mystery'
'Hollywood Mavericks','Comedy'
'Live at Harrah\'s','Comedy'
'Persuaders','Mystery'
'Nineteen Hundred','Drama'
'Van','Comedy'
'My Country Right or Wrong','War'
'Clint Eastwood Collection','western'
'Complete Dirty Harry','Action'
'Dead Pool','Action'
'Good','western'
'Rawhide','western'
'Tightrope','Mystery'
'Hearts of Fire','Drama'
'How the West Was Won','Western'
'Mummy\'s Hand','Mystery'
'Great White Death','Action'
'Mosquito Coast','Drama'
'Today We Kill....Tomorrow We Die','Western'
'Tormenta Sobre Arizona','Drama'
'Back to the Future II','Comedy'
'Maverick','western'
'Shakespeare Series','Drama'
'Deadly Trackers','Western'
'American Film Institute','Mystery'
'A Married Man','Drama'
'Othello','Drama'
'Only Way Home','Drama'
'Tales of Tomorrow','Horror'
'Inherit the Wind','Drama'
'This Is Horror','Horror'
'Conversation Piece','Drama'
'Crimson Pirate','Action'
'Devil\'s Disciple','Mystery'
'Hallelujah Trail','Drama'
'Train','Action'
'Jay Leno: The American Dream','Comedy'
'Primal Rage','Mystery'
'Industrial Symphony','Music'
'Howie Mandel\'s North American Watusi Tour','Comedy'
'Branford Marsalis','Music'
'L. A. Story','Comedy'
'Steve Martin Live!','Comedy'
'Steve Martin','Comedy'
'Runaway Barge','Action'
'Romulus & the Sabines','Action'
'Saint','Mystery'
'Strange Brew','Comedy'
'Another Forty-Eight Hours','Action'
'Best of Eddie Murphy','Comedy'
'What about Bob?','Comedy'
'Mummy\'s Revenge','Horror'
'Harper','Mystery'
'Left Handed Gun','western'
'Once upon a Wheel','Action'
'Prize','Drama'
'Secret War of Harry Frigg','Comedy'
'Two Jakes','Mystery'
'Exile in Concert','Music'
'Joe Piscopo New Jersey Special','Comedy'
'Joe Piscopo Video','Comedy'
'Death Valley Days','western'
'Salsa: The Motion Picture','Drama'
'Hollywood\'s Greatest War Movies','War'
'Out for Justice','Action'
'Case of the Mukkinese Battle Horn','Comedy'
'Goon Show Movie','Comedy'
'Great McGonagall','Comedy'
'I\'m All Right Jack','Comedy'
'Magic Christian','Comedy'
'Never Let Go','Action'
'Pink Panther','Comedy'
'Two-Way Stretch','Comedy'
'Face at the Window','Horror'
'Tom Thumb','Science Fiction'
'Beartooth','Action'
'James Taylor in Concert','Music'
'Gangbusters','Drama'
'El Rublo de las Dos Caras','Action'
'Law & Jake Wade','Drama'
'Chuka','Western'
'Cry of the Innocent','Drama'
'Edison the Man','Drama'
'Keeper of the Flame','Drama'
'Spencer Tracy Legacy','Comedy'
'Cheyenne','Western'
'Dawn Rider','western'
'Duke','western'
'Frontier Horizon','Western'
'Hell Town','Western'
'Hurricane Express','Western'
'Hurricane Express','Action'
'In Harm\'s Way','War'
'John Wayne Collection','War'
'John Wayne Collector\'s Limited Edition','War'
'John Wayne Four Pack','Western'
'John Wayne Matinee Double Feature','Western'
'John Wayne Matinee Double Feature','western'
'John Wayne Matinee Double Feature','western'
'John Wayne Six Pack','Western'
'John Wayne Western Greats','western'
'King of the Pecos','Western'
'Lawless Frontier','Western'
'Lawless Frontier','western'
'Lawless Nineties','western'
'Lucky Texan','Western'
'McQ','Action'
'Neath Arizona Skies','Western'
'Neath the Arizona Skies','Western'
'Randy Rides Alone','Western'
'Range Feud','Western'
'Red River','Western'
'Riders of Destiny','Western'
'Sagebrush Trail','Western'
'Shadow of the Eagle','Action'
'Blood & Guns','Action'
'Hot Money','Drama'
'Comedy Tonight','Comedy'
'Robin Williams','Comedy'}

genre = [Comedy, Drama, Horror, Music, War, Science Fiction, Western]
